/******************************************************************************
 * @file        hkv_arrhythmia_pack_3.c
 * @brief       Autogenerated AOT pack kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '3' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_pack_3.h"


#define pack_3_inputs_counts (4)

// Input pack dimensions
static const int32_t pack_3_pack_dims[pack_3_inputs_counts] = {
    1,
    1,
    1,
    1,
};

// Output dimensions
static const int32_t pack_3_output_shape[] = {
    4
};

// Parameters
static const int32_t pack_3_axis = 0;
static const int32_t* pack_3_input_data[pack_3_inputs_counts];

int32_t
hkv_arrhythmia_pack_3_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_arrhythmia_pack_3_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int32_t* __restrict input_0 = (const int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_53];
    const int32_t* __restrict input_1 = (const int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_3];
    const int32_t* __restrict input_2 = (const int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_4];
    const int32_t* __restrict input_3 = (const int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_3];
    int32_t* __restrict output = (int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_54];

    pack_3_input_data[0] = input_0;
    pack_3_input_data[1] = input_1;
    pack_3_input_data[2] = input_2;
    pack_3_input_data[3] = input_3;

    return arm_concatenation_s32(
        pack_3_input_data,
        pack_3_inputs_counts,
        pack_3_pack_dims,
        pack_3_axis,
        output,
        1,
        pack_3_output_shape
    );

}