/******************************************************************************
 * @file        hkv_arrhythmia_quantize_0.c
 * @brief       Autogenerated AOT quantize kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '0' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_quantize_0.h"


static const int32_t quantize_0_output_size = 500;

// Quantization parameters
static const int32_t quantize_0_input_zero_point = 0;
static const int32_t quantize_0_output_zero_point = 7;
static const float quantize_0_output_scale = 0.13112981617450714;
int32_t
hkv_arrhythmia_quantize_0_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}

int32_t hkv_arrhythmia_quantize_0_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const float* __restrict input = (const float*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_0];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_51];    return arm_quantize_f32_s8(
        input,
        output,
        quantize_0_output_size,
        quantize_0_output_zero_point,
        quantize_0_output_scale
    );
}