/******************************************************************************
 * @file        hkv_arrhythmia_shape_1.c
 * @brief       Autogenerated AOT shape kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '1' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_shape_1.h"

// Input dimensions
alignas(16) static int32_t shape_1_dims[] = {
    1, 500, 1
};

int32_t
hkv_arrhythmia_shape_1_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_arrhythmia_shape_1_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_51];
    int32_t* __restrict output = (int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_52];

    // Copy input shape into output tensor
    arm_memcpy_s8(
        (int8_t *)output,
        (int8_t *)shape_1_dims,
        12
    );

    return 0;
}