/******************************************************************************
 * @file        hkv_arrhythmia_softmax_48.c
 * @brief       Autogenerated AOT softmax kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '48' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_softmax_48.h"

// Softmax parameters
static const int32_t softmax_48_num_rows = 1;
static const int32_t softmax_48_row_size = 4;
static const int32_t softmax_48_input_multiplier = 1802644992;
static const int32_t softmax_48_input_shift = 22;

static const int32_t softmax_48_diff_min = -496;

int32_t
hkv_arrhythmia_softmax_48_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_arrhythmia_softmax_48_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_98];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_99];

    arm_softmax_s8(
        input,
        softmax_48_num_rows,
        softmax_48_row_size,
        softmax_48_input_multiplier,
        softmax_48_input_shift,
        softmax_48_diff_min,
        output
    );

    return 0;

}