/******************************************************************************
 * @file        hkv_arrhythmia_mul_20.c
 * @brief       Autogenerated AOT mul kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '20' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_mul_20.h"
#include "hkv_arrhythmia_kernels.h"

// Per-node descriptor (rodata) consumed by the shared elementwise-multiply kernel.
static const hkv_arrhythmia_mul_desc_t mul_20_desc = {
    .input1_id = hkv_arrhythmia_tensor_66,
    .input2_id = hkv_arrhythmia_tensor_70,
    .output_id = hkv_arrhythmia_tensor_71,
    .input1_dims = {
    .n = 1, .h = 1,
    .w = 63, .c = 24
},
    .input2_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 24
},
    .output_dims = {
    .n = 1, .h = 1,
    .w = 63, .c = 24
},
    .input1_offset = 128,
    .input2_offset = 128,
    .output_offset = -128,
    .output_multiplier = 1278400928,
    .output_shift = -7,
    .activation_min = -128,
    .activation_max = 127,
};

int32_t hkv_arrhythmia_mul_20_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    return hkv_arrhythmia_kernel_mul_s8(ctx, &mul_20_desc);
}
