/******************************************************************************
 * @file        hkv_arrhythmia_conv_2d_29.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '29' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_conv_2d_29.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_29_input_dims = {
    .n = 1, .h = 1,
    .w = 32, .c = 32
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_29_filter_dims = {
    .n =  48, .h = 1,
    .w = 1, .c = 32
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_29_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 48
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_29_output_dims = {
    .n = 1, .h = 1,
    .w = 32, .c = 48
};


// Quantization parameters (per-channel quantization)

static const int32_t conv_2d_29_input_zero_point = -128;
static const int32_t conv_2d_29_output_zero_point = -1;

// Scratch buffer context
static cmsis_nn_context conv_2d_29_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context conv_2d_29_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};


const cmsis_nn_conv_params conv_2d_29_params = {
    .input_offset = -conv_2d_29_input_zero_point,
    .output_offset = conv_2d_29_output_zero_point,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

// Grouped-conv semantics are derived inside the dispatched kernel from the
// input/filter channel relationship; helia-aot does not carry a separate AIR
// "groups" field for CONV_2D in this path.

int32_t
hkv_arrhythmia_conv_2d_29_init(
    hkv_arrhythmia_model_context_t *ctx
) {

    conv_2d_29_ctx.buf = NULL;
    conv_2d_29_ctx.size = 0;

    conv_2d_29_weight_sum_ctx.buf = ctx->tensor_ptrs[hkv_arrhythmia_tensor_conv_2d_29_weight_sum];
    conv_2d_29_weight_sum_ctx.size = 192;

    return ARM_CMSIS_NN_SUCCESS;

}

int32_t
hkv_arrhythmia_conv_2d_29_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_79];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_80];

    // Per-channel quantization tables resolved from interned constant tensors.
    const cmsis_nn_per_channel_quant_params conv_2d_29_quant_params = {
        .multiplier = (int32_t *)ctx->tensor_ptrs[hkv_arrhythmia_tensor_conv_2d_29_multiplier],
        .shift = (int32_t *)ctx->tensor_ptrs[hkv_arrhythmia_tensor_conv_2d_29_shift],
    };


    // Bias pointer
    const int32_t *conv_2d_29_bias_ptr = NULL;

    return arm_convolve_1x1_s8_fast(
        &conv_2d_29_ctx,
        &conv_2d_29_weight_sum_ctx,
        &conv_2d_29_params,
        &conv_2d_29_quant_params,
        &conv_2d_29_input_dims,
        input,
        &conv_2d_29_filter_dims,
        (int8_t *)ctx->tensor_ptrs[hkv_arrhythmia_tensor_25],
        &conv_2d_29_bias_dims,
        conv_2d_29_bias_ptr,
        &conv_2d_29_output_dims,
        output
    );

}