/******************************************************************************
 * @file        hkv_arrhythmia_mean_40.c
 * @brief       Autogenerated AOT mean kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '40' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_mean_40.h"


// Input dimensions
static const cmsis_nn_dims mean_40_input_dims = {
    .n = 1, .h = 1,
    .w = 8, .c = 64
};

// Axis dimensions: either 0 or 1 w/ 1 indicating reduction axis
static const cmsis_nn_dims mean_40_axis_dims = {
    .n = 0, .h = 1,
    .w = 1, .c = 0
};

// Output dimensions
static const cmsis_nn_dims mean_40_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 64
};

// Quantization parameters
static const int32_t mean_40_input_zero_point = -128;
static const int32_t mean_40_output_zero_point = -128;
static const int32_t mean_40_multiplier = 1686720337;
static const int32_t mean_40_shift = -2;


int32_t
hkv_arrhythmia_mean_40_init(
    hkv_arrhythmia_model_context_t *ctx
) {

    return 0;
}

int32_t
hkv_arrhythmia_mean_40_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_90];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_91];

    return arm_mean_s8(
        input,
        &mean_40_input_dims,
        -mean_40_input_zero_point,
        &mean_40_axis_dims,
        output,
        &mean_40_output_dims,
        mean_40_output_zero_point,
        mean_40_multiplier,
        mean_40_shift
    );

}