/******************************************************************************
 * @file        hkv_arrhythmia_tensors.c
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_tensors.h"


//── Memory Arenas ─────────────────────────────────────────────────────────────

const size_t hkv_arrhythmia_arena_sizes[hkv_arrhythmia_num_arena_buffers] = {
    [hkv_arrhythmia_arena_dtcm] = hkv_arrhythmia_arena_dtcm_size,
    [hkv_arrhythmia_arena_const_dtcm] = hkv_arrhythmia_arena_const_dtcm_size,
};

// Per-region alignment (bytes). Caller-supplied buffers passed to
// ``hkv_arrhythmia_bind_arena`` must be aligned to at least this many
// bytes for the region; otherwise the bind is rejected with status
// 4. Internal arena buffers are emitted with ``alignas(...)`` matching
// these values, so ``allocate_arenas=true`` builds always satisfy the
// constraint.
const size_t hkv_arrhythmia_arena_alignments[hkv_arrhythmia_num_arena_buffers] = {
    [hkv_arrhythmia_arena_dtcm] = 16,
    [hkv_arrhythmia_arena_const_dtcm] = 16,
};

// Internal arena buffers. Writable arenas (scratch, persistent, and
// staged-constant runtime copies) are uninitialized BSS-backed
// storage; cold-constant arenas are read-only blobs whose bytes are
// initialised in hkv_arrhythmia_constants.c.
alignas(16) static HKV_ARRHYTHMIA_PUT_IN_DTCM int8_t hkv_arrhythmia_arena_dtcm_buffer[hkv_arrhythmia_arena_dtcm_size];

extern HKV_ARRHYTHMIA_PUT_IN_DTCM_INIT int8_t hkv_arrhythmia_arena_const_dtcm__blob[25380];

const void * const hkv_arrhythmia_arena_buffers[hkv_arrhythmia_num_arena_buffers] = {
    [hkv_arrhythmia_arena_dtcm] = hkv_arrhythmia_arena_dtcm_buffer,
    // Cold constant arena: kernels read directly from the in-image blob.
    [hkv_arrhythmia_arena_const_dtcm] = hkv_arrhythmia_arena_const_dtcm__blob,
};


//── Model Input/Output ────────────────────────────────────────────────────────

const hkv_arrhythmia_tensor_ident_t hkv_arrhythmia_inputs_id[hkv_arrhythmia_num_inputs] = {
    hkv_arrhythmia_tensor_0,
};

const hkv_arrhythmia_tensor_ident_t hkv_arrhythmia_outputs_id[hkv_arrhythmia_num_outputs] = {
    hkv_arrhythmia_tensor_100,
};

const int32_t hkv_arrhythmia_inputs_len[hkv_arrhythmia_num_inputs] = {
    500,
};

const int32_t hkv_arrhythmia_inputs_zero_point[hkv_arrhythmia_num_inputs] = {
    0,
};

const float hkv_arrhythmia_inputs_scale[hkv_arrhythmia_num_inputs] = {
    1,
};

const int32_t hkv_arrhythmia_outputs_len[hkv_arrhythmia_num_outputs] = {
    4,
};

const int32_t hkv_arrhythmia_outputs_zero_point[hkv_arrhythmia_num_outputs] = {
    0,
};

const float hkv_arrhythmia_outputs_scale[hkv_arrhythmia_num_outputs] = {
    1,
};

//── Model Tensors ─────────────────────────────────────────────────────────────

// Tensor descriptors. Uniform shape: every tensor lives in an arena
// slot, addressed by ``(region, offset)``.
const hkv_arrhythmia_tensor_descriptor_t hkv_arrhythmia_tensor_descriptors[hkv_arrhythmia_num_tensors] = {
    [hkv_arrhythmia_tensor_0] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 2000,
    },
    [hkv_arrhythmia_tensor_2] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 25376,
        .size = 4,
    },
    [hkv_arrhythmia_tensor_3] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 25376,
        .size = 4,
    },
    [hkv_arrhythmia_tensor_4] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 0,
        .size = 4,
    },
    [hkv_arrhythmia_tensor_7] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 25008,
        .size = 320,
    },
    [hkv_arrhythmia_tensor_9] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 18928,
        .size = 5120,
    },
    [hkv_arrhythmia_tensor_11] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 17136,
        .size = 1024,
    },
    [hkv_arrhythmia_tensor_13] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 15920,
        .size = 1024,
    },
    [hkv_arrhythmia_tensor_15] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 14576,
        .size = 576,
    },
    [hkv_arrhythmia_tensor_17] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 10736,
        .size = 3072,
    },
    [hkv_arrhythmia_tensor_19] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 9584,
        .size = 576,
    },
    [hkv_arrhythmia_tensor_21] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 8864,
        .size = 576,
    },
    [hkv_arrhythmia_tensor_23] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 7856,
        .size = 432,
    },
    [hkv_arrhythmia_tensor_25] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5744,
        .size = 1536,
    },
    [hkv_arrhythmia_tensor_27] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5104,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_29] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 4752,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_31] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 4080,
        .size = 288,
    },
    [hkv_arrhythmia_tensor_33] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2928,
        .size = 768,
    },
    [hkv_arrhythmia_tensor_35] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2496,
        .size = 144,
    },
    [hkv_arrhythmia_tensor_37] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2256,
        .size = 144,
    },
    [hkv_arrhythmia_tensor_39] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 1744,
        .size = 216,
    },
    [hkv_arrhythmia_tensor_41] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 1072,
        .size = 384,
    },
    [hkv_arrhythmia_tensor_42] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 1056,
        .size = 1,
    },
    [hkv_arrhythmia_tensor_44] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 800,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_46] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 688,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_48] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 352,
        .size = 144,
    },
    [hkv_arrhythmia_tensor_50] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 16,
        .size = 144,
    },
    [hkv_arrhythmia_tensor_51] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2000,
        .size = 500,
    },
    [hkv_arrhythmia_tensor_52] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 12,
    },
    [hkv_arrhythmia_tensor_53] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 16,
        .size = 4,
    },
    [hkv_arrhythmia_tensor_54] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_55] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2000,
        .size = 500,
    },
    [hkv_arrhythmia_tensor_56] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2512,
        .size = 4000,
    },
    [hkv_arrhythmia_tensor_57] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 6512,
        .size = 4000,
    },
    [hkv_arrhythmia_tensor_58] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 2000,
    },
    [hkv_arrhythmia_tensor_59] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2000,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_60] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2016,
        .size = 4,
    },
    [hkv_arrhythmia_tensor_61] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2000,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_62] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2016,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_63] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2032,
        .size = 2000,
    },
    [hkv_arrhythmia_tensor_64] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 4032,
        .size = 3000,
    },
    [hkv_arrhythmia_tensor_65] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 3000,
    },
    [hkv_arrhythmia_tensor_66] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 3008,
        .size = 1512,
    },
    [hkv_arrhythmia_tensor_67] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 24,
    },
    [hkv_arrhythmia_tensor_68] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 32,
        .size = 6,
    },
    [hkv_arrhythmia_tensor_69] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 24,
    },
    [hkv_arrhythmia_tensor_70] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 32,
        .size = 24,
    },
    [hkv_arrhythmia_tensor_71] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 64,
        .size = 1512,
    },
    [hkv_arrhythmia_tensor_72] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1584,
        .size = 2016,
    },
    [hkv_arrhythmia_tensor_73] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 3600,
        .size = 2016,
    },
    [hkv_arrhythmia_tensor_74] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 1024,
    },
    [hkv_arrhythmia_tensor_75] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1024,
        .size = 32,
    },
    [hkv_arrhythmia_tensor_76] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1056,
        .size = 8,
    },
    [hkv_arrhythmia_tensor_77] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1024,
        .size = 32,
    },
    [hkv_arrhythmia_tensor_78] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1056,
        .size = 32,
    },
    [hkv_arrhythmia_tensor_79] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1088,
        .size = 1024,
    },
    [hkv_arrhythmia_tensor_80] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2112,
        .size = 1536,
    },
    [hkv_arrhythmia_tensor_81] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 1536,
    },
    [hkv_arrhythmia_tensor_82] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1536,
        .size = 768,
    },
    [hkv_arrhythmia_tensor_83] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 48,
    },
    [hkv_arrhythmia_tensor_84] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 48,
        .size = 12,
    },
    [hkv_arrhythmia_tensor_85] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 48,
    },
    [hkv_arrhythmia_tensor_86] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 48,
        .size = 48,
    },
    [hkv_arrhythmia_tensor_87] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 96,
        .size = 768,
    },
    [hkv_arrhythmia_tensor_88] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 864,
        .size = 1024,
    },
    [hkv_arrhythmia_tensor_89] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 1888,
        .size = 1024,
    },
    [hkv_arrhythmia_tensor_90] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 512,
    },
    [hkv_arrhythmia_tensor_91] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 512,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_92] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 576,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_93] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 512,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_94] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 576,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_95] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 640,
        .size = 512,
    },
    [hkv_arrhythmia_tensor_96] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 640,
    },
    [hkv_arrhythmia_tensor_97] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 640,
        .size = 80,
    },
    [hkv_arrhythmia_tensor_98] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 4,
    },
    [hkv_arrhythmia_tensor_99] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 16,
        .size = 4,
    },
    [hkv_arrhythmia_tensor_100] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_conv_2d_5_scratch] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 0,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_5_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 160,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_5_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 224,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_5_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 288,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_6_scratch] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 10512,
        .size = 4464,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_6_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 496,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_6_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 560,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_6_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 624,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_9_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 752,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_conv_2d_9_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 768,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_conv_2d_9_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 784,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_conv_2d_10_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 864,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_10_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 928,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_10_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 992,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_13_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 1456,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_conv_2d_13_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 1552,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_conv_2d_13_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 1648,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_14_scratch] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 7040,
        .size = 4464,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_14_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 1968,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_14_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2064,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_14_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2160,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_conv_2d_17_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2400,
        .size = 24,
    },
    [hkv_arrhythmia_tensor_conv_2d_17_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2432,
        .size = 24,
    },
    [hkv_arrhythmia_tensor_conv_2d_17_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2464,
        .size = 24,
    },
    [hkv_arrhythmia_tensor_conv_2d_18_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2640,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_conv_2d_18_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2736,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_conv_2d_18_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 2832,
        .size = 96,
    },
    [hkv_arrhythmia_tensor_conv_2d_21_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 3696,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_conv_2d_21_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 3824,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_conv_2d_21_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 3952,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_22_scratch] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 5616,
        .size = 4464,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_22_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 4368,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_22_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 4496,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_22_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 4624,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_conv_2d_25_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5008,
        .size = 32,
    },
    [hkv_arrhythmia_tensor_conv_2d_25_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5040,
        .size = 32,
    },
    [hkv_arrhythmia_tensor_conv_2d_25_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5072,
        .size = 32,
    },
    [hkv_arrhythmia_tensor_conv_2d_26_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5360,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_conv_2d_26_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5488,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_conv_2d_26_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 5616,
        .size = 128,
    },
    [hkv_arrhythmia_tensor_conv_2d_29_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 7280,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_conv_2d_29_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 7472,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_conv_2d_29_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 7664,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_30_scratch] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 3648,
        .size = 4464,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_30_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 8288,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_30_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 8480,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_30_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 8672,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_conv_2d_33_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 9440,
        .size = 48,
    },
    [hkv_arrhythmia_tensor_conv_2d_33_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 9488,
        .size = 48,
    },
    [hkv_arrhythmia_tensor_conv_2d_33_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 9536,
        .size = 48,
    },
    [hkv_arrhythmia_tensor_conv_2d_34_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 10160,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_conv_2d_34_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 10352,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_conv_2d_34_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 10544,
        .size = 192,
    },
    [hkv_arrhythmia_tensor_conv_2d_37_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 13808,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_conv_2d_37_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 14064,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_conv_2d_37_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 14320,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_38_scratch] = {
        .type = hkv_arrhythmia_tensor_type_scratch,
        .region = hkv_arrhythmia_arena_dtcm,
        .offset = 2912,
        .size = 4464,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_38_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 15152,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_38_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 15408,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_depthwise_conv_2d_38_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 15664,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_conv_2d_41_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 16944,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_41_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 17008,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_41_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 17072,
        .size = 64,
    },
    [hkv_arrhythmia_tensor_conv_2d_42_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 18160,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_conv_2d_42_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 18416,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_conv_2d_42_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 18672,
        .size = 256,
    },
    [hkv_arrhythmia_tensor_conv_2d_45_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 24048,
        .size = 320,
    },
    [hkv_arrhythmia_tensor_conv_2d_45_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 24368,
        .size = 320,
    },
    [hkv_arrhythmia_tensor_conv_2d_45_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 24688,
        .size = 320,
    },
    [hkv_arrhythmia_tensor_fully_connected_47_weight_sum] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 25328,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_fully_connected_47_multiplier] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 25344,
        .size = 16,
    },
    [hkv_arrhythmia_tensor_fully_connected_47_shift] = {
        .type = hkv_arrhythmia_tensor_type_constant,
        .region = hkv_arrhythmia_arena_const_dtcm,
        .offset = 25360,
        .size = 16,
    },
};