/******************************************************************************
 * @file        hkv_arrhythmia_reshape_4.c
 * @brief       Autogenerated AOT reshape kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '4' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_reshape_4.h"


int32_t
hkv_arrhythmia_reshape_4_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_arrhythmia_reshape_4_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_51];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_55];
    if (input == output) { return 0; }

    arm_memcpy_s8(
        output,
        input,
        500
    );

    return 0;

}