/******************************************************************************
 * @file        hkv_arrhythmia_fully_connected_47.c
 * @brief       Autogenerated AOT fully_connected kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '47' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/


#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_fully_connected_47.h"
#include "hkv_arrhythmia_kernels.h"

// Per-node descriptor (rodata) consumed by the shared per-channel int8
// fully-connected kernel. The kernel-sum scratch (when present) is resolved
// inside the shared helper, so this node needs no init.
static const hkv_arrhythmia_fc_per_channel_s8_desc_t fully_connected_47_desc = {
    .input_id = hkv_arrhythmia_tensor_97,
    .output_id = hkv_arrhythmia_tensor_98,
    .weights_id = hkv_arrhythmia_tensor_7,
    .bias_id = -1,
    .multiplier_id = hkv_arrhythmia_tensor_fully_connected_47_multiplier,
    .shift_id = hkv_arrhythmia_tensor_fully_connected_47_shift,
    .weight_sum_id = hkv_arrhythmia_tensor_fully_connected_47_weight_sum,
    .weight_sum_bytes = 16,
    .input_dims = { .n = 1, .h = 1, .w = 1, .c = 80 },
    .filter_dims = { .n = 80, .h = 1, .w = 1, .c = 4 },
    .bias_dims = { .n = 1, .h = 1, .w = 1, .c = 4 },
    .output_dims = { .n = 1, .h = 1, .w = 1, .c = 4 },
    .input_offset = 3,
    .filter_offset = 0,
    .output_offset = 8,
    .activation_min = -128,
    .activation_max = 127,
};

int32_t
hkv_arrhythmia_fully_connected_47_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    return hkv_arrhythmia_kernel_fc_per_channel_s8(ctx, &fully_connected_47_desc);
}
