/******************************************************************************
 * @file        hkv_arrhythmia_kernels.c
 * @brief       Autogenerated heliaAOT shared operator kernels
 * @details     Shared kernel runtimes for elementwise ADD/MUL and per-channel int8 FULLY_CONNECTED nodes.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_kernels.h"

int32_t hkv_arrhythmia_kernel_fc_per_channel_s8(
    hkv_arrhythmia_model_context_t *ctx,
    const hkv_arrhythmia_fc_per_channel_s8_desc_t *d
) {
    cmsis_nn_context fc_ctx = { .buf = NULL, .size = 0 };
    if (d->weight_sum_id >= 0) {
        fc_ctx.buf = ctx->tensor_ptrs[d->weight_sum_id];
        fc_ctx.size = d->weight_sum_bytes;
    }

    cmsis_nn_fc_params params = {
        .input_offset = d->input_offset,
        .filter_offset = d->filter_offset,
        .output_offset = d->output_offset,
        .activation.min = d->activation_min,
        .activation.max = d->activation_max,
    };

    const cmsis_nn_per_channel_quant_params quant_params = {
        .multiplier = (int32_t *)ctx->tensor_ptrs[d->multiplier_id],
        .shift = (int32_t *)ctx->tensor_ptrs[d->shift_id],
    };

    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[d->input_id];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[d->output_id];
    const int8_t* weights = (const int8_t*)ctx->tensor_ptrs[d->weights_id];
    const int32_t *bias = (d->bias_id >= 0) ? (const int32_t *)ctx->tensor_ptrs[d->bias_id] : NULL;

    return arm_fully_connected_per_channel_s8(
        &fc_ctx,
        &params,
        &quant_params,
        &d->input_dims,
        input,
        &d->filter_dims,
        weights,
        &d->bias_dims,
        bias,
        &d->output_dims,
        output
    );
}
int32_t hkv_arrhythmia_kernel_mul_s8(
    hkv_arrhythmia_model_context_t *ctx,
    const hkv_arrhythmia_mul_desc_t *d
) {
    const int8_t* __restrict input1 = (const int8_t*)ctx->tensor_ptrs[d->input1_id];
    const int8_t* __restrict input2 = (const int8_t*)ctx->tensor_ptrs[d->input2_id];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[d->output_id];

    return arm_mul_s8(
        input1,
        &d->input1_dims,
        input2,
        &d->input2_dims,
        d->input1_offset,
        d->input2_offset,
        output,
        &d->output_dims,
        d->output_offset,
        d->output_multiplier,
        d->output_shift,
        d->activation_min,
        d->activation_max
    );
}
