/******************************************************************************
 * @file        hkv_arrhythmia_model.c
 * @brief       Autogenerated heliaAOT model
 * @details     Model: hkv_arrhythmia - MLIR Converted.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_operators.h"
#include "hkv_arrhythmia_model.h"

//── Table-driven operator dispatch ────────────────────────────────────────────
//
// Every operator exposes the uniform ``(ctx) -> status`` ABI and resolves its
// own tensor I/O internally from ``ctx->tensor_ptrs``. The model therefore
// marshals nothing: ``model_init`` / ``model_run`` simply iterate one rodata
// table instead of emitting an unrolled call site per operator. This collapses
// dispatcher code size (critical for large unrolled RNN graphs) while
// preserving the exact per-operator callback contract used below.
//
// The loop body is the single integration chokepoint for long-term hooks: an
// RTOS scheduler can yield between entries, and per-layer PMU counters can be
// sampled around ``e->run(ctx)`` via the existing ``ctx->callback`` seam, which
// still receives the stable AIR operator id (``e->id``).

typedef int32_t (*hkv_arrhythmia_op_fn)(hkv_arrhythmia_model_context_t *ctx);

typedef struct {
    hkv_arrhythmia_op_fn init; // Per-operator init hook
    hkv_arrhythmia_op_fn run;  // Per-operator run hook (resolves its own I/O)
    int32_t id;              // Stable AIR operator id, forwarded to callbacks
} hkv_arrhythmia_op_entry_t;

// Operator dispatch table — one rodata entry per operator, in execution order.
// Operators with no per-instance init record a NULL init slot; the init loop
// skips the call while still firing the init callback contract.
static const hkv_arrhythmia_op_entry_t hkv_arrhythmia_op_table[50] = {
    { hkv_arrhythmia_quantize_0_init, hkv_arrhythmia_quantize_0_run, 0 },
    { hkv_arrhythmia_shape_1_init, hkv_arrhythmia_shape_1_run, 1 },
    { hkv_arrhythmia_strided_slice_2_init, hkv_arrhythmia_strided_slice_2_run, 2 },
    { hkv_arrhythmia_pack_3_init, hkv_arrhythmia_pack_3_run, 3 },
    { hkv_arrhythmia_reshape_4_init, hkv_arrhythmia_reshape_4_run, 4 },
    { hkv_arrhythmia_conv_2d_5_init, hkv_arrhythmia_conv_2d_5_run, 5 },
    { hkv_arrhythmia_depthwise_conv_2d_6_init, hkv_arrhythmia_depthwise_conv_2d_6_run, 6 },
    { hkv_arrhythmia_max_pool_2d_7_init, hkv_arrhythmia_max_pool_2d_7_run, 7 },
    { hkv_arrhythmia_mean_8_init, hkv_arrhythmia_mean_8_run, 8 },
    { hkv_arrhythmia_conv_2d_9_init, hkv_arrhythmia_conv_2d_9_run, 9 },
    { hkv_arrhythmia_conv_2d_10_init, hkv_arrhythmia_conv_2d_10_run, 10 },
    { NULL, hkv_arrhythmia_mul_11_run, 11 },
    { NULL, hkv_arrhythmia_mul_12_run, 12 },
    { hkv_arrhythmia_conv_2d_13_init, hkv_arrhythmia_conv_2d_13_run, 13 },
    { hkv_arrhythmia_depthwise_conv_2d_14_init, hkv_arrhythmia_depthwise_conv_2d_14_run, 14 },
    { hkv_arrhythmia_max_pool_2d_15_init, hkv_arrhythmia_max_pool_2d_15_run, 15 },
    { hkv_arrhythmia_mean_16_init, hkv_arrhythmia_mean_16_run, 16 },
    { hkv_arrhythmia_conv_2d_17_init, hkv_arrhythmia_conv_2d_17_run, 17 },
    { hkv_arrhythmia_conv_2d_18_init, hkv_arrhythmia_conv_2d_18_run, 18 },
    { NULL, hkv_arrhythmia_mul_19_run, 19 },
    { NULL, hkv_arrhythmia_mul_20_run, 20 },
    { hkv_arrhythmia_conv_2d_21_init, hkv_arrhythmia_conv_2d_21_run, 21 },
    { hkv_arrhythmia_depthwise_conv_2d_22_init, hkv_arrhythmia_depthwise_conv_2d_22_run, 22 },
    { hkv_arrhythmia_max_pool_2d_23_init, hkv_arrhythmia_max_pool_2d_23_run, 23 },
    { hkv_arrhythmia_mean_24_init, hkv_arrhythmia_mean_24_run, 24 },
    { hkv_arrhythmia_conv_2d_25_init, hkv_arrhythmia_conv_2d_25_run, 25 },
    { hkv_arrhythmia_conv_2d_26_init, hkv_arrhythmia_conv_2d_26_run, 26 },
    { NULL, hkv_arrhythmia_mul_27_run, 27 },
    { NULL, hkv_arrhythmia_mul_28_run, 28 },
    { hkv_arrhythmia_conv_2d_29_init, hkv_arrhythmia_conv_2d_29_run, 29 },
    { hkv_arrhythmia_depthwise_conv_2d_30_init, hkv_arrhythmia_depthwise_conv_2d_30_run, 30 },
    { hkv_arrhythmia_max_pool_2d_31_init, hkv_arrhythmia_max_pool_2d_31_run, 31 },
    { hkv_arrhythmia_mean_32_init, hkv_arrhythmia_mean_32_run, 32 },
    { hkv_arrhythmia_conv_2d_33_init, hkv_arrhythmia_conv_2d_33_run, 33 },
    { hkv_arrhythmia_conv_2d_34_init, hkv_arrhythmia_conv_2d_34_run, 34 },
    { NULL, hkv_arrhythmia_mul_35_run, 35 },
    { NULL, hkv_arrhythmia_mul_36_run, 36 },
    { hkv_arrhythmia_conv_2d_37_init, hkv_arrhythmia_conv_2d_37_run, 37 },
    { hkv_arrhythmia_depthwise_conv_2d_38_init, hkv_arrhythmia_depthwise_conv_2d_38_run, 38 },
    { hkv_arrhythmia_max_pool_2d_39_init, hkv_arrhythmia_max_pool_2d_39_run, 39 },
    { hkv_arrhythmia_mean_40_init, hkv_arrhythmia_mean_40_run, 40 },
    { hkv_arrhythmia_conv_2d_41_init, hkv_arrhythmia_conv_2d_41_run, 41 },
    { hkv_arrhythmia_conv_2d_42_init, hkv_arrhythmia_conv_2d_42_run, 42 },
    { NULL, hkv_arrhythmia_mul_43_run, 43 },
    { NULL, hkv_arrhythmia_mul_44_run, 44 },
    { hkv_arrhythmia_conv_2d_45_init, hkv_arrhythmia_conv_2d_45_run, 45 },
    { hkv_arrhythmia_mean_46_init, hkv_arrhythmia_mean_46_run, 46 },
    { NULL, hkv_arrhythmia_fully_connected_47_run, 47 },
    { hkv_arrhythmia_softmax_48_init, hkv_arrhythmia_softmax_48_run, 48 },
    { hkv_arrhythmia_dequantize_49_init, hkv_arrhythmia_dequantize_49_run, 49 },
};

int32_t hkv_arrhythmia_model_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    if (ctx == NULL) {
        return hkv_arrhythmia_status_null_context;
    }
    int32_t status = 0;

    status = hkv_arrhythmia_context_init(ctx);
    if (status != 0) {
        return status;
    }

    // Drive every operator's init hook through the dispatch table. The callback
    // contract (init_started / init_finished with the AIR op id) is preserved
    // exactly; only the unrolled call sites are collapsed into this loop.
    for (uint32_t i = 0; i < 50; ++i) {
        const hkv_arrhythmia_op_entry_t *e = &hkv_arrhythmia_op_table[i];
        if (ctx->callback) { ctx->callback(e->id, hkv_arrhythmia_op_state_init_started, status, ctx->user_data); }
        if (e->init) { status = e->init(ctx); }
        if (ctx->callback) { ctx->callback(e->id, hkv_arrhythmia_op_state_init_finished, status, ctx->user_data); }
        if (status != 0) { return status; }
    }

    // All operator inits succeeded — arm the lifecycle latch so
    // model_run accepts this context.
    ctx->_lifecycle_state = 1;

    return status;
}

int32_t hkv_arrhythmia_model_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    if (ctx == NULL) {
        return hkv_arrhythmia_status_null_context;
    }

    // Reject runs when model_init was never called or failed.
    if (ctx->_lifecycle_state != 1) {
        return hkv_arrhythmia_status_not_initialized;
    }

    int32_t status = 0;

    // Drive every operator's run hook through the dispatch table. Each operator
    // resolves its own typed tensor pointers from the context, keeping the loop
    // uniform. This is the single seam for RTOS scheduling / PMU sampling.
    for (uint32_t i = 0; i < 50; ++i) {
        const hkv_arrhythmia_op_entry_t *e = &hkv_arrhythmia_op_table[i];
        if (ctx->callback) { ctx->callback(e->id, hkv_arrhythmia_op_state_run_started, status, ctx->user_data); }
        status = e->run(ctx);
        if (ctx->callback) { ctx->callback(e->id, hkv_arrhythmia_op_state_run_finished, status, ctx->user_data); }
        if (status != 0) { return status; }
    }
    return status;
}