/******************************************************************************
 * @file        hkv_arrhythmia_strided_slice_2.c
 * @brief       Autogenerated AOT strided_slice kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '2' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_strided_slice_2.h"


// Input dimensions
static const cmsis_nn_dims strided_slice_2_input_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 3
};

// Begin dimensions
static const cmsis_nn_dims strided_slice_2_begin_dims = {
    .n = 0, .h = 0,
    .w = 0, .c = 0
};

// Stride dimensions
static const cmsis_nn_dims strided_slice_2_stride_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 1
};

// Computed output dimensions from slices (without shrink or new axis masks)
static const cmsis_nn_dims strided_slice_2_computed_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 1
};

// Output dimensions
static const cmsis_nn_dims strided_slice_2_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 1
};

int32_t
hkv_arrhythmia_strided_slice_2_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_arrhythmia_strided_slice_2_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int32_t* __restrict input = (const int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_52];
    int32_t* __restrict output = (int32_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_53];
    return arm_strided_slice_s32(
        input,
        output,
        &strided_slice_2_input_dims,
        &strided_slice_2_begin_dims,
        &strided_slice_2_stride_dims,
        &strided_slice_2_computed_output_dims
    );

}