/******************************************************************************
 * @file        hkv_arrhythmia_dequantize_49.c
 * @brief       Autogenerated AOT dequantize kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '49' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_dequantize_49.h"

static const int32_t dequantize_49_output_size = 4;
static const int32_t dequantize_49_input_zero_point = -128;
static const float dequantize_49_input_scale = 0.00390625;

int32_t
hkv_arrhythmia_dequantize_49_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}

int32_t hkv_arrhythmia_dequantize_49_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_99];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_100];
    return arm_dequantize_s8_f32(
        input,
        output,
        dequantize_49_output_size,
        dequantize_49_input_zero_point,
        dequantize_49_input_scale
    );
}