/******************************************************************************
 * @file        hkv_arrhythmia_test_case.c
 * @brief       Autogenerated heliaAOT test case
 * @details     This file is used to verify the correctness of the module.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdlib.h>

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_model.h"
#include "hkv_arrhythmia_test_case.h"


//── Optional cycle counter probe ──────────────────────────────────────────────
// The E2E Corstone builds pre-include the CMSIS device header (ARMCM55.h /
// ARMCM4_FP.h), so DWT and the debug control block are visible here when the
// target exposes a cycle counter. We time only model_run() inside the
// iteration loop so the metric stays focused on dispatch + kernel execution
// rather than init or output verification.
//
// CMSIS 6 deprecates the CMSIS 5 ``CoreDebug`` spelling in favour of ``DCB``:
// 6.0.0 omitted it, while 6.1.0+ retains it as a deprecated alias. Prefer
// ``DCB`` and fall back to ``CoreDebug`` for compatible CMSIS layouts.
#if defined(DCB) && defined(DCB_DEMCR_TRCENA_Msk)
#define HKV_ARRHYTHMIA_TEST_DEMCR       (DCB->DEMCR)
#define HKV_ARRHYTHMIA_TEST_DEMCR_TRCENA DCB_DEMCR_TRCENA_Msk
#elif defined(CoreDebug) && defined(CoreDebug_DEMCR_TRCENA_Msk)
#define HKV_ARRHYTHMIA_TEST_DEMCR       (CoreDebug->DEMCR)
#define HKV_ARRHYTHMIA_TEST_DEMCR_TRCENA CoreDebug_DEMCR_TRCENA_Msk
#endif

typedef enum {
    hkv_arrhythmia_test_counter_unavailable = 0,
    hkv_arrhythmia_test_counter_pmu,
    hkv_arrhythmia_test_counter_dwt,
    hkv_arrhythmia_test_counter_systick,
} hkv_arrhythmia_test_counter_kind_t;

static hkv_arrhythmia_test_counter_kind_t hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_unavailable;

static void hkv_arrhythmia_test_cycle_counter_probe_spin(void)
{
    for (volatile uint32_t i = 0; i < 64U; ++i) {
#if defined(__NOP)
        __NOP();
#endif
    }
}

static int hkv_arrhythmia_test_cycle_counter_enable(void)
{
#if defined(__PMU_PRESENT) && (__PMU_PRESENT == 1U)
    uint32_t pmu_start = 0;
    uint32_t pmu_end = 0;
    ARM_PMU_Disable();
    ARM_PMU_CYCCNT_Reset();
    ARM_PMU_Enable();
    ARM_PMU_CNTR_Enable(PMU_CNTENSET_CCNTR_ENABLE_Msk);
    pmu_start = ARM_PMU_Get_CCNTR();
    hkv_arrhythmia_test_cycle_counter_probe_spin();
    pmu_end = ARM_PMU_Get_CCNTR();
    if (((PMU->CNTENSET & PMU_CNTENSET_CCNTR_ENABLE_Msk) != 0U) && (pmu_end != pmu_start)) {
        hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_pmu;
        return 1;
    }
#elif defined(DWT) && defined(DWT_CTRL_CYCCNTENA_Msk) && defined(HKV_ARRHYTHMIA_TEST_DEMCR)
    uint32_t dwt_start = 0;
    uint32_t dwt_end = 0;
    HKV_ARRHYTHMIA_TEST_DEMCR |= HKV_ARRHYTHMIA_TEST_DEMCR_TRCENA;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
    dwt_start = DWT->CYCCNT;
    hkv_arrhythmia_test_cycle_counter_probe_spin();
    dwt_end = DWT->CYCCNT;
    if (((DWT->CTRL & DWT_CTRL_CYCCNTENA_Msk) != 0U) && (dwt_end != dwt_start)) {
        hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_dwt;
        return 1;
    }
#endif

#if defined(SysTick) && defined(SysTick_LOAD_RELOAD_Msk) && defined(SysTick_CTRL_ENABLE_Msk) && defined(SysTick_CTRL_CLKSOURCE_Msk)
    uint32_t systick_start = 0;
    uint32_t systick_end = 0;
    SysTick->CTRL = 0;
    SysTick->LOAD = SysTick_LOAD_RELOAD_Msk;
    SysTick->VAL = 0;
    SysTick->CTRL = SysTick_CTRL_ENABLE_Msk | SysTick_CTRL_CLKSOURCE_Msk;
    systick_start = SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
    hkv_arrhythmia_test_cycle_counter_probe_spin();
    systick_end = SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
    if (systick_end != systick_start) {
        hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_systick;
        return 1;
    }
#endif

    hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_unavailable;
    return 0;
}

static uint32_t hkv_arrhythmia_test_cycle_counter_read(void)
{
    switch (hkv_arrhythmia_test_counter_kind) {
        case hkv_arrhythmia_test_counter_pmu:
#if defined(__PMU_PRESENT) && (__PMU_PRESENT == 1U)
            return ARM_PMU_Get_CCNTR();
#else
            return 0;
#endif
        case hkv_arrhythmia_test_counter_dwt:
#if defined(DWT) && defined(DWT_CTRL_CYCCNTENA_Msk)
            return DWT->CYCCNT;
#else
            return 0;
#endif
        case hkv_arrhythmia_test_counter_systick:
#if defined(SysTick) && defined(SysTick_LOAD_RELOAD_Msk)
            return SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
#else
            return 0;
#endif
        default:
            return 0;
    }
}

static uint32_t hkv_arrhythmia_test_cycle_counter_delta(uint32_t start, uint32_t end)
{
    if (hkv_arrhythmia_test_counter_kind == hkv_arrhythmia_test_counter_systick) {
#if defined(SysTick_LOAD_RELOAD_Msk)
        const uint32_t modulo = SysTick_LOAD_RELOAD_Msk + 1U;
        return (end >= start) ? (end - start) : (modulo - start + end);
#else
        return 0;
#endif
    }
    return (uint32_t)(end - start);
}


//── Inputs ────────────────────────────────────────────────────────────────────
static const float hkv_arrhythmia_test_stimulus_input_0[500] = {
    0.12854591012001038, 0.3571454584598541, 0.40039002895355225, 0.3019409775733948, 0.22058027982711792, 0.013869882561266422, -0.21081966161727905, -0.287259042263031, -0.36817172169685364, -0.33410319685935974, -0.38962608575820923, -0.6718393564224243, 1.1216533184051514, 4.793339729309082, 6.440215110778809, 2.2796783447265625, -1.2972867488861084, -1.2110896110534668, -0.44204989075660706, -0.4305500388145447,
    -0.45493441820144653, -0.49948590993881226, -0.49330127239227295, -0.4663046598434448, -0.4851503372192383, -0.4006718099117279, -0.396388441324234, -0.41314995288848877, -0.3648148775100708, -0.3087099492549896, -0.2933443784713745, -0.28524285554885864, -0.20018619298934937, -0.1059611365199089, 0.0011247307993471622, 0.1479761302471161, 0.3523176312446594, 0.5618956685066223, 0.7568086385726929, 0.9231699109077454,
    1.0302475690841675, 1.0184472799301147, 0.9282475113868713, 0.7369258403778076, 0.4877239465713501, 0.2660619616508484, 0.09981176257133484, -0.050238534808158875, -0.13565632700920105, -0.1664322316646576, -0.19589528441429138, -0.21685753762722015, -0.22776350378990173, -0.22206991910934448, -0.22226502001285553, -0.22177903354167938, -0.2187741994857788, -0.20901192724704742, -0.20367883145809174, -0.19792425632476807,
    -0.19955602288246155, -0.1996023952960968, -0.19220128655433655, -0.1912047415971756, -0.19558052718639374, -0.21125446259975433, -0.2301974892616272, -0.2359522432088852, -0.2351827323436737, -0.23373015224933624, -0.22802849113941193, -0.21919023990631104, -0.21150922775268555, -0.20570138096809387, -0.20133189857006073, -0.19926249980926514, -0.19823727011680603, -0.1944013237953186, -0.1835446059703827, -0.1718713790178299,
    -0.1739068627357483, -0.1768067479133606, -0.19026239216327667, -0.19740189611911774, -0.20771628618240356, -0.20359034836292267, -0.22195619344711304, -0.2163662165403366, -0.2021716982126236, -0.1416163593530655, -0.10231857001781464, -0.04157290980219841, 0.08660660684108734, 0.260543555021286, 0.41493862867355347, 0.33179908990859985, 0.19226594269275665, 0.13492850959300995, -0.10367754846811295, -0.3339061141014099,
    -0.33054792881011963, -0.3816795349121094, -0.44922104477882385, -0.7985389232635498, -0.25007057189941406, 3.3154385089874268, 6.562113285064697, 4.124953269958496, -0.06528034061193466, -1.2099025249481201, -0.5722596049308777, -0.6109237670898438, -0.530121386051178, -0.4890535771846771, -0.5673418641090393, -0.4996455907821655, -0.5521025061607361, -0.4685084819793701, -0.4402516186237335, -0.44021737575531006,
    -0.44580674171447754, -0.35188645124435425, -0.2986184358596802, -0.2642197906970978, -0.1764954775571823, -0.10056674480438232, 0.009764286689460278, 0.1116238683462143, 0.29024115204811096, 0.4943534731864929, 0.6656111478805542, 0.8708666563034058, 0.9921370148658752, 1.0405694246292114, 1.0479477643966675, 0.9038269519805908, 0.6888812184333801, 0.44973987340927124, 0.24160727858543396, 0.0761871412396431,
    -0.03889419510960579, -0.11001284420490265, -0.14566202461719513, -0.18881255388259888, -0.20728257298469543, -0.2106168121099472, -0.21140752732753754, -0.21976575255393982, -0.21792854368686676, -0.2045341432094574, -0.20188991725444794, -0.20217594504356384, -0.21098078787326813, -0.21729981899261475, -0.21109986305236816, -0.20041614770889282, -0.19137240946292877, -0.19064436852931976, -0.20708809792995453, -0.2222292572259903,
    -0.22424471378326416, -0.2312294840812683, -0.23957039415836334, -0.23821720480918884, -0.23251621425151825, -0.2238590568304062, -0.216119647026062, -0.21340174973011017, -0.2083473801612854, -0.20291642844676971, -0.1973104625940323, -0.19677242636680603, -0.1955929398536682, -0.19389095902442932, -0.19608397781848907, -0.2065369337797165, -0.21498310565948486, -0.22843267023563385, -0.23293869197368622, -0.23600225150585175,
    -0.23008863627910614, -0.21175356209278107, -0.2026492804288864, -0.1729617416858673, -0.12125453352928162, -0.1133023127913475, -0.018519015982747078, 0.126004159450531, 0.2872685492038727, 0.32990655303001404, 0.23193050920963287, 0.17290298640727997, 0.043336037546396255, -0.143239825963974, -0.24475571513175964, -0.2990332245826721, -0.216888889670372, -0.30902817845344543, -0.5925219655036926, 0.9097552299499512,
    4.405550003051758, 6.409106254577637, 2.6121697425842285, -1.2497056722640991, -1.2604738473892212, -0.4681103527545929, -0.5028584003448486, -0.5073810815811157, -0.557955265045166, -0.5554218888282776, -0.5467367172241211, -0.586809515953064, -0.4873825013637543, -0.46262216567993164, -0.47531819343566895, -0.4242910146713257, -0.3541746437549591, -0.33228471875190735, -0.2864772081375122, -0.168588787317276,
    -0.06726715713739395, 0.056525252759456635, 0.18729035556316376, 0.376924604177475, 0.561388373374939, 0.7403584122657776, 0.8873546123504639, 0.9963392019271851, 1.015889286994934, 0.9747892022132874, 0.835442841053009, 0.6063479781150818, 0.37547218799591064, 0.16914352774620056, 0.0072024003602564335, -0.10703972727060318, -0.1587633192539215, -0.1964402049779892, -0.21207229793071747, -0.21220822632312775,
    -0.21207650005817413, -0.2157449722290039, -0.2138359248638153, -0.20846278965473175, -0.1995178759098053, -0.2030387818813324, -0.20107755064964294, -0.2074085921049118, -0.2149362713098526, -0.2149818241596222, -0.20960207283496857, -0.20409415662288666, -0.20587921142578125, -0.21382956206798553, -0.21432803571224213, -0.21123754978179932, -0.2109900414943695, -0.20661002397537231, -0.19836492836475372, -0.1910950243473053,
    -0.18565337359905243, -0.18340332806110382, -0.18569321930408478, -0.18989582359790802, -0.19499802589416504, -0.19208469986915588, -0.18483468890190125, -0.18317031860351562, -0.17966066300868988, -0.19020910561084747, -0.18898101150989532, -0.1962178498506546, -0.18185734748840332, -0.19143283367156982, -0.18552379310131073, -0.17790265381336212, -0.12736064195632935, -0.08401178568601608, -0.05883225053548813, 0.04431581124663353,
    0.2433953434228897, 0.42901062965393066, 0.38208919763565063, 0.26060760021209717, 0.15548479557037354, -0.08616030216217041, -0.2519422471523285, -0.2508517801761627, -0.3373499810695648, -0.41592907905578613, -0.660634458065033, -0.23129089176654816, 2.88634991645813, 5.984354496002197, 4.005861282348633, -0.022925827652215958, -1.2330174446105957, -0.62140953540802, -0.6396611928939819, -0.5052346587181091,
    -0.4261539876461029, -0.5259202718734741, -0.4730987250804901, -0.5204449892044067, -0.457846075296402, -0.40881168842315674, -0.3802788555622101, -0.39756402373313904, -0.3380821943283081, -0.28005099296569824, -0.26216426491737366, -0.1821414977312088, -0.1061093807220459, -0.0021189816761761904, 0.07827837020158768, 0.25075075030326843, 0.42796963453292847, 0.5827365517616272, 0.7534181475639343, 0.8573009967803955,
    0.8953019380569458, 0.9109416007995605, 0.7791236042976379, 0.5639420747756958, 0.35222187638282776, 0.17542795836925507, 0.03157155588269234, -0.07594196498394012, -0.14721739292144775, -0.18394242227077484, -0.20551122725009918, -0.21218113601207733, -0.21163105964660645, -0.2111203819513321, -0.20945359766483307, -0.2057608813047409, -0.1982843279838562, -0.19854582846164703, -0.1955488920211792, -0.2014966607093811,
    -0.20477737486362457, -0.19787435233592987, -0.185588076710701, -0.1766345500946045, -0.1769009679555893, -0.19308625161647797, -0.20401985943317413, -0.205658420920372, -0.20656684041023254, -0.20549437403678894, -0.1991492360830307, -0.19263330101966858, -0.1881943792104721, -0.18723611533641815, -0.1916767805814743, -0.19106784462928772, -0.1834307760000229, -0.18106023967266083, -0.18120789527893066, -0.1835949569940567,
    -0.18911510705947876, -0.19230221211910248, -0.18827475607395172, -0.18045690655708313, -0.1895405650138855, -0.19440680742263794, -0.157436802983284, -0.1166442260146141, -0.1304621696472168, -0.017833353951573372, 0.15163731575012207, 0.3753660023212433, 0.43507805466651917, 0.3430159389972687, 0.22886575758457184, 0.02993829734623432, -0.16934792697429657, -0.2314606010913849, -0.33747413754463196, -0.33687764406204224,
    -0.4666491150856018, -0.7195951342582703, 1.2758196592330933, 4.730877876281738, 5.787224769592285, 1.8757643699645996, -1.0486384630203247, -0.8005741238594055, -0.42448240518569946, -0.3867042064666748, -0.40493738651275635, -0.47076261043548584, -0.47149914503097534, -0.4807794392108917, -0.4691232144832611, -0.36248692870140076, -0.35764405131340027, -0.362155944108963, -0.30282342433929443, -0.258932501077652,
    -0.257132351398468, -0.23630006611347198, -0.13542653620243073, -0.03704302757978439, 0.06338904798030853, 0.1973586082458496, 0.40254637598991394, 0.5908915400505066, 0.7886162400245667, 0.9437263011932373, 1.0281071662902832, 1.042517066001892, 0.9742066860198975, 0.7857451438903809, 0.5210428237915039, 0.27211979031562805, 0.07401298731565475, -0.0832064151763916, -0.19421988725662231, -0.24096588790416718,
    -0.27232474088668823, -0.283158540725708, -0.2812415063381195, -0.2799786329269409, -0.2813146710395813, -0.27937132120132446, -0.2757083773612976, -0.2701082229614258, -0.2721724808216095, -0.2684536278247833, -0.2689456045627594, -0.26700159907341003, -0.25993019342422485, -0.258731484413147, -0.2669406831264496, -0.28153717517852783, -0.292163223028183, -0.28954949975013733, -0.28359755873680115, -0.27725479006767273,
    -0.26885727047920227, -0.26024940609931946, -0.2563185691833496, -0.25720536708831787, -0.26193177700042725, -0.26816296577453613, -0.27161774039268494, -0.273537814617157, -0.2685936689376831, -0.25825783610343933, -0.25454986095428467, -0.2534101605415344, -0.25675690174102783, -0.2618418335914612, -0.26694825291633606, -0.26598235964775085, -0.25782328844070435, -0.26884350180625916, -0.27064621448516846, -0.23962287604808807,
    -0.20875805616378784, -0.22551824152469635, -0.1232200637459755, 0.037924621254205704, 0.2161979079246521, 0.27318960428237915, 0.18056993186473846, 0.08157119154930115, -0.022087950259447098, -0.208954319357872, -0.28980377316474915, -0.3631152808666229, -0.34507569670677185, -0.4372985363006592, -0.6622216105461121, 0.9783605933189392, 4.39950704574585, 5.955902099609375, 2.233036518096924, -1.0990818738937378,
    -1.0714675188064575, -0.45229625701904297, -0.41133636236190796, -0.4237058758735657, -0.49701473116874695, -0.48188450932502747, -0.47663310170173645, -0.48245683312416077, -0.3603839874267578, -0.3560648560523987, -0.36449527740478516, -0.33003681898117065, -0.2835270166397095, -0.2709609866142273, -0.24797344207763672, -0.1446150839328766, -0.04235063120722771, 0.07030285894870758, 0.1961006075143814, 0.39769911766052246
};

//── Outputs ───────────────────────────────────────────────────────────────────
static const float hkv_arrhythmia_test_stimulus_golden_0[4] = {
    0.84375, 0.09765625, 0.0078125, 0.05078125
};

//── Callback ──────────────────────────────────────────────────────────────────
static void hkv_arrhythmia_test_stimulus_callback(
    int32_t op,
    hkv_arrhythmia_operator_state_t state,
    int32_t status,
    void *user_data
) {
    (void)user_data;
    if (state == hkv_arrhythmia_op_state_init_finished) {
        HKV_ARRHYTHMIA_PRINTF("Operator %ld init finished with status %ld\n", (long)op, (long)status);
    }
    if (state == hkv_arrhythmia_op_state_run_finished) {
        HKV_ARRHYTHMIA_PRINTF("Operator %ld run finished with status %ld\n", (long)op, (long)status);
    }
}


//── Context ───────────────────────────────────────────────────────────────────
static hkv_arrhythmia_model_context_t hkv_arrhythmia_test_stimulus_context = {
    .callback = hkv_arrhythmia_test_stimulus_callback,
    .user_data = NULL
};


int32_t
hkv_arrhythmia_test_case_init(void)
{
    // Initialize model
    int32_t status = hkv_arrhythmia_model_init(
        &hkv_arrhythmia_test_stimulus_context
    );
    if (status != 0) {
        return status;
    }
    return 0;
}

int32_t
hkv_arrhythmia_test_case_run(void)
{
    int32_t result = 0;
    const int num_iterations = 1;
    const int have_cycle_counter = hkv_arrhythmia_test_cycle_counter_enable();
    void (*saved_callback)(int32_t, hkv_arrhythmia_operator_state_t, int32_t, void *) = hkv_arrhythmia_test_stimulus_context.callback;
    uint64_t model_run_cycles_total = 0;

    if (have_cycle_counter) {
        hkv_arrhythmia_test_stimulus_context.callback = NULL;
    }

    // Run the model N times on the same stimulus
    for (int iter = 0; iter < num_iterations; iter++) {
        uint32_t cycle_start = 0;
        uint32_t cycle_end = 0;

        // Copy input tensors to context (before each iteration to ensure input persists)
    arm_memcpy_s8(
        hkv_arrhythmia_test_stimulus_context.inputs[0].data,
        (int8_t *)hkv_arrhythmia_test_stimulus_input_0,
        2000
    );

        if (have_cycle_counter) {
            cycle_start = hkv_arrhythmia_test_cycle_counter_read();
        }
        result = hkv_arrhythmia_model_run(&hkv_arrhythmia_test_stimulus_context);
        if (have_cycle_counter) {
            cycle_end = hkv_arrhythmia_test_cycle_counter_read();
            model_run_cycles_total += hkv_arrhythmia_test_cycle_counter_delta(cycle_start, cycle_end);
        }
        if (result != 0) {
            HKV_ARRHYTHMIA_PRINTF("Model run failed with status %ld (iteration %d)\n", (long)result, iter);
            hkv_arrhythmia_test_stimulus_context.callback = saved_callback;
            return result;
        }
    }

    if (have_cycle_counter) {
        const uint64_t cycles_per_iter = (num_iterations > 0)
            ? (model_run_cycles_total / (uint64_t)num_iterations)
            : 0;
        HKV_ARRHYTHMIA_PRINTF(
            "HELIA_E2E_METRIC counter=%s model_run_cycles_total=%llu model_run_cycles_per_iter=%llu iterations=%d\n",
            hkv_arrhythmia_test_counter_kind == hkv_arrhythmia_test_counter_pmu ? "pmu" :
            (hkv_arrhythmia_test_counter_kind == hkv_arrhythmia_test_counter_dwt ? "dwt" : "systick"),
            (unsigned long long)model_run_cycles_total,
            (unsigned long long)cycles_per_iter,
            num_iterations
        );
    } else {
        HKV_ARRHYTHMIA_PRINTF("HELIA_E2E_METRIC model_run_cycles_unavailable=1 iterations=%d\n", num_iterations);
    }

    hkv_arrhythmia_test_stimulus_context.callback = saved_callback;

    // Verify outputs once after all iterations
    float *act_0 = (float *)hkv_arrhythmia_test_stimulus_context.outputs[0].data;
    float *exp_0 = (float *)hkv_arrhythmia_test_stimulus_golden_0;
    for (int i = 0; i < 4; i++) {
        float act = (float)act_0[i];
        float exp = (float)exp_0[i];
        // Finite-aware oracle: a NaN ``diff`` makes ``diff > tol`` false, so a
        // plain magnitude check would silently accept NaN/unexpected-Inf
        // actuals against a finite expected value. Compare by expected class.
        int mismatch;
        if (isnan(exp)) {
            mismatch = !isnan(act);
        } else if (isinf(exp)) {
            mismatch = !(isinf(act) && ((act > 0.0f) == (exp > 0.0f)));
        } else {
            // Finite expected: any NaN/Inf actual fails; ``!(<=)`` also catches
            // the NaN ``diff`` case where ``>`` would wrongly pass.
            mismatch = !(fabsf(act - exp) <= (float)0.008);
        }
        if (mismatch) {
            HKV_ARRHYTHMIA_PRINTF("Output mismatch at index [%d][%d]: expected %f, got %f\n", 0, i, exp, act);
            result = 1;
        }
    }

    // Check for errors
    if (result == 0) {
        HKV_ARRHYTHMIA_PRINTF("Test passed!\n");
    } else {
        HKV_ARRHYTHMIA_PRINTF("Test failed!\n");
    }
    return result;

}