/******************************************************************************
 * @file        hkv_arrhythmia_max_pool_2d_39.c
 * @brief       Autogenerated AOT max_pool_2d kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '39' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_max_pool_2d_39.h"

// Input dimensions: input shape is [N, H_IN, W_IN, C_IN].
static const cmsis_nn_dims max_pool_2d_39_input_dims = {
    .n = 1, .h = 1,
    .w = 16, .c = 64
};

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, 1].
static const cmsis_nn_dims max_pool_2d_39_filter_dims = {
    .n = 1, .h = 1,
    .w = 2, .c = 1
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT]. C_OUT = C_IN
static const cmsis_nn_dims max_pool_2d_39_output_dims = {
    .n = 1, .h = 1,
    .w = 8, .c = 64
};

// NOTE: No scratch buffer needed for max pooling at this time
static cmsis_nn_context max_pool_2d_39_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_pool_params max_pool_2d_39_params = {
    .stride.w = 2,
    .stride.h = 1,
    .padding.w = 0,
    .padding.h = 0,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
hkv_arrhythmia_max_pool_2d_39_init(
    hkv_arrhythmia_model_context_t *ctx
) {
    return 0;
}


int32_t
hkv_arrhythmia_max_pool_2d_39_run(
    hkv_arrhythmia_model_context_t *ctx
){
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_89];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_90];

    return arm_max_pool_s8(
        &max_pool_2d_39_ctx,
        &max_pool_2d_39_params,
        &max_pool_2d_39_input_dims,
        input,
        &max_pool_2d_39_filter_dims,
        &max_pool_2d_39_output_dims,
        output
    );

}