/******************************************************************************
 * @file        hkv_arrhythmia_depthwise_conv_2d_38.c
 * @brief       Autogenerated AOT depthwise_conv_2d kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '38' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_depthwise_conv_2d_38.h"

// Input dimensions: input shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims depthwise_conv_2d_38_input_dims = {
    .n = 1, .h = 1,
    .w = 16, .c = 64
};

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_38_filter_dims = {
    .n = 1, .h = 1,
    .w = 9, .c = 64
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_38_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 64
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_38_output_dims = {
    .n = 1, .h = 1,
    .w = 16, .c = 64
};

// Quantization parameters (per-channel quantization)

static const int32_t depthwise_conv_2d_38_input_zero_point = -5;
static const int32_t depthwise_conv_2d_38_output_zero_point = -128;

// Scratch buffer context
static cmsis_nn_context depthwise_conv_2d_38_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context depthwise_conv_2d_38_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};


const cmsis_nn_dw_conv_params depthwise_conv_2d_38_params = {
    .input_offset = -depthwise_conv_2d_38_input_zero_point,
    .output_offset = depthwise_conv_2d_38_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 4,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
hkv_arrhythmia_depthwise_conv_2d_38_init(
    hkv_arrhythmia_model_context_t *ctx
) {

    depthwise_conv_2d_38_ctx.buf = ctx->tensor_ptrs[hkv_arrhythmia_tensor_depthwise_conv_2d_38_scratch];
    depthwise_conv_2d_38_ctx.size = 4464;

    depthwise_conv_2d_38_weight_sum_ctx.buf = ctx->tensor_ptrs[hkv_arrhythmia_tensor_depthwise_conv_2d_38_weight_sum];
    depthwise_conv_2d_38_weight_sum_ctx.size = 256;

    // Kernel sums precomputed offline.
    return ARM_CMSIS_NN_SUCCESS;
}


int32_t
hkv_arrhythmia_depthwise_conv_2d_38_run(
    hkv_arrhythmia_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_88];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_arrhythmia_tensor_89];

    // Per-channel quantization tables resolved from interned constant tensors.
    const cmsis_nn_per_channel_quant_params depthwise_conv_2d_38_quant_params = {
        .multiplier = (int32_t *)ctx->tensor_ptrs[hkv_arrhythmia_tensor_depthwise_conv_2d_38_multiplier],
        .shift = (int32_t *)ctx->tensor_ptrs[hkv_arrhythmia_tensor_depthwise_conv_2d_38_shift],
    };


    return arm_depthwise_conv_s8_opt(
        &depthwise_conv_2d_38_ctx,
        &depthwise_conv_2d_38_weight_sum_ctx,
        &depthwise_conv_2d_38_params,
        &depthwise_conv_2d_38_quant_params,
        &depthwise_conv_2d_38_input_dims,
        input,
        &depthwise_conv_2d_38_filter_dims,
        (int8_t *)ctx->tensor_ptrs[hkv_arrhythmia_tensor_15],
        &depthwise_conv_2d_38_bias_dims,
        NULL,
        &depthwise_conv_2d_38_output_dims,
        output
    );

}