/******************************************************************************
 * @file        hkv_arrhythmia_test_case.c
 * @brief       Autogenerated heliaAOT test case
 * @details     This file is used to verify the correctness of the module.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdlib.h>

#include "hkv_arrhythmia_common.h"
#include "hkv_arrhythmia_model.h"
#include "hkv_arrhythmia_test_case.h"


//── Optional cycle counter probe ──────────────────────────────────────────────
// The E2E Corstone builds pre-include the CMSIS device header (ARMCM55.h /
// ARMCM4_FP.h), so DWT and the debug control block are visible here when the
// target exposes a cycle counter. We time only model_run() inside the
// iteration loop so the metric stays focused on dispatch + kernel execution
// rather than init or output verification.
//
// CMSIS 6 deprecates the CMSIS 5 ``CoreDebug`` spelling in favour of ``DCB``:
// 6.0.0 omitted it, while 6.1.0+ retains it as a deprecated alias. Prefer
// ``DCB`` and fall back to ``CoreDebug`` for compatible CMSIS layouts.
#if defined(DCB) && defined(DCB_DEMCR_TRCENA_Msk)
#define HKV_ARRHYTHMIA_TEST_DEMCR       (DCB->DEMCR)
#define HKV_ARRHYTHMIA_TEST_DEMCR_TRCENA DCB_DEMCR_TRCENA_Msk
#elif defined(CoreDebug) && defined(CoreDebug_DEMCR_TRCENA_Msk)
#define HKV_ARRHYTHMIA_TEST_DEMCR       (CoreDebug->DEMCR)
#define HKV_ARRHYTHMIA_TEST_DEMCR_TRCENA CoreDebug_DEMCR_TRCENA_Msk
#endif

typedef enum {
    hkv_arrhythmia_test_counter_unavailable = 0,
    hkv_arrhythmia_test_counter_pmu,
    hkv_arrhythmia_test_counter_dwt,
    hkv_arrhythmia_test_counter_systick,
} hkv_arrhythmia_test_counter_kind_t;

static hkv_arrhythmia_test_counter_kind_t hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_unavailable;

static void hkv_arrhythmia_test_cycle_counter_probe_spin(void)
{
    for (volatile uint32_t i = 0; i < 64U; ++i) {
#if defined(__NOP)
        __NOP();
#endif
    }
}

static int hkv_arrhythmia_test_cycle_counter_enable(void)
{
#if defined(__PMU_PRESENT) && (__PMU_PRESENT == 1U)
    uint32_t pmu_start = 0;
    uint32_t pmu_end = 0;
    ARM_PMU_Disable();
    ARM_PMU_CYCCNT_Reset();
    ARM_PMU_Enable();
    ARM_PMU_CNTR_Enable(PMU_CNTENSET_CCNTR_ENABLE_Msk);
    pmu_start = ARM_PMU_Get_CCNTR();
    hkv_arrhythmia_test_cycle_counter_probe_spin();
    pmu_end = ARM_PMU_Get_CCNTR();
    if (((PMU->CNTENSET & PMU_CNTENSET_CCNTR_ENABLE_Msk) != 0U) && (pmu_end != pmu_start)) {
        hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_pmu;
        return 1;
    }
#elif defined(DWT) && defined(DWT_CTRL_CYCCNTENA_Msk) && defined(HKV_ARRHYTHMIA_TEST_DEMCR)
    uint32_t dwt_start = 0;
    uint32_t dwt_end = 0;
    HKV_ARRHYTHMIA_TEST_DEMCR |= HKV_ARRHYTHMIA_TEST_DEMCR_TRCENA;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
    dwt_start = DWT->CYCCNT;
    hkv_arrhythmia_test_cycle_counter_probe_spin();
    dwt_end = DWT->CYCCNT;
    if (((DWT->CTRL & DWT_CTRL_CYCCNTENA_Msk) != 0U) && (dwt_end != dwt_start)) {
        hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_dwt;
        return 1;
    }
#endif

#if defined(SysTick) && defined(SysTick_LOAD_RELOAD_Msk) && defined(SysTick_CTRL_ENABLE_Msk) && defined(SysTick_CTRL_CLKSOURCE_Msk)
    uint32_t systick_start = 0;
    uint32_t systick_end = 0;
    SysTick->CTRL = 0;
    SysTick->LOAD = SysTick_LOAD_RELOAD_Msk;
    SysTick->VAL = 0;
    SysTick->CTRL = SysTick_CTRL_ENABLE_Msk | SysTick_CTRL_CLKSOURCE_Msk;
    systick_start = SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
    hkv_arrhythmia_test_cycle_counter_probe_spin();
    systick_end = SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
    if (systick_end != systick_start) {
        hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_systick;
        return 1;
    }
#endif

    hkv_arrhythmia_test_counter_kind = hkv_arrhythmia_test_counter_unavailable;
    return 0;
}

static uint32_t hkv_arrhythmia_test_cycle_counter_read(void)
{
    switch (hkv_arrhythmia_test_counter_kind) {
        case hkv_arrhythmia_test_counter_pmu:
#if defined(__PMU_PRESENT) && (__PMU_PRESENT == 1U)
            return ARM_PMU_Get_CCNTR();
#else
            return 0;
#endif
        case hkv_arrhythmia_test_counter_dwt:
#if defined(DWT) && defined(DWT_CTRL_CYCCNTENA_Msk)
            return DWT->CYCCNT;
#else
            return 0;
#endif
        case hkv_arrhythmia_test_counter_systick:
#if defined(SysTick) && defined(SysTick_LOAD_RELOAD_Msk)
            return SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
#else
            return 0;
#endif
        default:
            return 0;
    }
}

static uint32_t hkv_arrhythmia_test_cycle_counter_delta(uint32_t start, uint32_t end)
{
    if (hkv_arrhythmia_test_counter_kind == hkv_arrhythmia_test_counter_systick) {
#if defined(SysTick_LOAD_RELOAD_Msk)
        const uint32_t modulo = SysTick_LOAD_RELOAD_Msk + 1U;
        return (end >= start) ? (end - start) : (modulo - start + end);
#else
        return 0;
#endif
    }
    return (uint32_t)(end - start);
}


//── Inputs ────────────────────────────────────────────────────────────────────
static const float hkv_arrhythmia_test_stimulus_input_0[500] = {
    0.12854614853858948, 0.3571458160877228, 0.40039047598838806, 0.3019413948059082, 0.22058077156543732, 0.013870218768715858, -0.2108193188905716, -0.2872590124607086, -0.3681715130805969, -0.3341028094291687, -0.38962551951408386, -0.6718385815620422, 1.1216545104980469, 4.793339729309082, 6.440216064453125, 2.2796790599823, -1.2972872257232666, -1.211090326309204, -0.4420510232448578, -0.43055129051208496,
    -0.45493507385253906, -0.4994863271713257, -0.4933014512062073, -0.46630507707595825, -0.4851508140563965, -0.4006724953651428, -0.39638903737068176, -0.41315051913261414, -0.3648154139518738, -0.308710515499115, -0.29334479570388794, -0.2852431535720825, -0.20018652081489563, -0.10596143454313278, 0.0011244211345911026, 0.1479758322238922, 0.35231733322143555, 0.561895489692688, 0.7568082213401794, 0.9231692552566528,
    1.0302470922470093, 1.018446683883667, 0.9282468557357788, 0.7369252443313599, 0.4877234101295471, 0.2660615146160126, 0.09981166571378708, -0.05023852735757828, -0.13565607368946075, -0.1664319783449173, -0.1958950012922287, -0.21685734391212463, -0.22776320576667786, -0.2220696657896042, -0.22226475179195404, -0.22177883982658386, -0.21877402067184448, -0.20901183784008026, -0.20367859303951263, -0.197923943400383,
    -0.19955570995807648, -0.1996021717786789, -0.19220104813575745, -0.19120456278324127, -0.19558024406433105, -0.21125423908233643, -0.23019717633724213, -0.2359519600868225, -0.23518244922161102, -0.23372991383075714, -0.22802816331386566, -0.21918998658657074, -0.21150892972946167, -0.20570112764835358, -0.20133158564567566, -0.19926215708255768, -0.19823689758777618, -0.19440101087093353, -0.18354418873786926, -0.1718711107969284,
    -0.17390653491020203, -0.17680640518665314, -0.1902620494365692, -0.19740161299705505, -0.20771591365337372, -0.20359008014202118, -0.22195594012737274, -0.2163659781217575, -0.2021714597940445, -0.1416161209344864, -0.10231821984052658, -0.04157261550426483, 0.08660698682069778, 0.2605438530445099, 0.4149390459060669, 0.33179962635040283, 0.19226618111133575, 0.13492894172668457, -0.10367731750011444, -0.33390578627586365,
    -0.33054763078689575, -0.3816792666912079, -0.44922053813934326, -0.7985382080078125, -0.25007006525993347, 3.315439224243164, 6.562115669250488, 4.124953269958496, -0.06528057157993317, -1.2099039554595947, -0.5722599625587463, -0.6109241843223572, -0.5301216840744019, -0.4890541434288025, -0.5673424005508423, -0.4996460974216461, -0.5521029233932495, -0.4685087502002716, -0.4402520954608917, -0.44021761417388916,
    -0.4458070397377014, -0.3518867790699005, -0.29861876368522644, -0.26422005891799927, -0.17649585008621216, -0.10056711733341217, 0.009763916954398155, 0.11162353307008743, 0.29024097323417664, 0.49435311555862427, 0.6656107306480408, 0.870866060256958, 0.9921364784240723, 1.0405685901641846, 1.0479466915130615, 0.9038258194923401, 0.688880205154419, 0.4497392177581787, 0.24160709977149963, 0.07618708163499832,
    -0.03889412060379982, -0.1100127100944519, -0.1456618458032608, -0.18881231546401978, -0.20728236436843872, -0.21061661839485168, -0.2114073485136032, -0.21976549923419952, -0.21792826056480408, -0.2045339047908783, -0.2018897384405136, -0.20217564702033997, -0.21098053455352783, -0.21729959547519684, -0.2110995501279831, -0.20041589438915253, -0.1913720816373825, -0.19064413011074066, -0.20708788931369781, -0.22222904860973358,
    -0.22424444556236267, -0.23122923076152802, -0.23957008123397827, -0.23821696639060974, -0.23251596093177795, -0.22385871410369873, -0.2161194086074829, -0.2134014368057251, -0.2083471417427063, -0.20291614532470703, -0.1973101645708084, -0.19677206873893738, -0.19559252262115479, -0.19389064610004425, -0.196083664894104, -0.20653659105300903, -0.21498273313045502, -0.2284322828054428, -0.23293833434581757, -0.2360018640756607,
    -0.2300882339477539, -0.21175360679626465, -0.20264932513237, -0.1729617714881897, -0.1212545707821846, -0.11330227553844452, -0.01851891539990902, 0.1260042041540146, 0.2872685492038727, 0.32990652322769165, 0.23193040490150452, 0.1729028820991516, 0.04333578795194626, -0.14323976635932922, -0.24475564062595367, -0.2990332841873169, -0.21688884496688843, -0.30902841687202454, -0.5925218462944031, 0.9097552299499512,
    4.405550479888916, 6.409107685089111, 2.612171173095703, -1.2497048377990723, -1.2604724168777466, -0.46810999512672424, -0.5028578042984009, -0.5073809623718262, -0.5579549670219421, -0.5554215312004089, -0.5467362999916077, -0.5868092179298401, -0.48738232254981995, -0.4626219868659973, -0.4753180146217346, -0.4242909848690033, -0.3541744351387024, -0.332284539937973, -0.2864771783351898, -0.1685888022184372,
    -0.06726715713739395, 0.05652526021003723, 0.18729045987129211, 0.37692469358444214, 0.5613884925842285, 0.7403584122657776, 0.88735431432724, 0.996338963508606, 1.015889048576355, 0.9747889041900635, 0.8354424834251404, 0.6063474416732788, 0.37547171115875244, 0.16914331912994385, 0.007202247157692909, -0.10703984647989273, -0.15876337885856628, -0.1964401751756668, -0.21207238733768463, -0.21220828592777252,
    -0.21207652986049652, -0.2157450020313263, -0.21383599936962128, -0.20846284925937653, -0.1995178908109665, -0.20303882658481598, -0.20107756555080414, -0.20740869641304016, -0.21493640542030334, -0.21498188376426697, -0.20960208773612976, -0.20409424602985382, -0.20587928593158722, -0.2138296365737915, -0.21432816982269287, -0.21123763918876648, -0.21099017560482025, -0.20661011338233948, -0.1983649879693985, -0.1910950094461441,
    -0.1856534332036972, -0.18340343236923218, -0.18569327890872955, -0.18989594280719757, -0.194998100399971, -0.19208480417728424, -0.1848347783088684, -0.1831703633069992, -0.17966075241565704, -0.19020918011665344, -0.1889810860157013, -0.19621789455413818, -0.1818573921918869, -0.1914328932762146, -0.1855238378047943, -0.1779027134180069, -0.12736062705516815, -0.08401186764240265, -0.058832332491874695, 0.04431591182947159,
    0.2433953583240509, 0.4290107786655426, 0.3820892870426178, 0.2606077492237091, 0.15548473596572876, -0.08616042137145996, -0.2519422173500061, -0.2508517801761627, -0.3373500406742096, -0.41592878103256226, -0.6606345772743225, -0.23129138350486755, 2.88634991645813, 5.984354496002197, 4.005861759185791, -0.022926032543182373, -1.2330173254013062, -0.6214091181755066, -0.639660656452179, -0.5052347779273987,
    -0.42615389823913574, -0.5259199142456055, -0.4730982482433319, -0.5204447507858276, -0.4578459560871124, -0.4088115394115448, -0.3802787661552429, -0.3975640535354614, -0.33808210492134094, -0.2800508439540863, -0.26216408610343933, -0.18214140832424164, -0.10610932111740112, -0.0021189674735069275, 0.07827840745449066, 0.25075072050094604, 0.4279696047306061, 0.5827363133430481, 0.7534180283546448, 0.8573005199432373,
    0.8953015804290771, 0.9109408855438232, 0.7791231274604797, 0.5639415979385376, 0.35222128033638, 0.17542745172977448, 0.03157123923301697, -0.07594228535890579, -0.14721760153770447, -0.1839425265789032, -0.20551124215126038, -0.2121812254190445, -0.21163107454776764, -0.2111203819513321, -0.20945365726947784, -0.2057609260082245, -0.1982843428850174, -0.19854585826396942, -0.195548877120018, -0.2014966756105423,
    -0.204777330160141, -0.1978743076324463, -0.18558809161186218, -0.17663462460041046, -0.17690102756023407, -0.19308634102344513, -0.20401988923549652, -0.2056584358215332, -0.2065669149160385, -0.20549432933330536, -0.1991492509841919, -0.19263333082199097, -0.18819443881511688, -0.18723618984222412, -0.19167685508728027, -0.19106794893741608, -0.18343085050582886, -0.18106035888195038, -0.18120789527893066, -0.1835949867963791,
    -0.18911513686180115, -0.1923021525144577, -0.1882748007774353, -0.1804569512605667, -0.18954063951969147, -0.19440686702728271, -0.15743684768676758, -0.1166442260146141, -0.13046202063560486, -0.01783321052789688, 0.15163753926753998, 0.3753662109375, 0.43507814407348633, 0.3430157005786896, 0.2288653552532196, 0.0299381036311388, -0.16934806108474731, -0.23146061599254608, -0.3374740779399872, -0.3368774950504303,
    -0.4666495621204376, -0.719596266746521, 1.275819182395935, 4.7308783531188965, 5.787225246429443, 1.8757652044296265, -1.0486366748809814, -0.8005750179290771, -0.4244835078716278, -0.3867048919200897, -0.4049379825592041, -0.4707632064819336, -0.4714997112751007, -0.4807800054550171, -0.4691237509250641, -0.3624873161315918, -0.35764437913894653, -0.3621561825275421, -0.3028236925601959, -0.2589327394962311,
    -0.2571326494216919, -0.2363003045320511, -0.13542670011520386, -0.03704318404197693, 0.06338881701231003, 0.1973584145307541, 0.40254613757133484, 0.5908911824226379, 0.788615882396698, 0.9437259435653687, 1.028106451034546, 1.0425169467926025, 0.9742065072059631, 0.7857450842857361, 0.5210428237915039, 0.2721199691295624, 0.07401309162378311, -0.08320620656013489, -0.1942196786403656, -0.24096569418907166,
    -0.2723245918750763, -0.2831583023071289, -0.2812412977218628, -0.279978483915329, -0.28131452202796936, -0.27937108278274536, -0.2757081687450409, -0.27010804414749146, -0.2721722424030304, -0.26845329999923706, -0.2689453363418579, -0.26700136065483093, -0.2599300146102905, -0.25873133540153503, -0.26694050431251526, -0.2815369963645935, -0.2921629548072815, -0.289549320936203, -0.2835974097251892, -0.277254581451416,
    -0.26885706186294556, -0.26024922728538513, -0.25631842017173767, -0.25720518827438354, -0.26193156838417053, -0.26816269755363464, -0.2716175615787506, -0.27353760600090027, -0.268593430519104, -0.25825759768486023, -0.25454971194267273, -0.25340989232063293, -0.25675666332244873, -0.26184162497520447, -0.26694804430007935, -0.2659820318222046, -0.25782299041748047, -0.26884329319000244, -0.27064600586891174, -0.23962260782718658,
    -0.20875775814056396, -0.2255181074142456, -0.12321995943784714, 0.03792472183704376, 0.2161981612443924, 0.2731899619102478, 0.18057021498680115, 0.08157158643007278, -0.022087667137384415, -0.20895405113697052, -0.28980347514152527, -0.3631151616573334, -0.3450752794742584, -0.437298059463501, -0.6622216701507568, 0.978360652923584, 4.399505615234375, 5.955903053283691, 2.2330362796783447, -1.0990816354751587,
    -1.0714679956436157, -0.45229753851890564, -0.4113371968269348, -0.42370688915252686, -0.4970153868198395, -0.4818848669528961, -0.4766336679458618, -0.4824574589729309, -0.3603845238685608, -0.3560652732849121, -0.36449557542800903, -0.33003735542297363, -0.28352734446525574, -0.27096137404441833, -0.24797378480434418, -0.14461539685726166, -0.04235087335109711, 0.07030263543128967, 0.19610045850276947, 0.3976990878582001
};

//── Outputs ───────────────────────────────────────────────────────────────────
static const float hkv_arrhythmia_test_stimulus_golden_0[4] = {
    0.8515625, 0.09375, 0.0078125, 0.046875
};

//── Callback ──────────────────────────────────────────────────────────────────
static void hkv_arrhythmia_test_stimulus_callback(
    int32_t op,
    hkv_arrhythmia_operator_state_t state,
    int32_t status,
    void *user_data
) {
    (void)user_data;
    if (state == hkv_arrhythmia_op_state_init_finished) {
        HKV_ARRHYTHMIA_PRINTF("Operator %ld init finished with status %ld\n", (long)op, (long)status);
    }
    if (state == hkv_arrhythmia_op_state_run_finished) {
        HKV_ARRHYTHMIA_PRINTF("Operator %ld run finished with status %ld\n", (long)op, (long)status);
    }
}


//── Context ───────────────────────────────────────────────────────────────────
static hkv_arrhythmia_model_context_t hkv_arrhythmia_test_stimulus_context = {
    .callback = hkv_arrhythmia_test_stimulus_callback,
    .user_data = NULL
};


int32_t
hkv_arrhythmia_test_case_init(void)
{
    // Initialize model
    int32_t status = hkv_arrhythmia_model_init(
        &hkv_arrhythmia_test_stimulus_context
    );
    if (status != 0) {
        return status;
    }
    return 0;
}

int32_t
hkv_arrhythmia_test_case_run(void)
{
    int32_t result = 0;
    const int num_iterations = 1;
    const int have_cycle_counter = hkv_arrhythmia_test_cycle_counter_enable();
    void (*saved_callback)(int32_t, hkv_arrhythmia_operator_state_t, int32_t, void *) = hkv_arrhythmia_test_stimulus_context.callback;
    uint64_t model_run_cycles_total = 0;

    if (have_cycle_counter) {
        hkv_arrhythmia_test_stimulus_context.callback = NULL;
    }

    // Run the model N times on the same stimulus
    for (int iter = 0; iter < num_iterations; iter++) {
        uint32_t cycle_start = 0;
        uint32_t cycle_end = 0;

        // Copy input tensors to context (before each iteration to ensure input persists)
    arm_memcpy_s8(
        hkv_arrhythmia_test_stimulus_context.inputs[0].data,
        (int8_t *)hkv_arrhythmia_test_stimulus_input_0,
        2000
    );

        if (have_cycle_counter) {
            cycle_start = hkv_arrhythmia_test_cycle_counter_read();
        }
        result = hkv_arrhythmia_model_run(&hkv_arrhythmia_test_stimulus_context);
        if (have_cycle_counter) {
            cycle_end = hkv_arrhythmia_test_cycle_counter_read();
            model_run_cycles_total += hkv_arrhythmia_test_cycle_counter_delta(cycle_start, cycle_end);
        }
        if (result != 0) {
            HKV_ARRHYTHMIA_PRINTF("Model run failed with status %ld (iteration %d)\n", (long)result, iter);
            hkv_arrhythmia_test_stimulus_context.callback = saved_callback;
            return result;
        }
    }

    if (have_cycle_counter) {
        const uint64_t cycles_per_iter = (num_iterations > 0)
            ? (model_run_cycles_total / (uint64_t)num_iterations)
            : 0;
        HKV_ARRHYTHMIA_PRINTF(
            "HELIA_E2E_METRIC counter=%s model_run_cycles_total=%llu model_run_cycles_per_iter=%llu iterations=%d\n",
            hkv_arrhythmia_test_counter_kind == hkv_arrhythmia_test_counter_pmu ? "pmu" :
            (hkv_arrhythmia_test_counter_kind == hkv_arrhythmia_test_counter_dwt ? "dwt" : "systick"),
            (unsigned long long)model_run_cycles_total,
            (unsigned long long)cycles_per_iter,
            num_iterations
        );
    } else {
        HKV_ARRHYTHMIA_PRINTF("HELIA_E2E_METRIC model_run_cycles_unavailable=1 iterations=%d\n", num_iterations);
    }

    hkv_arrhythmia_test_stimulus_context.callback = saved_callback;

    // Verify outputs once after all iterations
    float *act_0 = (float *)hkv_arrhythmia_test_stimulus_context.outputs[0].data;
    float *exp_0 = (float *)hkv_arrhythmia_test_stimulus_golden_0;
    for (int i = 0; i < 4; i++) {
        float act = (float)act_0[i];
        float exp = (float)exp_0[i];
        // Finite-aware oracle: a NaN ``diff`` makes ``diff > tol`` false, so a
        // plain magnitude check would silently accept NaN/unexpected-Inf
        // actuals against a finite expected value. Compare by expected class.
        int mismatch;
        if (isnan(exp)) {
            mismatch = !isnan(act);
        } else if (isinf(exp)) {
            mismatch = !(isinf(act) && ((act > 0.0f) == (exp > 0.0f)));
        } else {
            // Finite expected: any NaN/Inf actual fails; ``!(<=)`` also catches
            // the NaN ``diff`` case where ``>`` would wrongly pass.
            mismatch = !(fabsf(act - exp) <= (float)0.008);
        }
        if (mismatch) {
            HKV_ARRHYTHMIA_PRINTF("Output mismatch at index [%d][%d]: expected %f, got %f\n", 0, i, exp, act);
            result = 1;
        }
    }

    // Check for errors
    if (result == 0) {
        HKV_ARRHYTHMIA_PRINTF("Test passed!\n");
    } else {
        HKV_ARRHYTHMIA_PRINTF("Test failed!\n");
    }
    return result;

}