/******************************************************************************
 * @file        hkv_arrhythmia_operators.h
 * @brief       heliaAOT operators API
 * @details     Helper to pull in all operator headers
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include "hkv_arrhythmia_quantize_0.h"
#include "hkv_arrhythmia_shape_1.h"
#include "hkv_arrhythmia_strided_slice_2.h"
#include "hkv_arrhythmia_pack_3.h"
#include "hkv_arrhythmia_reshape_4.h"
#include "hkv_arrhythmia_conv_2d_5.h"
#include "hkv_arrhythmia_depthwise_conv_2d_6.h"
#include "hkv_arrhythmia_max_pool_2d_7.h"
#include "hkv_arrhythmia_mean_8.h"
#include "hkv_arrhythmia_conv_2d_9.h"
#include "hkv_arrhythmia_conv_2d_10.h"
#include "hkv_arrhythmia_mul_11.h"
#include "hkv_arrhythmia_mul_12.h"
#include "hkv_arrhythmia_conv_2d_13.h"
#include "hkv_arrhythmia_depthwise_conv_2d_14.h"
#include "hkv_arrhythmia_max_pool_2d_15.h"
#include "hkv_arrhythmia_mean_16.h"
#include "hkv_arrhythmia_conv_2d_17.h"
#include "hkv_arrhythmia_conv_2d_18.h"
#include "hkv_arrhythmia_mul_19.h"
#include "hkv_arrhythmia_mul_20.h"
#include "hkv_arrhythmia_conv_2d_21.h"
#include "hkv_arrhythmia_depthwise_conv_2d_22.h"
#include "hkv_arrhythmia_max_pool_2d_23.h"
#include "hkv_arrhythmia_mean_24.h"
#include "hkv_arrhythmia_conv_2d_25.h"
#include "hkv_arrhythmia_conv_2d_26.h"
#include "hkv_arrhythmia_mul_27.h"
#include "hkv_arrhythmia_mul_28.h"
#include "hkv_arrhythmia_conv_2d_29.h"
#include "hkv_arrhythmia_depthwise_conv_2d_30.h"
#include "hkv_arrhythmia_max_pool_2d_31.h"
#include "hkv_arrhythmia_mean_32.h"
#include "hkv_arrhythmia_conv_2d_33.h"
#include "hkv_arrhythmia_conv_2d_34.h"
#include "hkv_arrhythmia_mul_35.h"
#include "hkv_arrhythmia_mul_36.h"
#include "hkv_arrhythmia_conv_2d_37.h"
#include "hkv_arrhythmia_depthwise_conv_2d_38.h"
#include "hkv_arrhythmia_max_pool_2d_39.h"
#include "hkv_arrhythmia_mean_40.h"
#include "hkv_arrhythmia_conv_2d_41.h"
#include "hkv_arrhythmia_conv_2d_42.h"
#include "hkv_arrhythmia_mul_43.h"
#include "hkv_arrhythmia_mul_44.h"
#include "hkv_arrhythmia_conv_2d_45.h"
#include "hkv_arrhythmia_mean_46.h"
#include "hkv_arrhythmia_fully_connected_47.h"
#include "hkv_arrhythmia_softmax_48.h"
#include "hkv_arrhythmia_dequantize_49.h"
