/******************************************************************************
 * @file        hkv_arrhythmia_context.h
 * @brief       heliaAOT model context API
 * @details     Defines and initializes the model context:
 *              - Assigns arena buffers & sizes
 *              - Registers callback & user_data
 *              - Populates tensor pointer arrays
 *              - Performs context-level validation
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include "hkv_arrhythmia_common.h"

#ifdef __cplusplus
extern "C" {
#endif

//── Operator callback API ─────────────────────────────────────────────────────

// Operator states passed to the callback
typedef enum {
    hkv_arrhythmia_op_state_init_started = 0,
    hkv_arrhythmia_op_state_init_finished,
    hkv_arrhythmia_op_state_run_started,
    hkv_arrhythmia_op_state_run_finished,
} hkv_arrhythmia_operator_state_t;

// Signature for the operator callback
typedef void (*hkv_arrhythmia_operator_callback)(
    int32_t op, // Operator identifier
    hkv_arrhythmia_operator_state_t state, // Operator state
    int32_t status, // Operator return code
    void *user_data // Opaque user data
);

//── Model‐execution context ───────────────────────────────────────────────────

// Holds all of the memory arenas, tensor pointers, model I/O, and user hooks
typedef struct {
    //── Public fields──────────────────────────────────────────────────────────

    // Operator callback handle
    hkv_arrhythmia_operator_callback callback;
    void * user_data;

    //── Internal fields────────────────────────────────────────────────────────
    // Memory arenas for scratch tensors
    const void * const * arena_buffers;
    const size_t * arena_sizes;

    // Lifecycle latch: set to 1 only on successful model_init tail.
    // model_run early-returns status_not_initialized when this is 0.
    uint32_t _lifecycle_state;

    // Pointer table for *every* tensor (constant, persistent, scratch)
    int8_t *tensor_ptrs[hkv_arrhythmia_num_tensors];

    // Convenience view for model I/O
    hkv_arrhythmia_tensor_io_t inputs[hkv_arrhythmia_num_inputs];
    hkv_arrhythmia_tensor_io_t outputs[hkv_arrhythmia_num_outputs];

} hkv_arrhythmia_model_context_t;

/**
 * @brief heliaAOT context init
 *
 * Wires the per-tensor pointer table, populates the I/O convenience
 * views, clears the lifecycle latch (so a subsequent
 * ``hkv_arrhythmia_model_run`` requires a successful
 * ``hkv_arrhythmia_model_init``), and (for staged-constant builds)
 * clears the hydration latch.
 *
 * @note ``hkv_arrhythmia_model_init`` calls this internally; callers
 *       using ``hkv_arrhythmia_model_init`` as the entry point must
 *       NOT also call ``hkv_arrhythmia_context_init`` separately.
 *       Doing so would clear both the lifecycle and hydration
 *       latches, requiring a full ``hkv_arrhythmia_model_init`` (and,
 *       for manual-hydration builds,
 *       ``hkv_arrhythmia_hydrate_constants``) before
 *       ``hkv_arrhythmia_model_run`` will succeed again.
 *
 * @note Not thread-safe. The arena binding table and hydration latch
 *       are module-global; concurrent calls from multiple threads
 *       must be serialized externally.
 *
 * @param[in] ctx  The context struct to populate
 * @return ``hkv_arrhythmia_status_ok`` (0) on success.
 *         ``hkv_arrhythmia_status_null_context`` (13) if @p ctx is
 *         NULL.
 *         ``hkv_arrhythmia_status_context_arena_unbound`` (10) if any
 *         arena region has not been bound (external-arena mode
 *         only; see ``hkv_arrhythmia_bind_arena``).
 */
int32_t hkv_arrhythmia_context_init(
    hkv_arrhythmia_model_context_t *ctx
);

#ifdef __cplusplus
}
#endif