/******************************************************************************
 * @file        hkv_arrhythmia_tensors.h
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// ABI guard fingerprint for the generated arena layout.
//
// SHA-256(role|memory|source_memory|size|alignment|is_staged) over
// every region in region_id order, truncated to 16 hex chars. Stays
// stable across re-plans of the same model and changes whenever any
// region's role / memory residency / size / alignment / staged
// status changes. Downstream binaries that hard-code arena region
// IDs can validate this matches the planner that built their loader
// before binding arenas.
#define HKV_ARRHYTHMIA_PLAN_HASH "5d2b8211f7f2f774"

//── Tensor/Memory Definitions ─────────────────────────────────────────────────

// Tensor ID enumeration
typedef enum {
    hkv_arrhythmia_tensor_0 = 0,
    hkv_arrhythmia_tensor_2 = 1,
    hkv_arrhythmia_tensor_3 = 2,
    hkv_arrhythmia_tensor_4 = 3,
    hkv_arrhythmia_tensor_7 = 4,
    hkv_arrhythmia_tensor_9 = 5,
    hkv_arrhythmia_tensor_11 = 6,
    hkv_arrhythmia_tensor_13 = 7,
    hkv_arrhythmia_tensor_15 = 8,
    hkv_arrhythmia_tensor_17 = 9,
    hkv_arrhythmia_tensor_19 = 10,
    hkv_arrhythmia_tensor_21 = 11,
    hkv_arrhythmia_tensor_23 = 12,
    hkv_arrhythmia_tensor_25 = 13,
    hkv_arrhythmia_tensor_27 = 14,
    hkv_arrhythmia_tensor_29 = 15,
    hkv_arrhythmia_tensor_31 = 16,
    hkv_arrhythmia_tensor_33 = 17,
    hkv_arrhythmia_tensor_35 = 18,
    hkv_arrhythmia_tensor_37 = 19,
    hkv_arrhythmia_tensor_39 = 20,
    hkv_arrhythmia_tensor_41 = 21,
    hkv_arrhythmia_tensor_42 = 22,
    hkv_arrhythmia_tensor_44 = 23,
    hkv_arrhythmia_tensor_46 = 24,
    hkv_arrhythmia_tensor_48 = 25,
    hkv_arrhythmia_tensor_50 = 26,
    hkv_arrhythmia_tensor_51 = 27,
    hkv_arrhythmia_tensor_52 = 28,
    hkv_arrhythmia_tensor_53 = 29,
    hkv_arrhythmia_tensor_54 = 30,
    hkv_arrhythmia_tensor_55 = 31,
    hkv_arrhythmia_tensor_56 = 32,
    hkv_arrhythmia_tensor_57 = 33,
    hkv_arrhythmia_tensor_58 = 34,
    hkv_arrhythmia_tensor_59 = 35,
    hkv_arrhythmia_tensor_60 = 36,
    hkv_arrhythmia_tensor_61 = 37,
    hkv_arrhythmia_tensor_62 = 38,
    hkv_arrhythmia_tensor_63 = 39,
    hkv_arrhythmia_tensor_64 = 40,
    hkv_arrhythmia_tensor_65 = 41,
    hkv_arrhythmia_tensor_66 = 42,
    hkv_arrhythmia_tensor_67 = 43,
    hkv_arrhythmia_tensor_68 = 44,
    hkv_arrhythmia_tensor_69 = 45,
    hkv_arrhythmia_tensor_70 = 46,
    hkv_arrhythmia_tensor_71 = 47,
    hkv_arrhythmia_tensor_72 = 48,
    hkv_arrhythmia_tensor_73 = 49,
    hkv_arrhythmia_tensor_74 = 50,
    hkv_arrhythmia_tensor_75 = 51,
    hkv_arrhythmia_tensor_76 = 52,
    hkv_arrhythmia_tensor_77 = 53,
    hkv_arrhythmia_tensor_78 = 54,
    hkv_arrhythmia_tensor_79 = 55,
    hkv_arrhythmia_tensor_80 = 56,
    hkv_arrhythmia_tensor_81 = 57,
    hkv_arrhythmia_tensor_82 = 58,
    hkv_arrhythmia_tensor_83 = 59,
    hkv_arrhythmia_tensor_84 = 60,
    hkv_arrhythmia_tensor_85 = 61,
    hkv_arrhythmia_tensor_86 = 62,
    hkv_arrhythmia_tensor_87 = 63,
    hkv_arrhythmia_tensor_88 = 64,
    hkv_arrhythmia_tensor_89 = 65,
    hkv_arrhythmia_tensor_90 = 66,
    hkv_arrhythmia_tensor_91 = 67,
    hkv_arrhythmia_tensor_92 = 68,
    hkv_arrhythmia_tensor_93 = 69,
    hkv_arrhythmia_tensor_94 = 70,
    hkv_arrhythmia_tensor_95 = 71,
    hkv_arrhythmia_tensor_96 = 72,
    hkv_arrhythmia_tensor_97 = 73,
    hkv_arrhythmia_tensor_98 = 74,
    hkv_arrhythmia_tensor_99 = 75,
    hkv_arrhythmia_tensor_100 = 76,
    hkv_arrhythmia_tensor_conv_2d_5_scratch = 77,
    hkv_arrhythmia_tensor_conv_2d_5_weight_sum = 78,
    hkv_arrhythmia_tensor_conv_2d_5_multiplier = 79,
    hkv_arrhythmia_tensor_conv_2d_5_shift = 80,
    hkv_arrhythmia_tensor_depthwise_conv_2d_6_scratch = 81,
    hkv_arrhythmia_tensor_depthwise_conv_2d_6_weight_sum = 82,
    hkv_arrhythmia_tensor_depthwise_conv_2d_6_multiplier = 83,
    hkv_arrhythmia_tensor_depthwise_conv_2d_6_shift = 84,
    hkv_arrhythmia_tensor_conv_2d_9_weight_sum = 85,
    hkv_arrhythmia_tensor_conv_2d_9_multiplier = 86,
    hkv_arrhythmia_tensor_conv_2d_9_shift = 87,
    hkv_arrhythmia_tensor_conv_2d_10_weight_sum = 88,
    hkv_arrhythmia_tensor_conv_2d_10_multiplier = 89,
    hkv_arrhythmia_tensor_conv_2d_10_shift = 90,
    hkv_arrhythmia_tensor_conv_2d_13_weight_sum = 91,
    hkv_arrhythmia_tensor_conv_2d_13_multiplier = 92,
    hkv_arrhythmia_tensor_conv_2d_13_shift = 93,
    hkv_arrhythmia_tensor_depthwise_conv_2d_14_scratch = 94,
    hkv_arrhythmia_tensor_depthwise_conv_2d_14_weight_sum = 95,
    hkv_arrhythmia_tensor_depthwise_conv_2d_14_multiplier = 96,
    hkv_arrhythmia_tensor_depthwise_conv_2d_14_shift = 97,
    hkv_arrhythmia_tensor_conv_2d_17_weight_sum = 98,
    hkv_arrhythmia_tensor_conv_2d_17_multiplier = 99,
    hkv_arrhythmia_tensor_conv_2d_17_shift = 100,
    hkv_arrhythmia_tensor_conv_2d_18_weight_sum = 101,
    hkv_arrhythmia_tensor_conv_2d_18_multiplier = 102,
    hkv_arrhythmia_tensor_conv_2d_18_shift = 103,
    hkv_arrhythmia_tensor_conv_2d_21_weight_sum = 104,
    hkv_arrhythmia_tensor_conv_2d_21_multiplier = 105,
    hkv_arrhythmia_tensor_conv_2d_21_shift = 106,
    hkv_arrhythmia_tensor_depthwise_conv_2d_22_scratch = 107,
    hkv_arrhythmia_tensor_depthwise_conv_2d_22_weight_sum = 108,
    hkv_arrhythmia_tensor_depthwise_conv_2d_22_multiplier = 109,
    hkv_arrhythmia_tensor_depthwise_conv_2d_22_shift = 110,
    hkv_arrhythmia_tensor_conv_2d_25_weight_sum = 111,
    hkv_arrhythmia_tensor_conv_2d_25_multiplier = 112,
    hkv_arrhythmia_tensor_conv_2d_25_shift = 113,
    hkv_arrhythmia_tensor_conv_2d_26_weight_sum = 114,
    hkv_arrhythmia_tensor_conv_2d_26_multiplier = 115,
    hkv_arrhythmia_tensor_conv_2d_26_shift = 116,
    hkv_arrhythmia_tensor_conv_2d_29_weight_sum = 117,
    hkv_arrhythmia_tensor_conv_2d_29_multiplier = 118,
    hkv_arrhythmia_tensor_conv_2d_29_shift = 119,
    hkv_arrhythmia_tensor_depthwise_conv_2d_30_scratch = 120,
    hkv_arrhythmia_tensor_depthwise_conv_2d_30_weight_sum = 121,
    hkv_arrhythmia_tensor_depthwise_conv_2d_30_multiplier = 122,
    hkv_arrhythmia_tensor_depthwise_conv_2d_30_shift = 123,
    hkv_arrhythmia_tensor_conv_2d_33_weight_sum = 124,
    hkv_arrhythmia_tensor_conv_2d_33_multiplier = 125,
    hkv_arrhythmia_tensor_conv_2d_33_shift = 126,
    hkv_arrhythmia_tensor_conv_2d_34_weight_sum = 127,
    hkv_arrhythmia_tensor_conv_2d_34_multiplier = 128,
    hkv_arrhythmia_tensor_conv_2d_34_shift = 129,
    hkv_arrhythmia_tensor_conv_2d_37_weight_sum = 130,
    hkv_arrhythmia_tensor_conv_2d_37_multiplier = 131,
    hkv_arrhythmia_tensor_conv_2d_37_shift = 132,
    hkv_arrhythmia_tensor_depthwise_conv_2d_38_scratch = 133,
    hkv_arrhythmia_tensor_depthwise_conv_2d_38_weight_sum = 134,
    hkv_arrhythmia_tensor_depthwise_conv_2d_38_multiplier = 135,
    hkv_arrhythmia_tensor_depthwise_conv_2d_38_shift = 136,
    hkv_arrhythmia_tensor_conv_2d_41_weight_sum = 137,
    hkv_arrhythmia_tensor_conv_2d_41_multiplier = 138,
    hkv_arrhythmia_tensor_conv_2d_41_shift = 139,
    hkv_arrhythmia_tensor_conv_2d_42_weight_sum = 140,
    hkv_arrhythmia_tensor_conv_2d_42_multiplier = 141,
    hkv_arrhythmia_tensor_conv_2d_42_shift = 142,
    hkv_arrhythmia_tensor_conv_2d_45_weight_sum = 143,
    hkv_arrhythmia_tensor_conv_2d_45_multiplier = 144,
    hkv_arrhythmia_tensor_conv_2d_45_shift = 145,
    hkv_arrhythmia_tensor_fully_connected_47_weight_sum = 146,
    hkv_arrhythmia_tensor_fully_connected_47_multiplier = 147,
    hkv_arrhythmia_tensor_fully_connected_47_shift = 148,
    hkv_arrhythmia_num_tensors = 149
} hkv_arrhythmia_tensor_ident_t;

// Input/Output descriptors
typedef struct {
    hkv_arrhythmia_tensor_ident_t id;
    int8_t *data;  // pointer into context tensor_ptrs[]
    size_t size;  // Tensor size in bytes
    int32_t zero_point;  // Quantization zero-point
    float scale;  // Quantization scale
} hkv_arrhythmia_tensor_io_t;

// Memory arenas enumeration. Region IDs come from the render plan's
// deterministic ordering policy (scratch < persistent < constant;
// within-role: memory.name ascending) so two re-plans of the same
// model produce identical enum values. The PLAN_HASH macro above
// fingerprints the same ordering for ABI drift detection.
typedef enum {
    hkv_arrhythmia_arena_dtcm = 0,
    hkv_arrhythmia_arena_const_mram = 1,
    hkv_arrhythmia_num_arena_buffers = 2
} hkv_arrhythmia_arena_region_t;

// Runtime status codes returned by the generated C API.
//
// Numeric values are organized into namespaced ranges so callers can
// disambiguate which API surface produced an error without
// out-of-band context:
//
//   * 0          : success.
//   * 1..4       : per-region ``hkv_arrhythmia_bind_arena`` failures
//                  (also forwarded by ``hkv_arrhythmia_bind_arenas`` for
//                  per-region issues).
//   * 10..12     : ``hkv_arrhythmia_context_init`` /
//                  ``hkv_arrhythmia_hydrate_constants`` preconditions.
//   * 13         : common ``ctx == NULL`` precondition failure
//                  shared across every public entry point.
//   * 14         : lifecycle precondition (``model_run`` before
//                  successful ``model_init``).
//   * 100..109   : ``hkv_arrhythmia_bind_arenas`` bulk-argument failures.
//   * 200..209   : ``hkv_arrhythmia_model_run`` precondition failures
//                  (e.g. hydration latch).
//
// Code that needs to inspect status values should prefer the
// enumerator names below; raw literals are reserved for snapshot /
// ABI-stability tests.
typedef enum {
    hkv_arrhythmia_status_ok = 0,

    // bind_arena() per-region failures.
    hkv_arrhythmia_status_bind_unknown_region   = 1,
    hkv_arrhythmia_status_bind_null_buffer      = 2,
    hkv_arrhythmia_status_bind_undersized       = 3,
    hkv_arrhythmia_status_bind_misaligned       = 4,

    // context_init() / hydrate_constants() failures.
    hkv_arrhythmia_status_context_arena_unbound = 10,
    // hydrate_constants() called on a context whose arena_buffers
    // table is still NULL (i.e. before context_init succeeded).
    hkv_arrhythmia_status_hydrate_uninited_context = 11,
    hkv_arrhythmia_status_hydrate_null_blob     = 12,

    // Common precondition failure (any public entry point).
    hkv_arrhythmia_status_null_context          = 13,
    // model_run() called before model_init() succeeded.
    hkv_arrhythmia_status_not_initialized       = 14,

    // bind_arenas() bulk-argument failures (per-region failures
    // forward the 1..4 range above).
    hkv_arrhythmia_status_bind_bulk_null_argument = 100,
    hkv_arrhythmia_status_bind_bulk_wrong_count   = 101,

    // model_run() precondition failures.
    hkv_arrhythmia_status_hydration_required = 200,
} hkv_arrhythmia_status_t;

// Tensor categories
typedef enum {
    hkv_arrhythmia_tensor_type_constant,
    hkv_arrhythmia_tensor_type_persistent,
    hkv_arrhythmia_tensor_type_scratch,
} hkv_arrhythmia_tensor_type_t;

// Tensor descriptors. Every tensor — scratch, persistent, or
// constant — is bound to an arena slot. The kernel-visible address
// is always ``arena_buffers[region] + offset``. There are no
// per-tensor C symbols.
typedef struct {
    hkv_arrhythmia_tensor_type_t type;
    hkv_arrhythmia_arena_region_t region;
    size_t offset;
    size_t size;
} hkv_arrhythmia_tensor_descriptor_t;

//── Memory Arenas ─────────────────────────────────────────────────────────────

#define hkv_arrhythmia_arena_dtcm_size  14976
#define hkv_arrhythmia_arena_dtcm_alignment  16
#define hkv_arrhythmia_arena_const_mram_size  25380
#define hkv_arrhythmia_arena_const_mram_alignment  16

extern const void * const hkv_arrhythmia_arena_buffers[hkv_arrhythmia_num_arena_buffers];
/**
 * @brief Per-region capacity of every arena, in bytes.
 *
 * This table has **two** meanings, depending on the arena role:
 *
 *  - **Scratch / persistent / staged-constant** arenas:
 *    ``arena_sizes[region]`` is the runtime buffer size the caller
 *    must provide. In internal-arena mode the generated
 *    ``hkv_arrhythmia_arena_*_buffer`` storage is exactly this size.
 *    In external-arena mode (``allocate_arenas=false``) the caller
 *    must bind a buffer at least this large via
 *    ``hkv_arrhythmia_bind_arena``.
 *
 *  - **Cold-constant** arenas (``source_memory == memory``):
 *    ``arena_sizes[region]`` is the size of the cold blob in flash
 *    (or equivalent read-only memory). Kernels read the blob in
 *    place; there is no separate runtime buffer. In external-arena
 *    mode the caller must bind this region to a pointer to the
 *    cold blob itself (or to the matching ``__blob.bin`` sidecar
 *    when the C source omits the literal).
 *
 * Use ``hkv_arrhythmia_tensor_descriptors[i].region`` to find which
 * arena a given tensor lives in, and the corresponding
 * ``arena_sizes[region]`` for its containing arena's capacity.
 */
extern const size_t hkv_arrhythmia_arena_sizes[hkv_arrhythmia_num_arena_buffers];

/**
 * @brief Per-region alignment requirement (bytes) for caller-supplied
 *        arena buffers in external-arena mode.
 *
 * Each value is a power of two and reflects the strictest alignment
 * required by any tensor placed in that arena (platform floor or
 * per-arena ``arena_alignment`` override, whichever is larger).
 * ``hkv_arrhythmia_bind_arena`` returns status 4 if a buffer pointer
 * does not satisfy the corresponding entry. Internal-arena builds
 * (`allocate_arenas=true`) emit each buffer with
 * ``alignas(...)`` matching this table, so the constraint is
 * automatically met.
 */
extern const size_t hkv_arrhythmia_arena_alignments[hkv_arrhythmia_num_arena_buffers];

//── Model Input/Output ────────────────────────────────────────────────────────

#define hkv_arrhythmia_num_inputs 1
#define hkv_arrhythmia_num_outputs 1

#define hkv_arrhythmia_input_0_size (500)
#define hkv_arrhythmia_output_0_size (4)

extern const hkv_arrhythmia_tensor_ident_t hkv_arrhythmia_inputs_id[hkv_arrhythmia_num_inputs];
extern const hkv_arrhythmia_tensor_ident_t hkv_arrhythmia_outputs_id[hkv_arrhythmia_num_outputs];
extern const int32_t hkv_arrhythmia_inputs_len[hkv_arrhythmia_num_inputs];
extern const int32_t hkv_arrhythmia_inputs_zero_point[hkv_arrhythmia_num_inputs];
extern const float hkv_arrhythmia_inputs_scale[hkv_arrhythmia_num_inputs];
extern const int32_t hkv_arrhythmia_outputs_len[hkv_arrhythmia_num_outputs];
extern const int32_t hkv_arrhythmia_outputs_zero_point[hkv_arrhythmia_num_outputs];
extern const float hkv_arrhythmia_outputs_scale[hkv_arrhythmia_num_outputs];

//── Model Tensors ─────────────────────────────────────────────────────────────

// Per-tensor byte size lives on the descriptor (``hkv_arrhythmia_tensor_descriptors[i].size``);
// per-tensor element count is the descriptor size divided by the
// element width. Public ``_size`` macros are emitted only for model
// inputs/outputs above, where they are part of the stable I/O API.

// Tensor descriptors
extern const hkv_arrhythmia_tensor_descriptor_t hkv_arrhythmia_tensor_descriptors[hkv_arrhythmia_num_tensors];

#ifdef __cplusplus
}
#endif