/******************************************************************************
 * @file        hkv_arrhythmia_common.h
 * @brief       HeliaT common API
 * @details     Helper to pull in all common headers
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

//── 1) Compiler attributes and helpers ────────────────────────────────────────

#include "hkv_arrhythmia_compiler.h"

//── 2) Standard C types and macros ────────────────────────────────────────────

#include <math.h>     // for isnan, isinf
#include <float.h>    // for FLT_MAX, FLT_MIN
#include <stddef.h>   // for size_t, NULL
#include <stdint.h>   // for int8_t, int32_t, etc.
#include <stdalign.h> // for alignas()
#include <stdbool.h>  // for bool, true, false

//── 3) Platform hooks ─────────────────────────────────────────────────────────

#include "hkv_arrhythmia_platform.h"

//── 4) ns-cmsis-nn public API ─────────────────────────────────────────────────

#include "arm_nnfunctions.h"
#include "arm_nnsupportfunctions.h"

// Public float kernel API (``arm_*_f16``/``arm_*_f32``) — shipped in
// ns-cmsis-nn since v7.28.0. Only pulled in when this module
// actually dispatches to float kernels: the float type header (transitively
// ``arm_nn_types_flt.h``) hard-``#error``s when neither ``ARM_NN_ENABLE_F32``
// nor ``ARM_NN_ENABLE_F16`` is set, so integer-only modules must not include it
// under the ns-cmsis-nn default (both options OFF). Inclusion stays guarded so
// pre-float toolchains still build; float-dispatching operators #error at
// compile time if the header is absent.

// Verify ns-cmsis-nn version compatibility.
// All three components are compared on purpose. The floor is set past releases
// that are defective rather than merely old (v7.29.0 broadcast results, v7.30.0
// sizer and undefined-behaviour faults), and those exclusions can land on a
// patch boundary, where a major/minor-only test would accept exactly the
// release the floor exists to exclude.
#if (NS_CMSIS_NN_VERSION_MAJOR < 7) || \
    (NS_CMSIS_NN_VERSION_MAJOR == 7 && \
     NS_CMSIS_NN_VERSION_MINOR < 31) || \
    (NS_CMSIS_NN_VERSION_MAJOR == 7 && \
     NS_CMSIS_NN_VERSION_MINOR == 31 && \
     NS_CMSIS_NN_VERSION_PATCH < 0)
  #error "CMSIS-NN version too old; need at least v7.31.0"
#endif

//── 5) AOT core definitions ───────────────────────────────────────────────────

#include "hkv_arrhythmia_tensors.h"
#include "hkv_arrhythmia_context.h"