/******************************************************************************
 * @file        hkv_denoise_tensors.h
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// ABI guard fingerprint for the generated arena layout.
//
// SHA-256(role|memory|source_memory|size|alignment|is_staged) over
// every region in region_id order, truncated to 16 hex chars. Stays
// stable across re-plans of the same model and changes whenever any
// region's role / memory residency / size / alignment / staged
// status changes. Downstream binaries that hard-code arena region
// IDs can validate this matches the planner that built their loader
// before binding arenas.
#define HKV_DENOISE_PLAN_HASH "02d29fc56add9d56"

//── Tensor/Memory Definitions ─────────────────────────────────────────────────

// Tensor ID enumeration
typedef enum {
    hkv_denoise_tensor_0 = 0,
    hkv_denoise_tensor_1 = 1,
    hkv_denoise_tensor_2 = 2,
    hkv_denoise_tensor_3 = 3,
    hkv_denoise_tensor_4 = 4,
    hkv_denoise_tensor_5 = 5,
    hkv_denoise_tensor_6 = 6,
    hkv_denoise_tensor_7 = 7,
    hkv_denoise_tensor_8 = 8,
    hkv_denoise_tensor_9 = 9,
    hkv_denoise_tensor_10 = 10,
    hkv_denoise_tensor_11 = 11,
    hkv_denoise_tensor_12 = 12,
    hkv_denoise_tensor_13 = 13,
    hkv_denoise_tensor_14 = 14,
    hkv_denoise_tensor_15 = 15,
    hkv_denoise_tensor_16 = 16,
    hkv_denoise_tensor_17 = 17,
    hkv_denoise_tensor_18 = 18,
    hkv_denoise_tensor_19 = 19,
    hkv_denoise_tensor_20 = 20,
    hkv_denoise_tensor_21 = 21,
    hkv_denoise_tensor_22 = 22,
    hkv_denoise_tensor_23 = 23,
    hkv_denoise_tensor_24 = 24,
    hkv_denoise_tensor_25 = 25,
    hkv_denoise_tensor_26 = 26,
    hkv_denoise_tensor_27 = 27,
    hkv_denoise_tensor_28 = 28,
    hkv_denoise_tensor_29 = 29,
    hkv_denoise_tensor_30 = 30,
    hkv_denoise_tensor_31 = 31,
    hkv_denoise_tensor_32 = 32,
    hkv_denoise_tensor_35 = 33,
    hkv_denoise_tensor_37 = 34,
    hkv_denoise_tensor_38 = 35,
    hkv_denoise_tensor_39 = 36,
    hkv_denoise_tensor_40 = 37,
    hkv_denoise_tensor_41 = 38,
    hkv_denoise_tensor_42 = 39,
    hkv_denoise_tensor_43 = 40,
    hkv_denoise_tensor_44 = 41,
    hkv_denoise_tensor_45 = 42,
    hkv_denoise_tensor_46 = 43,
    hkv_denoise_tensor_47 = 44,
    hkv_denoise_tensor_48 = 45,
    hkv_denoise_tensor_49 = 46,
    hkv_denoise_tensor_50 = 47,
    hkv_denoise_tensor_51 = 48,
    hkv_denoise_tensor_52 = 49,
    hkv_denoise_tensor_53 = 50,
    hkv_denoise_tensor_54 = 51,
    hkv_denoise_tensor_55 = 52,
    hkv_denoise_tensor_56 = 53,
    hkv_denoise_tensor_57 = 54,
    hkv_denoise_tensor_58 = 55,
    hkv_denoise_tensor_59 = 56,
    hkv_denoise_tensor_60 = 57,
    hkv_denoise_tensor_61 = 58,
    hkv_denoise_tensor_62 = 59,
    hkv_denoise_tensor_63 = 60,
    hkv_denoise_tensor_64 = 61,
    hkv_denoise_tensor_65 = 62,
    hkv_denoise_tensor_66 = 63,
    hkv_denoise_tensor_conv_2d_28_scratch = 64,
    hkv_denoise_num_tensors = 65
} hkv_denoise_tensor_ident_t;

// Input/Output descriptors
typedef struct {
    hkv_denoise_tensor_ident_t id;
    int8_t *data;  // pointer into context tensor_ptrs[]
    size_t size;  // Tensor size in bytes
    int32_t zero_point;  // Quantization zero-point
    float scale;  // Quantization scale
} hkv_denoise_tensor_io_t;

// Memory arenas enumeration. Region IDs come from the render plan's
// deterministic ordering policy (scratch < persistent < constant;
// within-role: memory.name ascending) so two re-plans of the same
// model produce identical enum values. The PLAN_HASH macro above
// fingerprints the same ordering for ABI drift detection.
typedef enum {
    hkv_denoise_arena_sram = 0,
    hkv_denoise_arena_const_mram = 1,
    hkv_denoise_num_arena_buffers = 2
} hkv_denoise_arena_region_t;

// Runtime status codes returned by the generated C API.
//
// Numeric values are organized into namespaced ranges so callers can
// disambiguate which API surface produced an error without
// out-of-band context:
//
//   * 0          : success.
//   * 1..4       : per-region ``hkv_denoise_bind_arena`` failures
//                  (also forwarded by ``hkv_denoise_bind_arenas`` for
//                  per-region issues).
//   * 10..12     : ``hkv_denoise_context_init`` /
//                  ``hkv_denoise_hydrate_constants`` preconditions.
//   * 13         : common ``ctx == NULL`` precondition failure
//                  shared across every public entry point.
//   * 14         : lifecycle precondition (``model_run`` before
//                  successful ``model_init``).
//   * 100..109   : ``hkv_denoise_bind_arenas`` bulk-argument failures.
//   * 200..209   : ``hkv_denoise_model_run`` precondition failures
//                  (e.g. hydration latch).
//
// Code that needs to inspect status values should prefer the
// enumerator names below; raw literals are reserved for snapshot /
// ABI-stability tests.
typedef enum {
    hkv_denoise_status_ok = 0,

    // bind_arena() per-region failures.
    hkv_denoise_status_bind_unknown_region   = 1,
    hkv_denoise_status_bind_null_buffer      = 2,
    hkv_denoise_status_bind_undersized       = 3,
    hkv_denoise_status_bind_misaligned       = 4,

    // context_init() / hydrate_constants() failures.
    hkv_denoise_status_context_arena_unbound = 10,
    // hydrate_constants() called on a context whose arena_buffers
    // table is still NULL (i.e. before context_init succeeded).
    hkv_denoise_status_hydrate_uninited_context = 11,
    hkv_denoise_status_hydrate_null_blob     = 12,

    // Common precondition failure (any public entry point).
    hkv_denoise_status_null_context          = 13,
    // model_run() called before model_init() succeeded.
    hkv_denoise_status_not_initialized       = 14,

    // bind_arenas() bulk-argument failures (per-region failures
    // forward the 1..4 range above).
    hkv_denoise_status_bind_bulk_null_argument = 100,
    hkv_denoise_status_bind_bulk_wrong_count   = 101,

    // model_run() precondition failures.
    hkv_denoise_status_hydration_required = 200,
} hkv_denoise_status_t;

// Tensor categories
typedef enum {
    hkv_denoise_tensor_type_constant,
    hkv_denoise_tensor_type_persistent,
    hkv_denoise_tensor_type_scratch,
} hkv_denoise_tensor_type_t;

// Tensor descriptors. Every tensor — scratch, persistent, or
// constant — is bound to an arena slot. The kernel-visible address
// is always ``arena_buffers[region] + offset``. There are no
// per-tensor C symbols.
typedef struct {
    hkv_denoise_tensor_type_t type;
    hkv_denoise_arena_region_t region;
    size_t offset;
    size_t size;
} hkv_denoise_tensor_descriptor_t;

//── Memory Arenas ─────────────────────────────────────────────────────────────

#define hkv_denoise_arena_sram_size  65600
#define hkv_denoise_arena_sram_alignment  16
#define hkv_denoise_arena_const_mram_size  11892
#define hkv_denoise_arena_const_mram_alignment  16

extern const void * const hkv_denoise_arena_buffers[hkv_denoise_num_arena_buffers];
/**
 * @brief Per-region capacity of every arena, in bytes.
 *
 * This table has **two** meanings, depending on the arena role:
 *
 *  - **Scratch / persistent / staged-constant** arenas:
 *    ``arena_sizes[region]`` is the runtime buffer size the caller
 *    must provide. In internal-arena mode the generated
 *    ``hkv_denoise_arena_*_buffer`` storage is exactly this size.
 *    In external-arena mode (``allocate_arenas=false``) the caller
 *    must bind a buffer at least this large via
 *    ``hkv_denoise_bind_arena``.
 *
 *  - **Cold-constant** arenas (``source_memory == memory``):
 *    ``arena_sizes[region]`` is the size of the cold blob in flash
 *    (or equivalent read-only memory). Kernels read the blob in
 *    place; there is no separate runtime buffer. In external-arena
 *    mode the caller must bind this region to a pointer to the
 *    cold blob itself (or to the matching ``__blob.bin`` sidecar
 *    when the C source omits the literal).
 *
 * Use ``hkv_denoise_tensor_descriptors[i].region`` to find which
 * arena a given tensor lives in, and the corresponding
 * ``arena_sizes[region]`` for its containing arena's capacity.
 */
extern const size_t hkv_denoise_arena_sizes[hkv_denoise_num_arena_buffers];

/**
 * @brief Per-region alignment requirement (bytes) for caller-supplied
 *        arena buffers in external-arena mode.
 *
 * Each value is a power of two and reflects the strictest alignment
 * required by any tensor placed in that arena (platform floor or
 * per-arena ``arena_alignment`` override, whichever is larger).
 * ``hkv_denoise_bind_arena`` returns status 4 if a buffer pointer
 * does not satisfy the corresponding entry. Internal-arena builds
 * (`allocate_arenas=true`) emit each buffer with
 * ``alignas(...)`` matching this table, so the constraint is
 * automatically met.
 */
extern const size_t hkv_denoise_arena_alignments[hkv_denoise_num_arena_buffers];

//── Model Input/Output ────────────────────────────────────────────────────────

#define hkv_denoise_num_inputs 1
#define hkv_denoise_num_outputs 1

// These ``_size`` macros are element counts; ``hkv_denoise_tensor_io_t.size`` is bytes.
#define hkv_denoise_input_0_size (256)
#define hkv_denoise_output_0_size (256)

extern const hkv_denoise_tensor_ident_t hkv_denoise_inputs_id[hkv_denoise_num_inputs];
extern const hkv_denoise_tensor_ident_t hkv_denoise_outputs_id[hkv_denoise_num_outputs];
extern const int32_t hkv_denoise_inputs_len[hkv_denoise_num_inputs];
extern const int32_t hkv_denoise_inputs_zero_point[hkv_denoise_num_inputs];
extern const float hkv_denoise_inputs_scale[hkv_denoise_num_inputs];
extern const int32_t hkv_denoise_outputs_len[hkv_denoise_num_outputs];
extern const int32_t hkv_denoise_outputs_zero_point[hkv_denoise_num_outputs];
extern const float hkv_denoise_outputs_scale[hkv_denoise_num_outputs];

//── Model Tensors ─────────────────────────────────────────────────────────────

// Per-tensor byte size lives on the descriptor (``hkv_denoise_tensor_descriptors[i].size``);
// per-tensor element count is the descriptor size divided by the
// element width. Public ``_size`` macros are emitted only for model
// inputs/outputs above, where they are part of the stable I/O API.

// Tensor descriptors
extern const hkv_denoise_tensor_descriptor_t hkv_denoise_tensor_descriptors[hkv_denoise_num_tensors];

#ifdef __cplusplus
}
#endif