/******************************************************************************
 * @file        hkv_denoise_platform.h
 * @brief       heliaAOT platform-specific hooks
 * @details     Defines platform-specific macros for logging, memory, etc.
 *              These macros shall be overridden by the application as needed.
 *              Default values are provided for known platforms like neuralSPOT.
 *              If no overrides are defined, these macros become no-ops.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

//── Platform dependencies ─────────────────────────────────────────────────────


//── Logging hooks ─────────────────────────────────────────────────────────────

#ifndef HKV_DENOISE_PRINTF
// NSX: logging is provided by the application (e.g. nsx-harness).
// Override HKV_DENOISE_PRINTF before including this header or via -D flag.
#define HKV_DENOISE_PRINTF(...)   ((void)0)
#endif

//── Memory hooks ──────────────────────────────────────────────────────────────
//
// NSX note: when module.type=nsx, all PUT_IN_* macros default to no-ops here.
// The NSX CMakeLists.txt provides an optional _ATTRIBUTES_HEADER hook that
// lets the consumer (e.g. heliaPROFILER) force-preinclude a header with real
// __attribute__((section(...))) definitions BEFORE these #ifndef guards fire.
//

#ifndef HKV_DENOISE_PUT_IN_PSRAM
#define HKV_DENOISE_PUT_IN_PSRAM
#endif
#ifndef HKV_DENOISE_PUT_IN_PSRAM_INIT
#define HKV_DENOISE_PUT_IN_PSRAM_INIT
#endif

#ifndef HKV_DENOISE_PUT_IN_DRAM
#define HKV_DENOISE_PUT_IN_DRAM
#endif
#ifndef HKV_DENOISE_PUT_IN_DRAM_INIT
#define HKV_DENOISE_PUT_IN_DRAM_INIT
#endif

#ifndef HKV_DENOISE_PUT_IN_MRAM
#define HKV_DENOISE_PUT_IN_MRAM
#endif
#ifndef HKV_DENOISE_PUT_IN_MRAM_INIT
#define HKV_DENOISE_PUT_IN_MRAM_INIT
#endif

#ifndef HKV_DENOISE_PUT_IN_SRAM
#define HKV_DENOISE_PUT_IN_SRAM
#endif
#ifndef HKV_DENOISE_PUT_IN_SRAM_INIT
#define HKV_DENOISE_PUT_IN_SRAM_INIT
#endif

#ifndef HKV_DENOISE_PUT_IN_DTCM
#define HKV_DENOISE_PUT_IN_DTCM
#endif
#ifndef HKV_DENOISE_PUT_IN_DTCM_INIT
#define HKV_DENOISE_PUT_IN_DTCM_INIT
#endif

//── Instruction hooks ─────────────────────────────────────────────────────────

#ifndef HKV_DENOISE_PUT_IN_ITCM
#define HKV_DENOISE_PUT_IN_ITCM
#endif

#ifndef HKV_DENOISE_PUT_IN_ITCM_INIT
#define HKV_DENOISE_PUT_IN_ITCM_INIT
#endif