/******************************************************************************
 * @file        hkv_denoise_operators.h
 * @brief       heliaAOT operators API
 * @details     Helper to pull in all operator headers
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include "hkv_denoise_reshape_0.h"
#include "hkv_denoise_depthwise_conv_2d_1.h"
#include "hkv_denoise_depthwise_conv_2d_2.h"
#include "hkv_denoise_conv_2d_3.h"
#include "hkv_denoise_depthwise_conv_2d_4.h"
#include "hkv_denoise_mean_5.h"
#include "hkv_denoise_conv_2d_6.h"
#include "hkv_denoise_conv_2d_7.h"
#include "hkv_denoise_minimum_8.h"
#include "hkv_denoise_relu_9.h"
#include "hkv_denoise_mul_10.h"
#include "hkv_denoise_conv_2d_11.h"
#include "hkv_denoise_depthwise_conv_2d_12.h"
#include "hkv_denoise_mean_13.h"
#include "hkv_denoise_conv_2d_14.h"
#include "hkv_denoise_conv_2d_15.h"
#include "hkv_denoise_minimum_16.h"
#include "hkv_denoise_relu_17.h"
#include "hkv_denoise_mul_18.h"
#include "hkv_denoise_conv_2d_19.h"
#include "hkv_denoise_depthwise_conv_2d_20.h"
#include "hkv_denoise_mean_21.h"
#include "hkv_denoise_conv_2d_22.h"
#include "hkv_denoise_conv_2d_23.h"
#include "hkv_denoise_minimum_24.h"
#include "hkv_denoise_relu_25.h"
#include "hkv_denoise_mul_26.h"
#include "hkv_denoise_conv_2d_27.h"
#include "hkv_denoise_conv_2d_28.h"
#include "hkv_denoise_reshape_29.h"
