/******************************************************************************
 * @file        hkv_denoise_minimum_16.c
 * @brief       Autogenerated AOT minimum kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '16' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_minimum_16.h"


// Input1 dimensions
static const cmsis_nn_dims minimum_16_input1_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 16
};

// Input2 dimensions
static const cmsis_nn_dims minimum_16_input2_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 1
};

// Output dimensions
static const cmsis_nn_dims minimum_16_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 16
};

// NOTE: No scratch buffer needed for minimum
static cmsis_nn_context minimum_16_ctx = {
    .buf = NULL,
    .size = 0,
};


int32_t
hkv_denoise_minimum_16_init(
    hkv_denoise_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_denoise_minimum_16_run(
    hkv_denoise_model_context_t *ctx
) {
    const float* __restrict input1 = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_52];
    const float* __restrict input2 = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_35];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_denoise_tensor_53];

    return arm_minimum_f32(
        &minimum_16_ctx,
        input1,
        &minimum_16_input1_dims,
        input2,
        &minimum_16_input2_dims,
        output,
        &minimum_16_output_dims
    );

}