/******************************************************************************
 * @file        hkv_denoise_mean_5.c
 * @brief       Autogenerated AOT mean kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '5' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_mean_5.h"


// Input dimensions
static const cmsis_nn_dims mean_5_input_dims = { .n = 1, .h = 1, .w = 256, .c = 8 };

// Axis dimensions: either 0 or 1 w/ 1 indicating reduction axis
static const cmsis_nn_dims mean_5_axis_dims = {
    .n = 0, .h = 1,
    .w = 1, .c = 0
};

// Output dimensions
static const cmsis_nn_dims mean_5_output_dims = { .n = 1, .h = 1, .w = 1, .c = 8 };



int32_t
hkv_denoise_mean_5_init(
    hkv_denoise_model_context_t *ctx
) {

    (void)ctx;
    return 0;
}

int32_t
hkv_denoise_mean_5_run(
    hkv_denoise_model_context_t *ctx
) {
    const float* __restrict input = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_41];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_denoise_tensor_42];

#if (NS_CMSIS_NN_VERSION_MAJOR < 7) || \
    (NS_CMSIS_NN_VERSION_MAJOR == 7 && NS_CMSIS_NN_VERSION_MINOR < 32) || \
    (NS_CMSIS_NN_VERSION_MAJOR == 7 && NS_CMSIS_NN_VERSION_MINOR == 32 && NS_CMSIS_NN_VERSION_PATCH < 0)
#error "float MEAN requires ns-cmsis-nn >= v7.32.0 (arm_nn_mean_f16/arm_nn_mean_f32)"
#endif
    return arm_nn_mean_f32(
        input,
        &mean_5_input_dims,
        &mean_5_axis_dims,
        output,
        &mean_5_output_dims
    );

}