/******************************************************************************
 * @file        hkv_denoise_context.c
 * @brief       heliaAOT model context API
 * @details     Defines and initializes the model context:
 *              - Assigns arena buffers & sizes
 *              - Registers callback & user_data
 *              - Populates tensor pointer arrays
 *              - Performs context-level validation
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_context.h"

int32_t hkv_denoise_context_init(
    hkv_denoise_model_context_t *ctx
) {
    if (ctx == NULL) {
        return hkv_denoise_status_null_context;
    }

    // Clear the lifecycle latch so that a stale init-success from a
    // previous lifetime cannot mask an incomplete re-init.
    ctx->_lifecycle_state = 0;

    // Wire up internal arena buffers
    ctx->arena_buffers = hkv_denoise_arena_buffers;
    ctx->arena_sizes = hkv_denoise_arena_sizes;

    // Resolve every tensor pointer through the unified arena model:
    // ``arena_buffers[region] + offset``. Cold-constant regions point
    // at a read-only blob; staged-constant and writable regions
    // point at runtime buffers.
    for (int i = 0; i < hkv_denoise_num_tensors; ++i) {
        const hkv_denoise_tensor_descriptor_t *desc = &hkv_denoise_tensor_descriptors[i];
        ctx->tensor_ptrs[i] = (int8_t *)ctx->arena_buffers[desc->region] + desc->offset;
    }

    // Wire up inputs and outputs. ``hkv_denoise_inputs_len`` /
    // ``hkv_denoise_outputs_len`` stay public as element counts, while
    // ``size`` here is bytes, so it comes from the tensor descriptor
    // (the two coincide only for one-byte element types).
    for (int i = 0; i < hkv_denoise_num_inputs; ++i) {
        hkv_denoise_tensor_ident_t id = hkv_denoise_inputs_id[i];
        ctx->inputs[i].id         = id;
        ctx->inputs[i].data       = ctx->tensor_ptrs[id];
        ctx->inputs[i].size       = hkv_denoise_tensor_descriptors[id].size;
        ctx->inputs[i].zero_point = hkv_denoise_inputs_zero_point[i];
        ctx->inputs[i].scale      = hkv_denoise_inputs_scale[i];
    }

    for (int i = 0; i < hkv_denoise_num_outputs; ++i) {
        hkv_denoise_tensor_ident_t id = hkv_denoise_outputs_id[i];
        ctx->outputs[i].id         = id;
        ctx->outputs[i].data       = ctx->tensor_ptrs[id];
        ctx->outputs[i].size       = hkv_denoise_tensor_descriptors[id].size;
        ctx->outputs[i].zero_point = hkv_denoise_outputs_zero_point[i];
        ctx->outputs[i].scale      = hkv_denoise_outputs_scale[i];
    }

    return 0;
}