/******************************************************************************
 * @file        hkv_denoise_conv_2d_15.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '15' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_conv_2d_15.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_15_input_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 8
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_15_filter_dims = {
    .n =  16, .h = 1,
    .w = 1, .c = 8
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_15_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 16
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_15_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 16
};



// Scratch buffer context
static cmsis_nn_context conv_2d_15_ctx = {
    .buf = NULL,
    .size = 0,
};



static const cmsis_nn_conv_params_f32 conv_2d_15_params = {
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 0,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -FLT_MAX,
    .activation.max = FLT_MAX,
    .weight_format = ARM_NN_WEIGHT_FORMAT_STANDARD,
};

// Grouped-conv semantics are derived inside the dispatched kernel from the
// input/filter channel relationship; helia-aot does not carry a separate AIR
// "groups" field for CONV_2D in this path.

int32_t
hkv_denoise_conv_2d_15_init(
    hkv_denoise_model_context_t *ctx
) {

    conv_2d_15_ctx.buf = NULL;
    conv_2d_15_ctx.size = 0;

    return 0;

}

int32_t
hkv_denoise_conv_2d_15_run(
    hkv_denoise_model_context_t *ctx
) {
    const float* __restrict input = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_51];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_denoise_tensor_52];
    return arm_convolve_1x1_f32(
        &conv_2d_15_ctx,
        &conv_2d_15_params,
        &conv_2d_15_input_dims,
        input,
        &conv_2d_15_filter_dims,
        (float *)ctx->tensor_ptrs[hkv_denoise_tensor_27],
        &conv_2d_15_bias_dims,
        (float *)ctx->tensor_ptrs[hkv_denoise_tensor_10],
        &conv_2d_15_output_dims,
        output,
        ARM_NN_LAYOUT_NHWC
    );

}