/******************************************************************************
 * @file        hkv_denoise_reshape_29.c
 * @brief       Autogenerated AOT reshape kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '29' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_reshape_29.h"


int32_t
hkv_denoise_reshape_29_init(
    hkv_denoise_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_denoise_reshape_29_run(
    hkv_denoise_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_denoise_tensor_65];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_denoise_tensor_66];
    if (input == output) { return 0; }

    arm_memcpy_s8(
        output,
        input,
        1024
    );

    return 0;

}