/******************************************************************************
 * @file        hkv_denoise_conv_2d_28.c
 * @brief       Autogenerated AOT conv_2d kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '28' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_conv_2d_28.h"

// Input dimensions (with optional implicit upscale) shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims conv_2d_28_input_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 32
};

// Filter dimensions: weights shape is [C_OUT, H_FILT, W_FILT, C_IN].
static const cmsis_nn_dims conv_2d_28_filter_dims = {
    .n =  1, .h = 1,
    .w = 7, .c = 32
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims conv_2d_28_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 1
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims conv_2d_28_output_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 1
};



// Scratch buffer context
static cmsis_nn_context conv_2d_28_ctx = {
    .buf = NULL,
    .size = 0,
};



static const cmsis_nn_conv_params_f32 conv_2d_28_params = {
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 3,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -FLT_MAX,
    .activation.max = FLT_MAX,
    .weight_format = ARM_NN_WEIGHT_FORMAT_STANDARD,
};

// Grouped-conv semantics are derived inside the dispatched kernel from the
// input/filter channel relationship; helia-aot does not carry a separate AIR
// "groups" field for CONV_2D in this path.

int32_t
hkv_denoise_conv_2d_28_init(
    hkv_denoise_model_context_t *ctx
) {

    conv_2d_28_ctx.buf = ctx->tensor_ptrs[hkv_denoise_tensor_conv_2d_28_scratch];
    conv_2d_28_ctx.size = 896;

    return 0;

}

int32_t
hkv_denoise_conv_2d_28_run(
    hkv_denoise_model_context_t *ctx
) {
    const float* __restrict input = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_64];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_denoise_tensor_65];
    return arm_convolve_1_x_n_f32(
        &conv_2d_28_ctx,
        &conv_2d_28_params,
        &conv_2d_28_input_dims,
        input,
        &conv_2d_28_filter_dims,
        (float *)ctx->tensor_ptrs[hkv_denoise_tensor_32],
        &conv_2d_28_bias_dims,
        (float *)ctx->tensor_ptrs[hkv_denoise_tensor_21],
        &conv_2d_28_output_dims,
        output,
        ARM_NN_LAYOUT_NHWC
    );

}