/******************************************************************************
 * @file        hkv_denoise_tensors.c
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_tensors.h"


//── Memory Arenas ─────────────────────────────────────────────────────────────

const size_t hkv_denoise_arena_sizes[hkv_denoise_num_arena_buffers] = {
    [hkv_denoise_arena_sram] = hkv_denoise_arena_sram_size,
    [hkv_denoise_arena_const_mram] = hkv_denoise_arena_const_mram_size,
};

// Per-region alignment (bytes). Caller-supplied buffers passed to
// ``hkv_denoise_bind_arena`` must be aligned to at least this many
// bytes for the region; otherwise the bind is rejected with status
// 4. Internal arena buffers are emitted with ``alignas(...)`` matching
// these values, so ``allocate_arenas=true`` builds always satisfy the
// constraint.
const size_t hkv_denoise_arena_alignments[hkv_denoise_num_arena_buffers] = {
    [hkv_denoise_arena_sram] = 16,
    [hkv_denoise_arena_const_mram] = 16,
};

// Internal arena buffers. Writable arenas (scratch, persistent, and
// staged-constant runtime copies) are uninitialized BSS-backed
// storage; cold-constant arenas are read-only blobs whose bytes are
// initialised in hkv_denoise_constants.c.
alignas(16) static HKV_DENOISE_PUT_IN_SRAM int8_t hkv_denoise_arena_sram_buffer[hkv_denoise_arena_sram_size];

extern const HKV_DENOISE_PUT_IN_MRAM_INIT int8_t hkv_denoise_arena_const_mram__blob[11892];

const void * const hkv_denoise_arena_buffers[hkv_denoise_num_arena_buffers] = {
    [hkv_denoise_arena_sram] = hkv_denoise_arena_sram_buffer,
    // Cold constant arena: kernels read directly from the in-image blob.
    [hkv_denoise_arena_const_mram] = hkv_denoise_arena_const_mram__blob,
};


//── Model Input/Output ────────────────────────────────────────────────────────

const hkv_denoise_tensor_ident_t hkv_denoise_inputs_id[hkv_denoise_num_inputs] = {
    hkv_denoise_tensor_0,
};

const hkv_denoise_tensor_ident_t hkv_denoise_outputs_id[hkv_denoise_num_outputs] = {
    hkv_denoise_tensor_66,
};

const int32_t hkv_denoise_inputs_len[hkv_denoise_num_inputs] = {
    256,
};

const int32_t hkv_denoise_inputs_zero_point[hkv_denoise_num_inputs] = {
    0,
};

const float hkv_denoise_inputs_scale[hkv_denoise_num_inputs] = {
    1,
};

const int32_t hkv_denoise_outputs_len[hkv_denoise_num_outputs] = {
    256,
};

const int32_t hkv_denoise_outputs_zero_point[hkv_denoise_num_outputs] = {
    0,
};

const float hkv_denoise_outputs_scale[hkv_denoise_num_outputs] = {
    1,
};

//── Model Tensors ─────────────────────────────────────────────────────────────

// Tensor descriptors. Uniform shape: every tensor lives in an arena
// slot, addressed by ``(region, offset)``.
const hkv_denoise_tensor_descriptor_t hkv_denoise_tensor_descriptors[hkv_denoise_num_tensors] = {
    [hkv_denoise_tensor_0] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 1024,
    },
    [hkv_denoise_tensor_1] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 32,
        .size = 4,
    },
    [hkv_denoise_tensor_2] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 80,
        .size = 4,
    },
    [hkv_denoise_tensor_3] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 128,
        .size = 32,
    },
    [hkv_denoise_tensor_4] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 384,
        .size = 32,
    },
    [hkv_denoise_tensor_5] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 544,
        .size = 16,
    },
    [hkv_denoise_tensor_6] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 688,
        .size = 32,
    },
    [hkv_denoise_tensor_7] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 1248,
        .size = 64,
    },
    [hkv_denoise_tensor_8] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 1760,
        .size = 64,
    },
    [hkv_denoise_tensor_9] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 2336,
        .size = 32,
    },
    [hkv_denoise_tensor_10] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 2880,
        .size = 64,
    },
    [hkv_denoise_tensor_11] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 4480,
        .size = 96,
    },
    [hkv_denoise_tensor_12] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 5248,
        .size = 96,
    },
    [hkv_denoise_tensor_13] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 6496,
        .size = 48,
    },
    [hkv_denoise_tensor_14] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 7696,
        .size = 96,
    },
    [hkv_denoise_tensor_15] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 10864,
        .size = 128,
    },
    [hkv_denoise_tensor_16] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 0,
        .size = 28,
    },
    [hkv_denoise_tensor_17] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 48,
        .size = 28,
    },
    [hkv_denoise_tensor_18] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 160,
        .size = 224,
    },
    [hkv_denoise_tensor_19] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 1312,
        .size = 448,
    },
    [hkv_denoise_tensor_20] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 4576,
        .size = 672,
    },
    [hkv_denoise_tensor_21] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 11888,
        .size = 4,
    },
    [hkv_denoise_tensor_22] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 96,
        .size = 32,
    },
    [hkv_denoise_tensor_23] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 416,
        .size = 128,
    },
    [hkv_denoise_tensor_24] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 560,
        .size = 128,
    },
    [hkv_denoise_tensor_25] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 736,
        .size = 512,
    },
    [hkv_denoise_tensor_26] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 1824,
        .size = 512,
    },
    [hkv_denoise_tensor_27] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 2368,
        .size = 512,
    },
    [hkv_denoise_tensor_28] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 2944,
        .size = 1536,
    },
    [hkv_denoise_tensor_29] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 5344,
        .size = 1152,
    },
    [hkv_denoise_tensor_30] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 6544,
        .size = 1152,
    },
    [hkv_denoise_tensor_31] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 7792,
        .size = 3072,
    },
    [hkv_denoise_tensor_32] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 10992,
        .size = 896,
    },
    [hkv_denoise_tensor_35] = {
        .type = hkv_denoise_tensor_type_constant,
        .region = hkv_denoise_arena_const_mram,
        .offset = 720,
        .size = 4,
    },
    [hkv_denoise_tensor_37] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 1024,
    },
    [hkv_denoise_tensor_38] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 1024,
        .size = 1024,
    },
    [hkv_denoise_tensor_39] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 1024,
    },
    [hkv_denoise_tensor_40] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 1024,
        .size = 8192,
    },
    [hkv_denoise_tensor_41] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 9216,
        .size = 8192,
    },
    [hkv_denoise_tensor_42] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 32,
    },
    [hkv_denoise_tensor_43] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 32,
        .size = 16,
    },
    [hkv_denoise_tensor_44] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 32,
    },
    [hkv_denoise_tensor_45] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 32,
        .size = 32,
    },
    [hkv_denoise_tensor_46] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 32,
    },
    [hkv_denoise_tensor_47] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 32,
        .size = 8192,
    },
    [hkv_denoise_tensor_48] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 8224,
        .size = 16384,
    },
    [hkv_denoise_tensor_49] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 24608,
        .size = 16384,
    },
    [hkv_denoise_tensor_50] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 64,
    },
    [hkv_denoise_tensor_51] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 64,
        .size = 32,
    },
    [hkv_denoise_tensor_52] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 64,
    },
    [hkv_denoise_tensor_53] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 64,
        .size = 64,
    },
    [hkv_denoise_tensor_54] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 64,
    },
    [hkv_denoise_tensor_55] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 64,
        .size = 16384,
    },
    [hkv_denoise_tensor_56] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 16448,
        .size = 24576,
    },
    [hkv_denoise_tensor_57] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 41024,
        .size = 24576,
    },
    [hkv_denoise_tensor_58] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 96,
    },
    [hkv_denoise_tensor_59] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 96,
        .size = 48,
    },
    [hkv_denoise_tensor_60] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 96,
    },
    [hkv_denoise_tensor_61] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 96,
        .size = 96,
    },
    [hkv_denoise_tensor_62] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 96,
    },
    [hkv_denoise_tensor_63] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 96,
        .size = 24576,
    },
    [hkv_denoise_tensor_64] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 24672,
        .size = 32768,
    },
    [hkv_denoise_tensor_65] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 1024,
    },
    [hkv_denoise_tensor_66] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 0,
        .size = 1024,
    },
    [hkv_denoise_tensor_conv_2d_28_scratch] = {
        .type = hkv_denoise_tensor_type_scratch,
        .region = hkv_denoise_arena_sram,
        .offset = 1024,
        .size = 896,
    },
};