/******************************************************************************
 * @file        hkv_denoise_relu_17.c
 * @brief       Autogenerated AOT relu kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '17' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_relu_17.h"

static const int32_t relu_17_output_size = 16;

int32_t
hkv_denoise_relu_17_init(
    hkv_denoise_model_context_t *ctx
) {
    return 0;
}


int32_t
hkv_denoise_relu_17_run(
    hkv_denoise_model_context_t *ctx
) {
    const float* __restrict input = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_53];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_denoise_tensor_54];

    return arm_nn_activation_f32(
        input,
        output,
        relu_17_output_size,
        ARM_NN_FLT_ACT_RELU,
        0
    );
}
