/******************************************************************************
 * @file        hkv_denoise_depthwise_conv_2d_4.c
 * @brief       Autogenerated AOT depthwise_conv_2d kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '4' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_depthwise_conv_2d_4.h"

// Input dimensions: input shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims depthwise_conv_2d_4_input_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 8
};

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_4_filter_dims = {
    .n = 1, .h = 1,
    .w = 7, .c = 8
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_4_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 8
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_4_output_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 8
};


// Scratch buffer context
static cmsis_nn_context depthwise_conv_2d_4_ctx = {
    .buf = NULL,
    .size = 0,
};



static const cmsis_nn_dw_conv_params_f32 depthwise_conv_2d_4_params = {
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 3,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = 0.0f,
    .activation.max = 6.0f,
};

int32_t
hkv_denoise_depthwise_conv_2d_4_init(
    hkv_denoise_model_context_t *ctx
) {

    (void)ctx;
    depthwise_conv_2d_4_ctx.buf = NULL;
    depthwise_conv_2d_4_ctx.size = 0;

    return 0;
}


int32_t
hkv_denoise_depthwise_conv_2d_4_run(
    hkv_denoise_model_context_t *ctx
) {
    const float* __restrict input = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_40];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_denoise_tensor_41];
    return arm_depthwise_conv_f32(
        &depthwise_conv_2d_4_ctx,
        &depthwise_conv_2d_4_params,
        &depthwise_conv_2d_4_input_dims,
        input,
        &depthwise_conv_2d_4_filter_dims,
        (float *)ctx->tensor_ptrs[hkv_denoise_tensor_18],
        &depthwise_conv_2d_4_bias_dims,
        (float *)ctx->tensor_ptrs[hkv_denoise_tensor_4],
        &depthwise_conv_2d_4_output_dims,
        output,
        ARM_NN_LAYOUT_NHWC
    );

}