/******************************************************************************
 * @file        hkv_denoise_model.c
 * @brief       Autogenerated heliaAOT model
 * @details     Model: hkv_denoise - MLIR Converted.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_operators.h"
#include "hkv_denoise_model.h"

//── Table-driven operator dispatch ────────────────────────────────────────────
//
// Every operator exposes the uniform ``(ctx) -> status`` ABI and resolves its
// own tensor I/O internally from ``ctx->tensor_ptrs``. The model therefore
// marshals nothing: ``model_init`` / ``model_run`` simply iterate one rodata
// table instead of emitting an unrolled call site per operator. This collapses
// dispatcher code size (critical for large unrolled RNN graphs) while
// preserving the exact per-operator callback contract used below.
//
// The loop body is the single integration chokepoint for long-term hooks: an
// RTOS scheduler can yield between entries, and per-layer PMU counters can be
// sampled around ``e->run(ctx)`` via the existing ``ctx->callback`` seam, which
// still receives the stable AIR operator id (``e->id``).

typedef int32_t (*hkv_denoise_op_fn)(hkv_denoise_model_context_t *ctx);

typedef struct {
    hkv_denoise_op_fn init; // Per-operator init hook
    hkv_denoise_op_fn run;  // Per-operator run hook (resolves its own I/O)
    int32_t id;              // Stable AIR operator id, forwarded to callbacks
} hkv_denoise_op_entry_t;

// Operator dispatch table — one rodata entry per operator, in execution order.
// Operators with no per-instance init record a NULL init slot; the init loop
// skips the call while still firing the init callback contract.
static const hkv_denoise_op_entry_t hkv_denoise_op_table[30] = {
    { hkv_denoise_reshape_0_init, hkv_denoise_reshape_0_run, 0 },
    { hkv_denoise_depthwise_conv_2d_1_init, hkv_denoise_depthwise_conv_2d_1_run, 1 },
    { hkv_denoise_depthwise_conv_2d_2_init, hkv_denoise_depthwise_conv_2d_2_run, 2 },
    { hkv_denoise_conv_2d_3_init, hkv_denoise_conv_2d_3_run, 3 },
    { hkv_denoise_depthwise_conv_2d_4_init, hkv_denoise_depthwise_conv_2d_4_run, 4 },
    { hkv_denoise_mean_5_init, hkv_denoise_mean_5_run, 5 },
    { hkv_denoise_conv_2d_6_init, hkv_denoise_conv_2d_6_run, 6 },
    { hkv_denoise_conv_2d_7_init, hkv_denoise_conv_2d_7_run, 7 },
    { hkv_denoise_minimum_8_init, hkv_denoise_minimum_8_run, 8 },
    { hkv_denoise_relu_9_init, hkv_denoise_relu_9_run, 9 },
    { NULL, hkv_denoise_mul_10_run, 10 },
    { hkv_denoise_conv_2d_11_init, hkv_denoise_conv_2d_11_run, 11 },
    { hkv_denoise_depthwise_conv_2d_12_init, hkv_denoise_depthwise_conv_2d_12_run, 12 },
    { hkv_denoise_mean_13_init, hkv_denoise_mean_13_run, 13 },
    { hkv_denoise_conv_2d_14_init, hkv_denoise_conv_2d_14_run, 14 },
    { hkv_denoise_conv_2d_15_init, hkv_denoise_conv_2d_15_run, 15 },
    { hkv_denoise_minimum_16_init, hkv_denoise_minimum_16_run, 16 },
    { hkv_denoise_relu_17_init, hkv_denoise_relu_17_run, 17 },
    { NULL, hkv_denoise_mul_18_run, 18 },
    { hkv_denoise_conv_2d_19_init, hkv_denoise_conv_2d_19_run, 19 },
    { hkv_denoise_depthwise_conv_2d_20_init, hkv_denoise_depthwise_conv_2d_20_run, 20 },
    { hkv_denoise_mean_21_init, hkv_denoise_mean_21_run, 21 },
    { hkv_denoise_conv_2d_22_init, hkv_denoise_conv_2d_22_run, 22 },
    { hkv_denoise_conv_2d_23_init, hkv_denoise_conv_2d_23_run, 23 },
    { hkv_denoise_minimum_24_init, hkv_denoise_minimum_24_run, 24 },
    { hkv_denoise_relu_25_init, hkv_denoise_relu_25_run, 25 },
    { NULL, hkv_denoise_mul_26_run, 26 },
    { hkv_denoise_conv_2d_27_init, hkv_denoise_conv_2d_27_run, 27 },
    { hkv_denoise_conv_2d_28_init, hkv_denoise_conv_2d_28_run, 28 },
    { hkv_denoise_reshape_29_init, hkv_denoise_reshape_29_run, 29 },
};

int32_t hkv_denoise_model_init(
    hkv_denoise_model_context_t *ctx
) {
    if (ctx == NULL) {
        return hkv_denoise_status_null_context;
    }
    int32_t status = 0;

    status = hkv_denoise_context_init(ctx);
    if (status != 0) {
        return status;
    }

    // Drive every operator's init hook through the dispatch table. The callback
    // contract (init_started / init_finished with the AIR op id) is preserved
    // exactly; only the unrolled call sites are collapsed into this loop.
    for (uint32_t i = 0; i < 30; ++i) {
        const hkv_denoise_op_entry_t *e = &hkv_denoise_op_table[i];
        if (ctx->callback) { ctx->callback(e->id, hkv_denoise_op_state_init_started, status, ctx->user_data); }
        if (e->init) { status = e->init(ctx); }
        if (ctx->callback) { ctx->callback(e->id, hkv_denoise_op_state_init_finished, status, ctx->user_data); }
        if (status != 0) { return status; }
    }

    // All operator inits succeeded — arm the lifecycle latch so
    // model_run accepts this context.
    ctx->_lifecycle_state = 1;

    return status;
}

int32_t hkv_denoise_model_run(
    hkv_denoise_model_context_t *ctx
) {
    if (ctx == NULL) {
        return hkv_denoise_status_null_context;
    }

    // Reject runs when model_init was never called or failed.
    if (ctx->_lifecycle_state != 1) {
        return hkv_denoise_status_not_initialized;
    }

    int32_t status = 0;

    // Drive every operator's run hook through the dispatch table. Each operator
    // resolves its own typed tensor pointers from the context, keeping the loop
    // uniform. This is the single seam for RTOS scheduling / PMU sampling.
    for (uint32_t i = 0; i < 30; ++i) {
        const hkv_denoise_op_entry_t *e = &hkv_denoise_op_table[i];
        if (ctx->callback) { ctx->callback(e->id, hkv_denoise_op_state_run_started, status, ctx->user_data); }
        status = e->run(ctx);
        if (ctx->callback) { ctx->callback(e->id, hkv_denoise_op_state_run_finished, status, ctx->user_data); }
        if (status != 0) { return status; }
    }
    return status;
}