/******************************************************************************
 * @file        hkv_denoise_mul_18.c
 * @brief       Autogenerated AOT mul kernel
 * @details     This file was generated by heliaAOT v0.21.0 on 2026-09-08.
 *              This kernel represents node '18' in the corresponding graph.
 * @date        2026-09-08
 * @version     0.21.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_denoise_common.h"
#include "hkv_denoise_mul_18.h"

static const cmsis_nn_dims mul_18_input1_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 16
};
static const cmsis_nn_dims mul_18_input2_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 16
};
static const cmsis_nn_dims mul_18_output_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 16
};

int32_t hkv_denoise_mul_18_run(hkv_denoise_model_context_t *ctx) {
    const float* __restrict input1 = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_49];
    const float* __restrict input2 = (const float*)ctx->tensor_ptrs[hkv_denoise_tensor_54];
    float* __restrict output = (float*)ctx->tensor_ptrs[hkv_denoise_tensor_55];
    return arm_elementwise_mul_broadcast_f32(
        input1, &mul_18_input1_dims,
        input2, &mul_18_input2_dims,
        output, &mul_18_output_dims,
        -FLT_MAX, FLT_MAX
    );
}
