/******************************************************************************
 * @file        hkv_segmentation_test_case.h
 * @brief       Autogenerated heliaAOT test case
 * @details     This file is used to verify the correctness of the module.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include "hkv_segmentation_common.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initialize unit test
 *
 * @return 0 on SUCCESS
 */
int32_t hkv_segmentation_test_case_init(void);


/**
 * @brief Run the unit test
 *
 * @return 0 on SUCCESS
 */
int32_t hkv_segmentation_test_case_run(void);

#ifdef __cplusplus
}
#endif