/******************************************************************************
 * @file        hkv_segmentation_model.h
 * @brief       Autogenerated heliaAOT model
 * @details     Model: hkv_segmentation - MLIR Converted.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include <stdint.h>
#include "hkv_segmentation_tensors.h"
#include "hkv_segmentation_context.h"

#ifdef __cplusplus
extern "C" {
#endif


/**
 * @brief heliaAOT model init
 *
 * Single entry point that wires up the context, hydrates any
 * staged-constant arenas (via the weak
 * ``hkv_segmentation_hydrate_constants``), and runs every operator's
 * per-call init hook. Callers using ``model_init`` as the entry
 * point must NOT also call ``context_init`` separately: a second
 * ``context_init`` would clear both the lifecycle latch and the
 * hydration latch and a subsequent ``model_run`` would reject the
 * call.
 *
 * @param[in] ctx  The context struct
 *
 * @return ``hkv_segmentation_status_ok`` (0) on success.
 *         ``hkv_segmentation_status_null_context`` (13) if @p ctx is
 *         NULL.
 *         Any non-zero code forwarded from
 *         ``hkv_segmentation_context_init`` (e.g. 10 for an unbound
 *         arena), from ``hkv_segmentation_hydrate_constants`` for
 *         staged-constant builds, or from an operator's _init
 *         hook.
 *
 * @note Not thread-safe. See ``hkv_segmentation_context_init``.
 */
int32_t hkv_segmentation_model_init(
    hkv_segmentation_model_context_t *ctx
);

/**
 * @brief heliaAOT model run
 *
 * @param[in] ctx  The context struct
 *
 * @return ``hkv_segmentation_status_ok`` (0) on success; non-zero on
 *         failure.
 *         ``hkv_segmentation_status_null_context`` (13) if @p ctx is
 *         NULL.
 *         ``hkv_segmentation_status_not_initialized`` (14) if
 *         ``hkv_segmentation_model_init`` was never called or failed.
 *
 * @note Not thread-safe. See ``hkv_segmentation_context_init``.
 */
int32_t hkv_segmentation_model_run(
    hkv_segmentation_model_context_t *ctx
);

#ifdef __cplusplus
}
#endif