/******************************************************************************
 * @file        hkv_segmentation_tensors.h
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// ABI guard fingerprint for the generated arena layout.
//
// SHA-256(role|memory|source_memory|size|alignment|is_staged) over
// every region in region_id order, truncated to 16 hex chars. Stays
// stable across re-plans of the same model and changes whenever any
// region's role / memory residency / size / alignment / staged
// status changes. Downstream binaries that hard-code arena region
// IDs can validate this matches the planner that built their loader
// before binding arenas.
#define HKV_SEGMENTATION_PLAN_HASH "e7e860ab99fa70a1"

//── Tensor/Memory Definitions ─────────────────────────────────────────────────

// Tensor ID enumeration
typedef enum {
    hkv_segmentation_tensor_0 = 0,
    hkv_segmentation_tensor_5 = 1,
    hkv_segmentation_tensor_7 = 2,
    hkv_segmentation_tensor_9 = 3,
    hkv_segmentation_tensor_11 = 4,
    hkv_segmentation_tensor_12 = 5,
    hkv_segmentation_tensor_13 = 6,
    hkv_segmentation_tensor_15 = 7,
    hkv_segmentation_tensor_17 = 8,
    hkv_segmentation_tensor_19 = 9,
    hkv_segmentation_tensor_20 = 10,
    hkv_segmentation_tensor_21 = 11,
    hkv_segmentation_tensor_23 = 12,
    hkv_segmentation_tensor_24 = 13,
    hkv_segmentation_tensor_25 = 14,
    hkv_segmentation_tensor_26 = 15,
    hkv_segmentation_tensor_28 = 16,
    hkv_segmentation_tensor_30 = 17,
    hkv_segmentation_tensor_31 = 18,
    hkv_segmentation_tensor_32 = 19,
    hkv_segmentation_tensor_34 = 20,
    hkv_segmentation_tensor_36 = 21,
    hkv_segmentation_tensor_38 = 22,
    hkv_segmentation_tensor_39 = 23,
    hkv_segmentation_tensor_40 = 24,
    hkv_segmentation_tensor_41 = 25,
    hkv_segmentation_tensor_42 = 26,
    hkv_segmentation_tensor_43 = 27,
    hkv_segmentation_tensor_44 = 28,
    hkv_segmentation_tensor_45 = 29,
    hkv_segmentation_tensor_46 = 30,
    hkv_segmentation_tensor_47 = 31,
    hkv_segmentation_tensor_48 = 32,
    hkv_segmentation_tensor_49 = 33,
    hkv_segmentation_tensor_50 = 34,
    hkv_segmentation_tensor_51 = 35,
    hkv_segmentation_tensor_52 = 36,
    hkv_segmentation_tensor_53 = 37,
    hkv_segmentation_tensor_54 = 38,
    hkv_segmentation_tensor_55 = 39,
    hkv_segmentation_tensor_56 = 40,
    hkv_segmentation_tensor_57 = 41,
    hkv_segmentation_tensor_58 = 42,
    hkv_segmentation_tensor_59 = 43,
    hkv_segmentation_tensor_60 = 44,
    hkv_segmentation_tensor_61 = 45,
    hkv_segmentation_tensor_62 = 46,
    hkv_segmentation_tensor_63 = 47,
    hkv_segmentation_tensor_64 = 48,
    hkv_segmentation_tensor_65 = 49,
    hkv_segmentation_tensor_66 = 50,
    hkv_segmentation_tensor_67 = 51,
    hkv_segmentation_tensor_68 = 52,
    hkv_segmentation_tensor_69 = 53,
    hkv_segmentation_tensor_depthwise_conv_2d_1_scratch = 54,
    hkv_segmentation_tensor_depthwise_conv_2d_1_weight_sum = 55,
    hkv_segmentation_tensor_depthwise_conv_2d_2_scratch = 56,
    hkv_segmentation_tensor_depthwise_conv_2d_2_weight_sum = 57,
    hkv_segmentation_tensor_conv_2d_3_weight_sum = 58,
    hkv_segmentation_tensor_conv_2d_3_multiplier = 59,
    hkv_segmentation_tensor_conv_2d_3_shift = 60,
    hkv_segmentation_tensor_depthwise_conv_2d_4_multiplier = 61,
    hkv_segmentation_tensor_depthwise_conv_2d_4_shift = 62,
    hkv_segmentation_tensor_conv_2d_6_weight_sum = 63,
    hkv_segmentation_tensor_conv_2d_6_multiplier = 64,
    hkv_segmentation_tensor_conv_2d_6_shift = 65,
    hkv_segmentation_tensor_conv_2d_7_weight_sum = 66,
    hkv_segmentation_tensor_conv_2d_7_multiplier = 67,
    hkv_segmentation_tensor_conv_2d_7_shift = 68,
    hkv_segmentation_tensor_conv_2d_11_weight_sum = 69,
    hkv_segmentation_tensor_conv_2d_11_multiplier = 70,
    hkv_segmentation_tensor_conv_2d_11_shift = 71,
    hkv_segmentation_tensor_depthwise_conv_2d_12_multiplier = 72,
    hkv_segmentation_tensor_depthwise_conv_2d_12_shift = 73,
    hkv_segmentation_tensor_conv_2d_14_weight_sum = 74,
    hkv_segmentation_tensor_conv_2d_14_multiplier = 75,
    hkv_segmentation_tensor_conv_2d_14_shift = 76,
    hkv_segmentation_tensor_conv_2d_15_weight_sum = 77,
    hkv_segmentation_tensor_conv_2d_15_multiplier = 78,
    hkv_segmentation_tensor_conv_2d_15_shift = 79,
    hkv_segmentation_tensor_conv_2d_19_weight_sum = 80,
    hkv_segmentation_tensor_conv_2d_19_multiplier = 81,
    hkv_segmentation_tensor_conv_2d_19_shift = 82,
    hkv_segmentation_tensor_depthwise_conv_2d_20_multiplier = 83,
    hkv_segmentation_tensor_depthwise_conv_2d_20_shift = 84,
    hkv_segmentation_tensor_conv_2d_22_weight_sum = 85,
    hkv_segmentation_tensor_conv_2d_22_multiplier = 86,
    hkv_segmentation_tensor_conv_2d_22_shift = 87,
    hkv_segmentation_tensor_conv_2d_23_weight_sum = 88,
    hkv_segmentation_tensor_conv_2d_23_multiplier = 89,
    hkv_segmentation_tensor_conv_2d_23_shift = 90,
    hkv_segmentation_tensor_conv_2d_27_weight_sum = 91,
    hkv_segmentation_tensor_conv_2d_27_multiplier = 92,
    hkv_segmentation_tensor_conv_2d_27_shift = 93,
    hkv_segmentation_tensor_conv_2d_28_scratch = 94,
    hkv_segmentation_tensor_conv_2d_28_weight_sum = 95,
    hkv_segmentation_tensor_conv_2d_28_multiplier = 96,
    hkv_segmentation_tensor_conv_2d_28_shift = 97,
    hkv_segmentation_num_tensors = 98
} hkv_segmentation_tensor_ident_t;

// Input/Output descriptors
typedef struct {
    hkv_segmentation_tensor_ident_t id;
    int8_t *data;  // pointer into context tensor_ptrs[]
    size_t size;  // Tensor size in bytes
    int32_t zero_point;  // Quantization zero-point
    float scale;  // Quantization scale
} hkv_segmentation_tensor_io_t;

// Memory arenas enumeration. Region IDs come from the render plan's
// deterministic ordering policy (scratch < persistent < constant;
// within-role: memory.name ascending) so two re-plans of the same
// model produce identical enum values. The PLAN_HASH macro above
// fingerprints the same ordering for ABI drift detection.
typedef enum {
    hkv_segmentation_arena_dtcm = 0,
    hkv_segmentation_arena_const_mram = 1,
    hkv_segmentation_num_arena_buffers = 2
} hkv_segmentation_arena_region_t;

// Runtime status codes returned by the generated C API.
//
// Numeric values are organized into namespaced ranges so callers can
// disambiguate which API surface produced an error without
// out-of-band context:
//
//   * 0          : success.
//   * 1..4       : per-region ``hkv_segmentation_bind_arena`` failures
//                  (also forwarded by ``hkv_segmentation_bind_arenas`` for
//                  per-region issues).
//   * 10..12     : ``hkv_segmentation_context_init`` /
//                  ``hkv_segmentation_hydrate_constants`` preconditions.
//   * 13         : common ``ctx == NULL`` precondition failure
//                  shared across every public entry point.
//   * 14         : lifecycle precondition (``model_run`` before
//                  successful ``model_init``).
//   * 100..109   : ``hkv_segmentation_bind_arenas`` bulk-argument failures.
//   * 200..209   : ``hkv_segmentation_model_run`` precondition failures
//                  (e.g. hydration latch).
//
// Code that needs to inspect status values should prefer the
// enumerator names below; raw literals are reserved for snapshot /
// ABI-stability tests.
typedef enum {
    hkv_segmentation_status_ok = 0,

    // bind_arena() per-region failures.
    hkv_segmentation_status_bind_unknown_region   = 1,
    hkv_segmentation_status_bind_null_buffer      = 2,
    hkv_segmentation_status_bind_undersized       = 3,
    hkv_segmentation_status_bind_misaligned       = 4,

    // context_init() / hydrate_constants() failures.
    hkv_segmentation_status_context_arena_unbound = 10,
    // hydrate_constants() called on a context whose arena_buffers
    // table is still NULL (i.e. before context_init succeeded).
    hkv_segmentation_status_hydrate_uninited_context = 11,
    hkv_segmentation_status_hydrate_null_blob     = 12,

    // Common precondition failure (any public entry point).
    hkv_segmentation_status_null_context          = 13,
    // model_run() called before model_init() succeeded.
    hkv_segmentation_status_not_initialized       = 14,

    // bind_arenas() bulk-argument failures (per-region failures
    // forward the 1..4 range above).
    hkv_segmentation_status_bind_bulk_null_argument = 100,
    hkv_segmentation_status_bind_bulk_wrong_count   = 101,

    // model_run() precondition failures.
    hkv_segmentation_status_hydration_required = 200,
} hkv_segmentation_status_t;

// Tensor categories
typedef enum {
    hkv_segmentation_tensor_type_constant,
    hkv_segmentation_tensor_type_persistent,
    hkv_segmentation_tensor_type_scratch,
} hkv_segmentation_tensor_type_t;

// Tensor descriptors. Every tensor — scratch, persistent, or
// constant — is bound to an arena slot. The kernel-visible address
// is always ``arena_buffers[region] + offset``. There are no
// per-tensor C symbols.
typedef struct {
    hkv_segmentation_tensor_type_t type;
    hkv_segmentation_arena_region_t region;
    size_t offset;
    size_t size;
} hkv_segmentation_tensor_descriptor_t;

//── Memory Arenas ─────────────────────────────────────────────────────────────

#define hkv_segmentation_arena_dtcm_size  22560
#define hkv_segmentation_arena_dtcm_alignment  16
#define hkv_segmentation_arena_const_mram_size  9568
#define hkv_segmentation_arena_const_mram_alignment  16

extern const void * const hkv_segmentation_arena_buffers[hkv_segmentation_num_arena_buffers];
/**
 * @brief Per-region capacity of every arena, in bytes.
 *
 * This table has **two** meanings, depending on the arena role:
 *
 *  - **Scratch / persistent / staged-constant** arenas:
 *    ``arena_sizes[region]`` is the runtime buffer size the caller
 *    must provide. In internal-arena mode the generated
 *    ``hkv_segmentation_arena_*_buffer`` storage is exactly this size.
 *    In external-arena mode (``allocate_arenas=false``) the caller
 *    must bind a buffer at least this large via
 *    ``hkv_segmentation_bind_arena``.
 *
 *  - **Cold-constant** arenas (``source_memory == memory``):
 *    ``arena_sizes[region]`` is the size of the cold blob in flash
 *    (or equivalent read-only memory). Kernels read the blob in
 *    place; there is no separate runtime buffer. In external-arena
 *    mode the caller must bind this region to a pointer to the
 *    cold blob itself (or to the matching ``__blob.bin`` sidecar
 *    when the C source omits the literal).
 *
 * Use ``hkv_segmentation_tensor_descriptors[i].region`` to find which
 * arena a given tensor lives in, and the corresponding
 * ``arena_sizes[region]`` for its containing arena's capacity.
 */
extern const size_t hkv_segmentation_arena_sizes[hkv_segmentation_num_arena_buffers];

/**
 * @brief Per-region alignment requirement (bytes) for caller-supplied
 *        arena buffers in external-arena mode.
 *
 * Each value is a power of two and reflects the strictest alignment
 * required by any tensor placed in that arena (platform floor or
 * per-arena ``arena_alignment`` override, whichever is larger).
 * ``hkv_segmentation_bind_arena`` returns status 4 if a buffer pointer
 * does not satisfy the corresponding entry. Internal-arena builds
 * (`allocate_arenas=true`) emit each buffer with
 * ``alignas(...)`` matching this table, so the constraint is
 * automatically met.
 */
extern const size_t hkv_segmentation_arena_alignments[hkv_segmentation_num_arena_buffers];

//── Model Input/Output ────────────────────────────────────────────────────────

#define hkv_segmentation_num_inputs 1
#define hkv_segmentation_num_outputs 1

#define hkv_segmentation_input_0_size (256)
#define hkv_segmentation_output_0_size (1024)

extern const hkv_segmentation_tensor_ident_t hkv_segmentation_inputs_id[hkv_segmentation_num_inputs];
extern const hkv_segmentation_tensor_ident_t hkv_segmentation_outputs_id[hkv_segmentation_num_outputs];
extern const int32_t hkv_segmentation_inputs_len[hkv_segmentation_num_inputs];
extern const int32_t hkv_segmentation_inputs_zero_point[hkv_segmentation_num_inputs];
extern const float hkv_segmentation_inputs_scale[hkv_segmentation_num_inputs];
extern const int32_t hkv_segmentation_outputs_len[hkv_segmentation_num_outputs];
extern const int32_t hkv_segmentation_outputs_zero_point[hkv_segmentation_num_outputs];
extern const float hkv_segmentation_outputs_scale[hkv_segmentation_num_outputs];

//── Model Tensors ─────────────────────────────────────────────────────────────

// Per-tensor byte size lives on the descriptor (``hkv_segmentation_tensor_descriptors[i].size``);
// per-tensor element count is the descriptor size divided by the
// element width. Public ``_size`` macros are emitted only for model
// inputs/outputs above, where they are part of the stable I/O API.

// Tensor descriptors
extern const hkv_segmentation_tensor_descriptor_t hkv_segmentation_tensor_descriptors[hkv_segmentation_num_tensors];

#ifdef __cplusplus
}
#endif