/******************************************************************************
 * @file        hkv_segmentation_depthwise_conv_2d_2.c
 * @brief       Autogenerated AOT depthwise_conv_2d kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '2' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_depthwise_conv_2d_2.h"

// Input dimensions: input shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims depthwise_conv_2d_2_input_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 1
};

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_2_filter_dims = {
    .n = 1, .h = 1,
    .w = 7, .c = 1
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_2_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 1
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_2_output_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 1
};

// Quantization parameters (per-channel quantization)
static const int32_t depthwise_conv_2d_2_multiplier[1] = {
    1283879467
};
static const int32_t depthwise_conv_2d_2_shift[1] = {
    -6
};

static const int32_t depthwise_conv_2d_2_input_zero_point = 3;
static const int32_t depthwise_conv_2d_2_output_zero_point = -128;

// Scratch buffer context
static cmsis_nn_context depthwise_conv_2d_2_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context depthwise_conv_2d_2_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};

const cmsis_nn_per_channel_quant_params depthwise_conv_2d_2_quant_params = {
    .multiplier = (int32_t*)depthwise_conv_2d_2_multiplier,
    .shift = (int32_t*)depthwise_conv_2d_2_shift,
};

const cmsis_nn_dw_conv_params depthwise_conv_2d_2_params = {
    .input_offset = -depthwise_conv_2d_2_input_zero_point,
    .output_offset = depthwise_conv_2d_2_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 3,
    .padding.h = 0,
    .dilation.w = 1,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
hkv_segmentation_depthwise_conv_2d_2_init(
    hkv_segmentation_model_context_t *ctx
) {

    depthwise_conv_2d_2_ctx.buf = ctx->tensor_ptrs[hkv_segmentation_tensor_depthwise_conv_2d_2_scratch];
    depthwise_conv_2d_2_ctx.size = 3472;

    depthwise_conv_2d_2_weight_sum_ctx.buf = ctx->tensor_ptrs[hkv_segmentation_tensor_depthwise_conv_2d_2_weight_sum];
    depthwise_conv_2d_2_weight_sum_ctx.size = 4;

    // Kernel sums precomputed offline.
    return ARM_CMSIS_NN_SUCCESS;
}


int32_t
hkv_segmentation_depthwise_conv_2d_2_run(
    hkv_segmentation_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_40];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_41];


    return arm_depthwise_conv_s8_opt(
        &depthwise_conv_2d_2_ctx,
        &depthwise_conv_2d_2_weight_sum_ctx,
        &depthwise_conv_2d_2_params,
        &depthwise_conv_2d_2_quant_params,
        &depthwise_conv_2d_2_input_dims,
        input,
        &depthwise_conv_2d_2_filter_dims,
        (int8_t *)ctx->tensor_ptrs[hkv_segmentation_tensor_36],
        &depthwise_conv_2d_2_bias_dims,
        NULL,
        &depthwise_conv_2d_2_output_dims,
        output
    );

}