/******************************************************************************
 * @file        hkv_segmentation_tensors.c
 * @brief       Autogenerated tensor definitions
 * @details     Contains tensor definitions, arenas, and model I/O.
 * @date        2026-09-26
 * @version     0.23.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_tensors.h"


//── Memory Arenas ─────────────────────────────────────────────────────────────

const size_t hkv_segmentation_arena_sizes[hkv_segmentation_num_arena_buffers] = {
    [hkv_segmentation_arena_sram] = hkv_segmentation_arena_sram_size,
    [hkv_segmentation_arena_const_mram] = hkv_segmentation_arena_const_mram_size,
};

// Per-region alignment (bytes). Caller-supplied buffers passed to
// ``hkv_segmentation_bind_arena`` must be aligned to at least this many
// bytes for the region; otherwise the bind is rejected with status
// 4. Internal arena buffers are emitted with ``alignas(...)`` matching
// these values, so ``allocate_arenas=true`` builds always satisfy the
// constraint.
const size_t hkv_segmentation_arena_alignments[hkv_segmentation_num_arena_buffers] = {
    [hkv_segmentation_arena_sram] = 16,
    [hkv_segmentation_arena_const_mram] = 16,
};

// Internal arena buffers. Writable arenas (scratch, persistent, and
// staged-constant runtime copies) are uninitialized BSS-backed
// storage; cold-constant arenas are read-only blobs whose bytes are
// initialised in hkv_segmentation_constants.c.
alignas(16) static HKV_SEGMENTATION_PUT_IN_SRAM int8_t hkv_segmentation_arena_sram_buffer[hkv_segmentation_arena_sram_size];

extern const HKV_SEGMENTATION_PUT_IN_MRAM_INIT int8_t hkv_segmentation_arena_const_mram__blob[9596];

const void * const hkv_segmentation_arena_buffers[hkv_segmentation_num_arena_buffers] = {
    [hkv_segmentation_arena_sram] = hkv_segmentation_arena_sram_buffer,
    // Cold constant arena: kernels read directly from the in-image blob.
    [hkv_segmentation_arena_const_mram] = hkv_segmentation_arena_const_mram__blob,
};


//── Model Input/Output ────────────────────────────────────────────────────────

const hkv_segmentation_tensor_ident_t hkv_segmentation_inputs_id[hkv_segmentation_num_inputs] = {
    hkv_segmentation_tensor_0,
};

const hkv_segmentation_tensor_ident_t hkv_segmentation_outputs_id[hkv_segmentation_num_outputs] = {
    hkv_segmentation_tensor_69,
};

const int32_t hkv_segmentation_inputs_len[hkv_segmentation_num_inputs] = {
    256,
};

const int32_t hkv_segmentation_inputs_zero_point[hkv_segmentation_num_inputs] = {
    -13,
};

const float hkv_segmentation_inputs_scale[hkv_segmentation_num_inputs] = {
    0.07215825468301773,
};

const int32_t hkv_segmentation_outputs_len[hkv_segmentation_num_outputs] = {
    1024,
};

const int32_t hkv_segmentation_outputs_zero_point[hkv_segmentation_num_outputs] = {
    -128,
};

const float hkv_segmentation_outputs_scale[hkv_segmentation_num_outputs] = {
    0.00390625,
};

//── Model Tensors ─────────────────────────────────────────────────────────────

// Tensor descriptors. Uniform shape: every tensor lives in an arena
// slot, addressed by ``(region, offset)``.
const hkv_segmentation_tensor_descriptor_t hkv_segmentation_tensor_descriptors[hkv_segmentation_num_tensors] = {
    [hkv_segmentation_tensor_0] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 256,
    },
    [hkv_segmentation_tensor_1] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 0,
        .size = 16,
    },
    [hkv_segmentation_tensor_3] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 9584,
        .size = 12,
    },
    [hkv_segmentation_tensor_5] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 8416,
        .size = 1120,
    },
    [hkv_segmentation_tensor_7] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 6656,
        .size = 1280,
    },
    [hkv_segmentation_tensor_9] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 5760,
        .size = 512,
    },
    [hkv_segmentation_tensor_11] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 5056,
        .size = 512,
    },
    [hkv_segmentation_tensor_13] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 4448,
        .size = 224,
    },
    [hkv_segmentation_tensor_15] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 3296,
        .size = 768,
    },
    [hkv_segmentation_tensor_17] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2720,
        .size = 288,
    },
    [hkv_segmentation_tensor_19] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2288,
        .size = 288,
    },
    [hkv_segmentation_tensor_21] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1824,
        .size = 168,
    },
    [hkv_segmentation_tensor_23] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1152,
        .size = 384,
    },
    [hkv_segmentation_tensor_24] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1136,
        .size = 1,
    },
    [hkv_segmentation_tensor_25] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1136,
        .size = 1,
    },
    [hkv_segmentation_tensor_26] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1136,
        .size = 1,
    },
    [hkv_segmentation_tensor_28] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 816,
        .size = 128,
    },
    [hkv_segmentation_tensor_30] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 592,
        .size = 128,
    },
    [hkv_segmentation_tensor_32] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 288,
        .size = 112,
    },
    [hkv_segmentation_tensor_34] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 80,
        .size = 16,
    },
    [hkv_segmentation_tensor_36] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 48,
        .size = 7,
    },
    [hkv_segmentation_tensor_38] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 16,
        .size = 7,
    },
    [hkv_segmentation_tensor_39] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 256,
    },
    [hkv_segmentation_tensor_40] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 256,
        .size = 256,
    },
    [hkv_segmentation_tensor_41] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 256,
    },
    [hkv_segmentation_tensor_42] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 256,
        .size = 4096,
    },
    [hkv_segmentation_tensor_43] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 4352,
        .size = 4096,
    },
    [hkv_segmentation_tensor_44] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 16,
    },
    [hkv_segmentation_tensor_45] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 16,
        .size = 8,
    },
    [hkv_segmentation_tensor_46] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 16,
    },
    [hkv_segmentation_tensor_47] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 16,
        .size = 16,
    },
    [hkv_segmentation_tensor_48] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 16,
    },
    [hkv_segmentation_tensor_49] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 16,
        .size = 4096,
    },
    [hkv_segmentation_tensor_50] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 4112,
        .size = 6144,
    },
    [hkv_segmentation_tensor_51] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 10256,
        .size = 6144,
    },
    [hkv_segmentation_tensor_52] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 24,
    },
    [hkv_segmentation_tensor_53] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 32,
        .size = 12,
    },
    [hkv_segmentation_tensor_54] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 24,
    },
    [hkv_segmentation_tensor_55] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 32,
        .size = 24,
    },
    [hkv_segmentation_tensor_56] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 24,
    },
    [hkv_segmentation_tensor_57] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 32,
        .size = 6144,
    },
    [hkv_segmentation_tensor_58] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 6176,
        .size = 8192,
    },
    [hkv_segmentation_tensor_59] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 14368,
        .size = 8192,
    },
    [hkv_segmentation_tensor_60] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 32,
    },
    [hkv_segmentation_tensor_61] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 32,
        .size = 16,
    },
    [hkv_segmentation_tensor_62] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 32,
    },
    [hkv_segmentation_tensor_63] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 32,
        .size = 32,
    },
    [hkv_segmentation_tensor_64] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 32,
    },
    [hkv_segmentation_tensor_65] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 32,
        .size = 8192,
    },
    [hkv_segmentation_tensor_66] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 8224,
        .size = 10240,
    },
    [hkv_segmentation_tensor_67] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 1024,
    },
    [hkv_segmentation_tensor_68] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 1024,
    },
    [hkv_segmentation_tensor_69] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 1024,
        .size = 1024,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_1_scratch] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 512,
        .size = 3472,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_1_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 32,
        .size = 4,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_2_scratch] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 512,
        .size = 3472,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_2_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 64,
        .size = 4,
    },
    [hkv_segmentation_tensor_conv_2d_3_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 96,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_3_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 160,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_3_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 224,
        .size = 64,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_4_scratch] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 8448,
        .size = 3472,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_4_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 400,
        .size = 64,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_4_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 464,
        .size = 64,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_4_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 528,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_6_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 720,
        .size = 32,
    },
    [hkv_segmentation_tensor_conv_2d_6_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 752,
        .size = 32,
    },
    [hkv_segmentation_tensor_conv_2d_6_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 784,
        .size = 32,
    },
    [hkv_segmentation_tensor_conv_2d_7_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 944,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_7_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1008,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_7_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1072,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_11_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1536,
        .size = 96,
    },
    [hkv_segmentation_tensor_conv_2d_11_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1632,
        .size = 96,
    },
    [hkv_segmentation_tensor_conv_2d_11_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 1728,
        .size = 96,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_12_scratch] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 3472,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_12_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2000,
        .size = 96,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_12_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2096,
        .size = 96,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_12_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2192,
        .size = 96,
    },
    [hkv_segmentation_tensor_conv_2d_14_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2576,
        .size = 48,
    },
    [hkv_segmentation_tensor_conv_2d_14_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2624,
        .size = 48,
    },
    [hkv_segmentation_tensor_conv_2d_14_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 2672,
        .size = 48,
    },
    [hkv_segmentation_tensor_conv_2d_15_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 3008,
        .size = 96,
    },
    [hkv_segmentation_tensor_conv_2d_15_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 3104,
        .size = 96,
    },
    [hkv_segmentation_tensor_conv_2d_15_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 3200,
        .size = 96,
    },
    [hkv_segmentation_tensor_conv_2d_19_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 4064,
        .size = 128,
    },
    [hkv_segmentation_tensor_conv_2d_19_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 4192,
        .size = 128,
    },
    [hkv_segmentation_tensor_conv_2d_19_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 4320,
        .size = 128,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_20_scratch] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 0,
        .size = 3472,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_20_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 4672,
        .size = 128,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_20_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 4800,
        .size = 128,
    },
    [hkv_segmentation_tensor_depthwise_conv_2d_20_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 4928,
        .size = 128,
    },
    [hkv_segmentation_tensor_conv_2d_22_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 5568,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_22_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 5632,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_22_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 5696,
        .size = 64,
    },
    [hkv_segmentation_tensor_conv_2d_23_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 6272,
        .size = 128,
    },
    [hkv_segmentation_tensor_conv_2d_23_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 6400,
        .size = 128,
    },
    [hkv_segmentation_tensor_conv_2d_23_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 6528,
        .size = 128,
    },
    [hkv_segmentation_tensor_conv_2d_27_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 7936,
        .size = 160,
    },
    [hkv_segmentation_tensor_conv_2d_27_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 8096,
        .size = 160,
    },
    [hkv_segmentation_tensor_conv_2d_27_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 8256,
        .size = 160,
    },
    [hkv_segmentation_tensor_conv_2d_28_scratch] = {
        .type = hkv_segmentation_tensor_type_scratch,
        .region = hkv_segmentation_arena_sram,
        .offset = 1024,
        .size = 400,
    },
    [hkv_segmentation_tensor_conv_2d_28_weight_sum] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 9536,
        .size = 16,
    },
    [hkv_segmentation_tensor_conv_2d_28_multiplier] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 9552,
        .size = 16,
    },
    [hkv_segmentation_tensor_conv_2d_28_shift] = {
        .type = hkv_segmentation_tensor_type_constant,
        .region = hkv_segmentation_arena_const_mram,
        .offset = 9568,
        .size = 16,
    },
};