/******************************************************************************
 * @file        hkv_segmentation_kernels.c
 * @brief       Autogenerated heliaAOT shared operator kernels
 * @details     Shared kernel runtimes for elementwise ADD/MUL and per-channel int8 FULLY_CONNECTED nodes.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_kernels.h"

int32_t hkv_segmentation_kernel_mul_s8(
    hkv_segmentation_model_context_t *ctx,
    const hkv_segmentation_mul_desc_t *d
) {
    const int8_t* __restrict input1 = (const int8_t*)ctx->tensor_ptrs[d->input1_id];
    const int8_t* __restrict input2 = (const int8_t*)ctx->tensor_ptrs[d->input2_id];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[d->output_id];

    return arm_mul_s8(
        input1,
        &d->input1_dims,
        input2,
        &d->input2_dims,
        d->input1_offset,
        d->input2_offset,
        output,
        &d->output_dims,
        d->output_offset,
        d->output_multiplier,
        d->output_shift,
        d->activation_min,
        d->activation_max
    );
}
