/******************************************************************************
 * @file        hkv_segmentation_relu_9.c
 * @brief       Autogenerated AOT relu kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '9' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_relu_9.h"

// ReLU parameters
static const int32_t relu_9_output_size = 16;
static const int32_t relu_9_activation_min = -128;
static const int32_t relu_9_activation_max = 127;

// Quantization parameters
static const int32_t relu_9_input_zero_point = -128;
static const int32_t relu_9_output_zero_point = -128;
static const int32_t relu_9_output_multiplier = 1073741824;
static const int32_t relu_9_output_shift = 1;

int32_t
hkv_segmentation_relu_9_init(
    hkv_segmentation_model_context_t *ctx
) {
    return 0;
}


int32_t
hkv_segmentation_relu_9_run(
    hkv_segmentation_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_47];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_48];

    return arm_relu_generic_s8(
        input,
        relu_9_input_zero_point,
        relu_9_output_zero_point,
        relu_9_output_multiplier,
        relu_9_output_shift,
        relu_9_activation_min,
        relu_9_activation_max,
        output,
        relu_9_output_size
    );

}
