/******************************************************************************
 * @file        hkv_segmentation_test_case.c
 * @brief       Autogenerated heliaAOT test case
 * @details     This file is used to verify the correctness of the module.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include <stdlib.h>

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_model.h"
#include "hkv_segmentation_test_case.h"


//── Optional cycle counter probe ──────────────────────────────────────────────
// The E2E Corstone builds pre-include the CMSIS device header (ARMCM55.h /
// ARMCM4_FP.h), so DWT and the debug control block are visible here when the
// target exposes a cycle counter. We time only model_run() inside the
// iteration loop so the metric stays focused on dispatch + kernel execution
// rather than init or output verification.
//
// CMSIS 6 deprecates the CMSIS 5 ``CoreDebug`` spelling in favour of ``DCB``:
// 6.0.0 omitted it, while 6.1.0+ retains it as a deprecated alias. Prefer
// ``DCB`` and fall back to ``CoreDebug`` for compatible CMSIS layouts.
#if defined(DCB) && defined(DCB_DEMCR_TRCENA_Msk)
#define HKV_SEGMENTATION_TEST_DEMCR       (DCB->DEMCR)
#define HKV_SEGMENTATION_TEST_DEMCR_TRCENA DCB_DEMCR_TRCENA_Msk
#elif defined(CoreDebug) && defined(CoreDebug_DEMCR_TRCENA_Msk)
#define HKV_SEGMENTATION_TEST_DEMCR       (CoreDebug->DEMCR)
#define HKV_SEGMENTATION_TEST_DEMCR_TRCENA CoreDebug_DEMCR_TRCENA_Msk
#endif

typedef enum {
    hkv_segmentation_test_counter_unavailable = 0,
    hkv_segmentation_test_counter_pmu,
    hkv_segmentation_test_counter_dwt,
    hkv_segmentation_test_counter_systick,
} hkv_segmentation_test_counter_kind_t;

static hkv_segmentation_test_counter_kind_t hkv_segmentation_test_counter_kind = hkv_segmentation_test_counter_unavailable;

static void hkv_segmentation_test_cycle_counter_probe_spin(void)
{
    for (volatile uint32_t i = 0; i < 64U; ++i) {
#if defined(__NOP)
        __NOP();
#endif
    }
}

static int hkv_segmentation_test_cycle_counter_enable(void)
{
#if defined(__PMU_PRESENT) && (__PMU_PRESENT == 1U)
    uint32_t pmu_start = 0;
    uint32_t pmu_end = 0;
    ARM_PMU_Disable();
    ARM_PMU_CYCCNT_Reset();
    ARM_PMU_Enable();
    ARM_PMU_CNTR_Enable(PMU_CNTENSET_CCNTR_ENABLE_Msk);
    pmu_start = ARM_PMU_Get_CCNTR();
    hkv_segmentation_test_cycle_counter_probe_spin();
    pmu_end = ARM_PMU_Get_CCNTR();
    if (((PMU->CNTENSET & PMU_CNTENSET_CCNTR_ENABLE_Msk) != 0U) && (pmu_end != pmu_start)) {
        hkv_segmentation_test_counter_kind = hkv_segmentation_test_counter_pmu;
        return 1;
    }
#elif defined(DWT) && defined(DWT_CTRL_CYCCNTENA_Msk) && defined(HKV_SEGMENTATION_TEST_DEMCR)
    uint32_t dwt_start = 0;
    uint32_t dwt_end = 0;
    HKV_SEGMENTATION_TEST_DEMCR |= HKV_SEGMENTATION_TEST_DEMCR_TRCENA;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
    dwt_start = DWT->CYCCNT;
    hkv_segmentation_test_cycle_counter_probe_spin();
    dwt_end = DWT->CYCCNT;
    if (((DWT->CTRL & DWT_CTRL_CYCCNTENA_Msk) != 0U) && (dwt_end != dwt_start)) {
        hkv_segmentation_test_counter_kind = hkv_segmentation_test_counter_dwt;
        return 1;
    }
#endif

#if defined(SysTick) && defined(SysTick_LOAD_RELOAD_Msk) && defined(SysTick_CTRL_ENABLE_Msk) && defined(SysTick_CTRL_CLKSOURCE_Msk)
    uint32_t systick_start = 0;
    uint32_t systick_end = 0;
    SysTick->CTRL = 0;
    SysTick->LOAD = SysTick_LOAD_RELOAD_Msk;
    SysTick->VAL = 0;
    SysTick->CTRL = SysTick_CTRL_ENABLE_Msk | SysTick_CTRL_CLKSOURCE_Msk;
    systick_start = SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
    hkv_segmentation_test_cycle_counter_probe_spin();
    systick_end = SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
    if (systick_end != systick_start) {
        hkv_segmentation_test_counter_kind = hkv_segmentation_test_counter_systick;
        return 1;
    }
#endif

    hkv_segmentation_test_counter_kind = hkv_segmentation_test_counter_unavailable;
    return 0;
}

static uint32_t hkv_segmentation_test_cycle_counter_read(void)
{
    switch (hkv_segmentation_test_counter_kind) {
        case hkv_segmentation_test_counter_pmu:
#if defined(__PMU_PRESENT) && (__PMU_PRESENT == 1U)
            return ARM_PMU_Get_CCNTR();
#else
            return 0;
#endif
        case hkv_segmentation_test_counter_dwt:
#if defined(DWT) && defined(DWT_CTRL_CYCCNTENA_Msk)
            return DWT->CYCCNT;
#else
            return 0;
#endif
        case hkv_segmentation_test_counter_systick:
#if defined(SysTick) && defined(SysTick_LOAD_RELOAD_Msk)
            return SysTick_LOAD_RELOAD_Msk - SysTick->VAL;
#else
            return 0;
#endif
        default:
            return 0;
    }
}

static uint32_t hkv_segmentation_test_cycle_counter_delta(uint32_t start, uint32_t end)
{
    if (hkv_segmentation_test_counter_kind == hkv_segmentation_test_counter_systick) {
#if defined(SysTick_LOAD_RELOAD_Msk)
        const uint32_t modulo = SysTick_LOAD_RELOAD_Msk + 1U;
        return (end >= start) ? (end - start) : (modulo - start + end);
#else
        return 0;
#endif
    }
    return (uint32_t)(end - start);
}


//── Inputs ────────────────────────────────────────────────────────────────────
static const int8_t hkv_segmentation_test_stimulus_input_0[256] = {
    -15, -15, -15, -15, -15, -15, -15, -15, -15, -16, -16, -15, -15, -15, -15, -15, -15, -15, -15, -15,
    -16, -15, -15, -15, -13, -11, -8, -7, -8, -9, -12, -15, -16, -18, -17, -18, -22, 2, 53, 76,
    18, -30, -29, -19, -18, -19, -19, -19, -19, -19, -18, -18, -18, -18, -17, -17, -16, -15, -14, -12,
    -10, -8, -5, -2, 0, 1, 1, 0, -2, -6, -9, -11, -13, -14, -15, -15, -16, -16, -16, -16,
    -16, -16, -15, -15, -15, -15, -15, -15, -15, -15, -15, -16, -16, -16, -16, -16, -16, -15, -15, -15,
    -15, -15, -15, -15, -15, -15, -15, -15, -15, -15, -15, -16, -15, -15, -14, -14, -13, -11, -9, -7,
    -8, -10, -11, -14, -17, -17, -18, -19, -24, -16, 32, 77, 44, -13, -29, -20, -21, -20, -19, -20,
    -19, -20, -19, -19, -19, -19, -17, -17, -16, -15, -14, -12, -11, -8, -6, -3, 0, 0, 1, 1,
    0, -3, -6, -9, -11, -13, -14, -15, -15, -15, -15, -15, -16, -16, -15, -15, -15, -15, -16, -15,
    -15, -15, -15, -15, -16, -16, -16, -16, -16, -16, -16, -15, -15, -15, -15, -15, -15, -15, -15, -15,
    -15, -15, -16, -16, -16, -16, -15, -15, -15, -14, -14, -13, -11, -9, -8, -9, -10, -12, -14, -16,
    -17, -16, -17, -21, 0, 48, 75, 23, -30, -30, -19, -19, -20, -20, -20, -20, -21, -19, -19, -19,
    -18, -17, -17, -16, -15, -13, -12, -10, -7, -5, -2, 0, 0, 1, 0, -1
};

//── Outputs ───────────────────────────────────────────────────────────────────
static const int8_t hkv_segmentation_test_stimulus_golden_0[1024] = {
    52, -127, -121, -61, 72, -127, -125, -76, 84, -127, -126, -86, 91, -128, -128, -92, 91, -128, -128, -92,
    101, -128, -128, -101, 105, -127, -128, -105, 106, -127, -128, -107, 104, -127, -128, -105, 105, -124, -128, -109,
    102, -119, -128, -111, 96, -110, -128, -114, 88, -101, -128, -116, 86, -98, -128, -116, 87, -95, -128, -119,
    80, -87, -128, -122, 84, -89, -128, -123, 78, -83, -128, -123, 55, -60, -128, -123, 42, -45, -128, -125,
    10, -12, -128, -126, -12, 11, -128, -127, -34, 33, -128, -127, -49, 49, -128, -127, -49, 49, -128, -128,
    -59, 58, -128, -128, -59, 58, -128, -128, -58, 58, -128, -128, -49, 49, -128, -128, -28, 28, -128, -128,
    11, -12, -127, -128, 46, -50, -124, -128, 84, -101, -111, -128, 55, -123, -60, -128, -12, -127, 11, -128,
    -54, -128, 54, -128, -79, -128, 79, -128, -101, -128, 101, -128, -113, -128, 113, -128, -109, -128, 109, -128,
    -91, -128, 91, -128, -39, -128, 39, -128, -11, -128, 11, -128, 39, -128, -39, -128, 53, -128, -54, -127,
    66, -128, -68, -126, 82, -128, -90, -120, 101, -128, -121, -108, 91, -128, -127, -92, 91, -128, -128, -92,
    58, -128, -128, -58, 54, -128, -128, -54, 34, -128, -128, -34, 17, -128, -128, -17, -23, -128, -128, 23,
    -34, -128, -128, 34, -63, -128, -128, 63, -75, -128, -128, 75, -89, -128, -128, 89, -91, -128, -128, 91,
    -99, -128, -128, 99, -97, -128, -128, 97, -94, -128, -128, 94, -94, -128, -128, 94, -94, -128, -128, 94,
    -94, -128, -128, 94, -99, -128, -128, 99, -94, -128, -128, 94, -94, -128, -128, 94, -89, -128, -128, 89,
    -71, -128, -128, 71, -49, -128, -128, 49, -17, -128, -128, 17, 17, -128, -128, -17, 44, -128, -128, -44,
    67, -128, -128, -67, 82, -128, -128, -82, 88, -128, -128, -89, 94, -128, -128, -94, 96, -128, -128, -97,
    101, -128, -128, -101, 106, -127, -128, -107, 110, -127, -128, -112, 113, -126, -128, -115, 116, -126, -127, -119,
    116, -124, -127, -121, 115, -121, -127, -123, 114, -120, -127, -123, 115, -119, -127, -125, 116, -119, -127, -126,
    117, -120, -127, -127, 115, -117, -127, -127, 115, -117, -126, -127, 115, -116, -127, -127, 112, -113, -127, -128,
    109, -110, -127, -128, 106, -107, -128, -128, 105, -105, -128, -128, 101, -101, -128, -128, 101, -101, -128, -128,
    103, -103, -128, -128, 96, -97, -128, -128, 94, -94, -128, -128, 88, -89, -128, -128, 88, -89, -128, -128,
    85, -86, -128, -128, 88, -89, -128, -128, 89, -89, -128, -128, 85, -86, -128, -128, 82, -82, -128, -128,
    71, -71, -128, -128, 49, -49, -128, -128, 17, -17, -128, -128, -6, 6, -128, -128, -39, 39, -128, -128,
    -58, 58, -128, -128, -71, 71, -128, -128, -75, 75, -128, -128, -71, 71, -128, -128, -67, 67, -128, -128,
    -58, 58, -128, -128, -39, 39, -128, -128, -12, 11, -128, -128, 38, -39, -127, -128, 78, -87, -119, -128,
    74, -118, -84, -128, 10, -126, -12, -128, -59, -128, 58, -128, -82, -128, 82, -128, -103, -128, 103, -128,
    -110, -128, 110, -128, -112, -128, 112, -128, -99, -128, 99, -128, -63, -128, 63, -128, -17, -128, 17, -128,
    23, -128, -23, -128, 67, -128, -67, -128, 81, -128, -82, -127, 85, -128, -89, -123, 99, -128, -113, -114,
    97, -128, -125, -99, 85, -128, -127, -86, 71, -128, -128, -71, 49, -128, -128, -49, 28, -128, -128, -28,
    11, -128, -128, -11, -11, -128, -128, 11, -23, -128, -128, 23, -44, -128, -128, 44, -67, -128, -128, 67,
    -82, -128, -128, 82, -85, -128, -128, 85, -94, -128, -128, 94, -94, -128, -128, 94, -97, -128, -128, 97,
    -94, -128, -128, 94, -91, -128, -128, 91, -94, -128, -128, 94, -94, -128, -128, 94, -94, -128, -128, 94,
    -91, -128, -128, 91, -91, -128, -128, 91, -82, -128, -128, 82, -71, -128, -128, 71, -44, -128, -128, 44,
    -17, -128, -128, 17, 17, -128, -128, -17, 44, -128, -128, -44, 54, -128, -128, -54, 71, -128, -128, -71,
    79, -128, -128, -79, 85, -128, -128, -86, 88, -128, -128, -89, 91, -128, -128, -92, 98, -127, -128, -99,
    104, -127, -128, -105, 110, -126, -127, -112, 111, -125, -127, -114, 115, -125, -127, -118, 115, -124, -127, -120,
    115, -123, -127, -122, 113, -120, -126, -123, 116, -121, -126, -124, 116, -121, -126, -126, 117, -120, -127, -127,
    118, -121, -126, -127, 118, -121, -126, -127, 118, -121, -126, -127, 116, -118, -127, -127, 111, -113, -127, -127,
    109, -110, -127, -128, 110, -110, -128, -128, 108, -109, -128, -128, 108, -109, -128, -128, 105, -105, -128, -128,
    105, -105, -128, -128, 96, -97, -128, -128, 91, -92, -128, -128, 85, -86, -128, -128, 85, -86, -128, -128,
    85, -86, -128, -128, 85, -86, -128, -128, 85, -86, -128, -128, 85, -86, -128, -128, 75, -75, -128, -128,
    54, -54, -128, -128, 34, -34, -128, -128, 0, 0, -128, -128, -28, 28, -128, -128, -54, 54, -128, -128,
    -67, 67, -128, -128, -71, 71, -128, -128, -71, 71, -128, -128, -71, 71, -128, -128, -63, 63, -128, -128,
    -54, 54, -128, -128, -28, 28, -128, -128, 5, -6, -127, -128, 60, -64, -124, -128, 89, -105, -112, -128,
    55, -123, -60, -128, -12, -127, 11, -128, -54, -128, 54, -128, -79, -128, 79, -128, -101, -128, 101, -128,
    -112, -128, 112, -128, -109, -128, 109, -128, -89, -128, 89, -128, -44, -128, 44, -128, -11, -128, 11, -128,
    39, -128, -39, -128, 66, -128, -67, -127, 77, -128, -79, -125, 91, -128, -100, -119, 101, -128, -121, -108,
    93, -128, -127, -94, 88, -128, -128, -89, 63, -128, -128, -63, 39, -128, -128, -39, 17, -128, -128, -17,
    0, -128, -128, 0, -23, -128, -128, 23, -28, -128, -128, 28, -63, -128, -128, 63, -67, -128, -128, 67,
    -85, -128, -128, 85, -91, -128, -128, 91, -99, -128, -128, 99, -94, -128, -128, 94, -94, -128, -128, 94,
    -94, -128, -128, 94, -82, -128, -128, 82, -75, -128, -128, 75, -79, -128, -128, 79, -71, -128, -128, 71,
    -63, -128, -128, 63
};

//── Callback ──────────────────────────────────────────────────────────────────
static void hkv_segmentation_test_stimulus_callback(
    int32_t op,
    hkv_segmentation_operator_state_t state,
    int32_t status,
    void *user_data
) {
    (void)user_data;
    if (state == hkv_segmentation_op_state_init_finished) {
        HKV_SEGMENTATION_PRINTF("Operator %ld init finished with status %ld\n", (long)op, (long)status);
    }
    if (state == hkv_segmentation_op_state_run_finished) {
        HKV_SEGMENTATION_PRINTF("Operator %ld run finished with status %ld\n", (long)op, (long)status);
    }
}


//── Context ───────────────────────────────────────────────────────────────────
static hkv_segmentation_model_context_t hkv_segmentation_test_stimulus_context = {
    .callback = hkv_segmentation_test_stimulus_callback,
    .user_data = NULL
};


int32_t
hkv_segmentation_test_case_init(void)
{
    // Initialize model
    int32_t status = hkv_segmentation_model_init(
        &hkv_segmentation_test_stimulus_context
    );
    if (status != 0) {
        return status;
    }
    return 0;
}

int32_t
hkv_segmentation_test_case_run(void)
{
    int32_t result = 0;
    const int num_iterations = 1;
    const int have_cycle_counter = hkv_segmentation_test_cycle_counter_enable();
    void (*saved_callback)(int32_t, hkv_segmentation_operator_state_t, int32_t, void *) = hkv_segmentation_test_stimulus_context.callback;
    uint64_t model_run_cycles_total = 0;

    if (have_cycle_counter) {
        hkv_segmentation_test_stimulus_context.callback = NULL;
    }

    // Run the model N times on the same stimulus
    for (int iter = 0; iter < num_iterations; iter++) {
        uint32_t cycle_start = 0;
        uint32_t cycle_end = 0;

        // Copy input tensors to context (before each iteration to ensure input persists)
    arm_memcpy_s8(
        hkv_segmentation_test_stimulus_context.inputs[0].data,
        (int8_t *)hkv_segmentation_test_stimulus_input_0,
        256
    );

        if (have_cycle_counter) {
            cycle_start = hkv_segmentation_test_cycle_counter_read();
        }
        result = hkv_segmentation_model_run(&hkv_segmentation_test_stimulus_context);
        if (have_cycle_counter) {
            cycle_end = hkv_segmentation_test_cycle_counter_read();
            model_run_cycles_total += hkv_segmentation_test_cycle_counter_delta(cycle_start, cycle_end);
        }
        if (result != 0) {
            HKV_SEGMENTATION_PRINTF("Model run failed with status %ld (iteration %d)\n", (long)result, iter);
            hkv_segmentation_test_stimulus_context.callback = saved_callback;
            return result;
        }
    }

    if (have_cycle_counter) {
        const uint64_t cycles_per_iter = (num_iterations > 0)
            ? (model_run_cycles_total / (uint64_t)num_iterations)
            : 0;
        HKV_SEGMENTATION_PRINTF(
            "HELIA_E2E_METRIC counter=%s model_run_cycles_total=%llu model_run_cycles_per_iter=%llu iterations=%d\n",
            hkv_segmentation_test_counter_kind == hkv_segmentation_test_counter_pmu ? "pmu" :
            (hkv_segmentation_test_counter_kind == hkv_segmentation_test_counter_dwt ? "dwt" : "systick"),
            (unsigned long long)model_run_cycles_total,
            (unsigned long long)cycles_per_iter,
            num_iterations
        );
    } else {
        HKV_SEGMENTATION_PRINTF("HELIA_E2E_METRIC model_run_cycles_unavailable=1 iterations=%d\n", num_iterations);
    }

    hkv_segmentation_test_stimulus_context.callback = saved_callback;

    // Verify outputs once after all iterations
    int8_t *act_0 = (int8_t *)hkv_segmentation_test_stimulus_context.outputs[0].data;
    int8_t *exp_0 = (int8_t *)hkv_segmentation_test_stimulus_golden_0;
    for (int i = 0; i < 1024; i++) {
        int act = (int)act_0[i];
        int exp = (int)exp_0[i];
        int diff = abs(act - exp);
        if (diff > (int)1.0) {
            HKV_SEGMENTATION_PRINTF("Output mismatch at index [%d][%d]: expected %d, got %d (diff=%d)\n", 0, i, exp, act, diff);
            result = 1;
        }
    }

    // Check for errors
    if (result == 0) {
        HKV_SEGMENTATION_PRINTF("Test passed!\n");
    } else {
        HKV_SEGMENTATION_PRINTF("Test failed!\n");
    }
    return result;

}