/******************************************************************************
 * @file        hkv_segmentation_mean_13.c
 * @brief       Autogenerated AOT mean kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '13' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_mean_13.h"


// Input dimensions
static const cmsis_nn_dims mean_13_input_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 24
};

// Axis dimensions: either 0 or 1 w/ 1 indicating reduction axis
static const cmsis_nn_dims mean_13_axis_dims = {
    .n = 0, .h = 1,
    .w = 1, .c = 0
};

// Output dimensions
static const cmsis_nn_dims mean_13_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 24
};

// Quantization parameters
static const int32_t mean_13_input_zero_point = -128;
static const int32_t mean_13_output_zero_point = -128;
static const int32_t mean_13_multiplier = 1075480505;
static const int32_t mean_13_shift = -5;


int32_t
hkv_segmentation_mean_13_init(
    hkv_segmentation_model_context_t *ctx
) {

    return 0;
}

int32_t
hkv_segmentation_mean_13_run(
    hkv_segmentation_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_51];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_52];

    return arm_mean_s8(
        input,
        &mean_13_input_dims,
        -mean_13_input_zero_point,
        &mean_13_axis_dims,
        output,
        &mean_13_output_dims,
        mean_13_output_zero_point,
        mean_13_multiplier,
        mean_13_shift
    );

}