/******************************************************************************
 * @file        hkv_segmentation_softmax_30.c
 * @brief       Autogenerated AOT softmax kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '30' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_softmax_30.h"

// Softmax parameters
static const int32_t softmax_30_num_rows = 256;
static const int32_t softmax_30_row_size = 4;
static const int32_t softmax_30_input_multiplier = 1540592256;
static const int32_t softmax_30_input_shift = 23;

static const int32_t softmax_30_diff_min = -248;

int32_t
hkv_segmentation_softmax_30_init(
    hkv_segmentation_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_segmentation_softmax_30_run(
    hkv_segmentation_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_68];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_69];

    arm_softmax_s8(
        input,
        softmax_30_num_rows,
        softmax_30_row_size,
        softmax_30_input_multiplier,
        softmax_30_input_shift,
        softmax_30_diff_min,
        output
    );

    return 0;

}