/******************************************************************************
 * @file        hkv_segmentation_depthwise_conv_2d_20.c
 * @brief       Autogenerated AOT depthwise_conv_2d kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '20' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_depthwise_conv_2d_20.h"

// Input dimensions: input shape is [N, H_IN, W_IN, C_IN]
static const cmsis_nn_dims depthwise_conv_2d_20_input_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 32
};

// Filter dimensions: weights shape is [1, H_FILT, W_FILT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_20_filter_dims = {
    .n = 1, .h = 1,
    .w = 7, .c = 32
};

// Bias dimensions: bias shape is [1, 1, 1, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_20_bias_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 32
};

// Output dimensions: output shape is [N, H_OUT, W_OUT, C_OUT].
static const cmsis_nn_dims depthwise_conv_2d_20_output_dims = {
    .n = 1, .h = 1,
    .w = 256, .c = 32
};

// Quantization parameters (per-channel quantization)

static const int32_t depthwise_conv_2d_20_input_zero_point = -128;
static const int32_t depthwise_conv_2d_20_output_zero_point = -128;

// Scratch buffer context
static cmsis_nn_context depthwise_conv_2d_20_ctx = {
    .buf = NULL,
    .size = 0,
};

// Weight sum context
static cmsis_nn_context depthwise_conv_2d_20_weight_sum_ctx = {
    .buf = NULL,
    .size = 0,
};


const cmsis_nn_dw_conv_params depthwise_conv_2d_20_params = {
    .input_offset = -depthwise_conv_2d_20_input_zero_point,
    .output_offset = depthwise_conv_2d_20_output_zero_point,
    .ch_mult = 1,
    .stride.w = 1,
    .stride.h = 1,
    .padding.w = 24,
    .padding.h = 0,
    .dilation.w = 8,
    .dilation.h = 1,
    .activation.min = -128,
    .activation.max = 127,
};

int32_t
hkv_segmentation_depthwise_conv_2d_20_init(
    hkv_segmentation_model_context_t *ctx
) {

    depthwise_conv_2d_20_ctx.buf = NULL;
    depthwise_conv_2d_20_ctx.size = 0;

    depthwise_conv_2d_20_weight_sum_ctx.buf = NULL;
    depthwise_conv_2d_20_weight_sum_ctx.size = 0;
    return 0;
}


int32_t
hkv_segmentation_depthwise_conv_2d_20_run(
    hkv_segmentation_model_context_t *ctx
) {
    const int8_t* __restrict input = (const int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_58];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_59];

    // Per-channel quantization tables resolved from interned constant tensors.
    const cmsis_nn_per_channel_quant_params depthwise_conv_2d_20_quant_params = {
        .multiplier = (int32_t *)ctx->tensor_ptrs[hkv_segmentation_tensor_depthwise_conv_2d_20_multiplier],
        .shift = (int32_t *)ctx->tensor_ptrs[hkv_segmentation_tensor_depthwise_conv_2d_20_shift],
    };


    return arm_depthwise_conv_s8(
        &depthwise_conv_2d_20_ctx,
        &depthwise_conv_2d_20_params,
        &depthwise_conv_2d_20_quant_params,
        &depthwise_conv_2d_20_input_dims,
        input,
        &depthwise_conv_2d_20_filter_dims,
        (int8_t *)ctx->tensor_ptrs[hkv_segmentation_tensor_13],
        &depthwise_conv_2d_20_bias_dims,
        (int32_t *)ctx->tensor_ptrs[hkv_segmentation_tensor_12],
        &depthwise_conv_2d_20_output_dims,
        output
    );

}