/******************************************************************************
 * @file        hkv_segmentation_minimum_24.c
 * @brief       Autogenerated AOT minimum kernel
 * @details     This file was generated by heliaAOT v0.19.0 on 2026-09-06.
 *              This kernel represents node '24' in the corresponding graph.
 * @date        2026-09-06
 * @version     0.19.0
 *
 * @copyright
 *   © 2026 Ambiq. All rights reserved.
 *
 *   This generated C module is licensed for use **only** on Ambiq hardware
 *   incorporating Ambiq's sub-threshold power optimized technology.
 *   Any other use is strictly prohibited.
 *
 *   See “LICENSE” at the root of this distribution for full terms.
 *
 * @note        Do not edit this file—any changes will be overwritten.
 ******************************************************************************/

#include "hkv_segmentation_common.h"
#include "hkv_segmentation_minimum_24.h"


// Input1 dimensions
static const cmsis_nn_dims minimum_24_input1_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 32
};

// Input2 dimensions
static const cmsis_nn_dims minimum_24_input2_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 1
};

// Output dimensions
static const cmsis_nn_dims minimum_24_output_dims = {
    .n = 1, .h = 1,
    .w = 1, .c = 32
};

// NOTE: No scratch buffer needed for minimum
static cmsis_nn_context minimum_24_ctx = {
    .buf = NULL,
    .size = 0,
};


int32_t
hkv_segmentation_minimum_24_init(
    hkv_segmentation_model_context_t *ctx
) {
    return 0;
}

int32_t
hkv_segmentation_minimum_24_run(
    hkv_segmentation_model_context_t *ctx
) {
    const int8_t* __restrict input1 = (const int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_62];
    const int8_t* __restrict input2 = (const int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_26];
    int8_t* __restrict output = (int8_t*)ctx->tensor_ptrs[hkv_segmentation_tensor_63];

    return arm_minimum_s8(
        &minimum_24_ctx,
        input1,
        &minimum_24_input1_dims,
        input2,
        &minimum_24_input2_dims,
        output,
        &minimum_24_output_dims
    );

}