// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
// Generated by tools/aot/golden_to_c.py -- do not edit. See #37.
//
// Model: arrhythmia (assets/arrhythmia.tflite)
// model_sha256: a1855af0e0b2a346d773e0d36ff8c8b986c51db4aed99a6066c9da9f23f12eab
// Cases (8), each npz listed with its sha256:
//   0: golden-arr.npz 6c4744fc7ff561cca034b1f61210a44ddefcf2394812aaf74f8959f61319ba7c
//   1: golden-arr_case01.npz 5d442a818c6e646a9dca2182b73689c9db2b849ea766d906f66fb56809cc2d97
//   2: golden-arr_case02.npz e0c001b812567814288be7403e96ecbafa7f13724326d517e00b5a61323bfec6
//   3: golden-arr_case03.npz 3d252c14ecbfbae43273a83a0011235b855aaeb4e7333bba0cd279101406eed7
//   4: golden-arr_case04.npz ef78ce319473798efd480f5a95c86a47a986e1fd7943a968d049977a8b22aea3
//   5: golden-arr_case05.npz 0fd49353125157860134e3c8dd68d92874c190d9a35b98e7dc9c7f22721f3d17
//   6: golden-arr_case06.npz a5dca10f6e67925c3cefcb36f99a4fa0d9829ed60e493d2aa1556bf85079980c
//   7: golden-arr_case07.npz e2b46eafe534c109ce43d525c77826169f95e026e76c1a73f703899eb02e6b49

#ifndef __HKV_GOLDEN_ARR_CASES_H
#define __HKV_GOLDEN_ARR_CASES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GOLDEN_ARR_NUM_CASES 8
#define GOLDEN_ARR_INPUT_LEN 500
#define GOLDEN_ARR_OUTPUT_LEN 4

extern const float golden_arr_inputs[GOLDEN_ARR_NUM_CASES][GOLDEN_ARR_INPUT_LEN];
extern const float golden_arr_outputs[GOLDEN_ARR_NUM_CASES][GOLDEN_ARR_OUTPUT_LEN];

#ifdef __cplusplus
}
#endif

#endif // __HKV_GOLDEN_ARR_CASES_H
