// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
// Generated by tools/aot/golden_to_c.py -- do not edit. See #37.
//
// Model: denoise (assets/denoise.tflite)
// model_sha256: e94a5788163e436d63750cb9dd462932cc281863d5d42d0c4851fd85a1b89d0a
// Cases (8), each npz listed with its sha256:
//   0: golden-den.npz c337bb90f06d13ae1055a749eb94bd8749be01366773e451d11a4fae875b8880
//   1: golden-den_case01.npz d02557da66ecc7803ec62e0158bf57f4414aba8c6efa3abbfb208f1681ba7e48
//   2: golden-den_case02.npz cff5e39fc6f14137925a2b600ad2d65c29ac912846f059633271f933c0a3c2d0
//   3: golden-den_case03.npz 20c946ee337a0718c2fda00b5077b48719e92907a33edb2bfd2ecc21fcbd5b26
//   4: golden-den_case04.npz 9c40a8839b703d32a146b0d84a014d4265b3a82df669eadf2e1fc34b7004230c
//   5: golden-den_case05.npz b595c4bfd17b5790abf17f6ca764be0d986ea8e3a01aaf6ee72f4e62e88dd738
//   6: golden-den_case06.npz be21cb23b58e2256cd4f0d09d856c7d886f2056235d08f0cac7c8144618cf1e8
//   7: golden-den_case07.npz e571cfb439bea5bf147be60e4b7323c3685090d96904b4d83d2710c1d6e0ba91

#ifndef __HKV_GOLDEN_DEN_CASES_H
#define __HKV_GOLDEN_DEN_CASES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GOLDEN_DEN_NUM_CASES 8
#define GOLDEN_DEN_INPUT_LEN 256
#define GOLDEN_DEN_OUTPUT_LEN 256

extern const float golden_den_inputs[GOLDEN_DEN_NUM_CASES][GOLDEN_DEN_INPUT_LEN];
extern const float golden_den_outputs[GOLDEN_DEN_NUM_CASES][GOLDEN_DEN_OUTPUT_LEN];

#ifdef __cplusplus
}
#endif

#endif // __HKV_GOLDEN_DEN_CASES_H
