// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
// Generated by tools/aot/golden_to_c.py -- do not edit. See #37.
//
// Model: segmentation (assets/segmentation.tflite)
// model_sha256: 93c4493a1d09e1818abaffd74973d807b9e6830e5a03217b2c777abe1032e6fe
// Cases (8), each npz listed with its sha256:
//   0: golden-seg.npz 019bcf4daeebefa4fdc1b0ff8161be0e974f2e9604bcfb9bc8ab7fb423addc70
//   1: golden-seg_case01.npz 0026763c319976afe5d61ab08a233a5019fefb93f5e11605ec1e13b07d0783a8
//   2: golden-seg_case02.npz 9ab5d2ded79c95c0b5da15e41a2392ae986639502c278d097abc7fa96d3a6140
//   3: golden-seg_case03.npz 0d904dc543ea34ac87338463b51d37b110b61e2bb1c05324792c5f9e707f31d1
//   4: golden-seg_case04.npz 4be5f16a956f909782add9eacda41c017b73bd35611231c7409e2a8cbe4932c4
//   5: golden-seg_case05.npz 61c5b919baa9ce7ffe784974b12d9623c0c9603aa62b4336c403fb03cf417162
//   6: golden-seg_case06.npz 0716e45a55f8b7d8dfbdc4f62d5b3fab1a4035578f212cac8f958fa9ac21942e
//   7: golden-seg_case07.npz da3b8d82c9fc351f11a8c8bedfb3d9b004828732429dd8b1c0a319fd73719b91

#ifndef __HKV_GOLDEN_SEG_CASES_H
#define __HKV_GOLDEN_SEG_CASES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GOLDEN_SEG_NUM_CASES 8
#define GOLDEN_SEG_INPUT_LEN 256
#define GOLDEN_SEG_OUTPUT_LEN 1024

extern const int8_t golden_seg_inputs[GOLDEN_SEG_NUM_CASES][GOLDEN_SEG_INPUT_LEN];
extern const int8_t golden_seg_outputs[GOLDEN_SEG_NUM_CASES][GOLDEN_SEG_OUTPUT_LEN];

#ifdef __cplusplus
}
#endif

#endif // __HKV_GOLDEN_SEG_CASES_H
