// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
// Generated by tools/aot/golden_to_c.py -- do not edit. See #37.
//
// Model: arrhythmia (assets/arrhythmia.tflite)
// model_sha256: a1855af0e0b2a346d773e0d36ff8c8b986c51db4aed99a6066c9da9f23f12eab
// Cases (8), each npz listed with its sha256:
//   0: golden-arr.npz eb4e2eb8a61f39298d28a23ebd8920be90245733323aeaffdadaea4a5d91f0f8
//   1: golden-arr_case01.npz 49fe7e42084ef492f0bcd97ec3f3975bca85ace47da13963e817b31770ad1b67
//   2: golden-arr_case02.npz 2d97e91f8349927d13a83842bb8ddf862c2d47527f36419e59d7ac46ad7722e2
//   3: golden-arr_case03.npz 5c9a60f089fb65a800dff7d32d1b3e8869002cd3d268322fe836934861624723
//   4: golden-arr_case04.npz 94bb328494418be20c38ea0a8cd14f17847d98cdd932b3545e77b51e65cb9a23
//   5: golden-arr_case05.npz 93f1f3926ded4c80531cc68ccc85073cc038863abd0217df2c7cc9015cea2ff0
//   6: golden-arr_case06.npz 6d06146be604a16c12180b8d016a46825cb9aaa3ac8745d94d5c77e55d1deaa1
//   7: golden-arr_case07.npz 34536bf9b9ea3325bb22f8f07fd1916c3adf2460c3753e1623ef54b924bc7ed8

#ifndef __HKV_GOLDEN_ARR_CASES_H
#define __HKV_GOLDEN_ARR_CASES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GOLDEN_ARR_NUM_CASES 8
#define GOLDEN_ARR_INPUT_LEN 500
#define GOLDEN_ARR_OUTPUT_LEN 4

extern const float golden_arr_inputs[GOLDEN_ARR_NUM_CASES][GOLDEN_ARR_INPUT_LEN];
extern const float golden_arr_outputs[GOLDEN_ARR_NUM_CASES][GOLDEN_ARR_OUTPUT_LEN];

#ifdef __cplusplus
}
#endif

#endif // __HKV_GOLDEN_ARR_CASES_H
