// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
// Generated by tools/aot/golden_to_c.py -- do not edit. See #37.
//
// Model: segmentation (assets/segmentation.tflite)
// model_sha256: 93c4493a1d09e1818abaffd74973d807b9e6830e5a03217b2c777abe1032e6fe
// Cases (8), each npz listed with its sha256:
//   0: golden-seg.npz 437aa89014c1d1b55a15c9fde5cd6403b2727c4c4de73090ce4a3d0ffd14ac8c
//   1: golden-seg_case01.npz 7d8a2e621c36a48d738de5614dfbccc5011845a663def8d933055bed61b7130d
//   2: golden-seg_case02.npz 20a9db78afeeb2aba4f2d616bf70a4d5d2fe083796951cdf1a6569d4d8afa9ee
//   3: golden-seg_case03.npz d80ad07fbf0dcc0f84725fbbb02851f28891883ba962da17199fe92b3319decb
//   4: golden-seg_case04.npz f79da2f7d03b2be721735fe4076054a8495f5e939d7b1cc088013ee4e84a536e
//   5: golden-seg_case05.npz fbdef62bb9722d63745b2fe6891c4384af8806b9b528f2b9d12883506cac4c03
//   6: golden-seg_case06.npz 820309795c21d0875d6f86e1ea4537b897c164697e82fa11326d091894828e30
//   7: golden-seg_case07.npz 37089025e9a5ea351e6a1927543ae6bc572a3daa66f7b275b002ce92f9b47281

#ifndef __HKV_GOLDEN_SEG_CASES_H
#define __HKV_GOLDEN_SEG_CASES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GOLDEN_SEG_NUM_CASES 8
#define GOLDEN_SEG_INPUT_LEN 256
#define GOLDEN_SEG_OUTPUT_LEN 1024

extern const int8_t golden_seg_inputs[GOLDEN_SEG_NUM_CASES][GOLDEN_SEG_INPUT_LEN];
extern const int8_t golden_seg_outputs[GOLDEN_SEG_NUM_CASES][GOLDEN_SEG_OUTPUT_LEN];

#ifdef __cplusplus
}
#endif

#endif // __HKV_GOLDEN_SEG_CASES_H
