#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026, Ambiq
"""Emit the golden model I/O fixtures as C arrays for the on-device parity runner.

    python3 tools/aot/golden_to_c.py            # write tools/aot/parity/*.c/.h
    python3 tools/aot/golden_to_c.py --check    # regenerate to $TMPDIR, fail on drift

Reads `tools/aot/golden/golden-<m>.json` and the eight npz it lists, and writes
`golden_<m>_cases.c/.h` holding the inputs and outputs in the model's native
dtype (int8 for segmentation, float32 for denoise and arrhythmia). No dequantization and no
reshaping happens here: the runner memcpy's the input straight into the module's
input tensor and compares raw output bytes, so any transform applied on the host
would hide exactly the mismatch the runner exists to find.

Output is byte-for-byte reproducible from the committed fixtures, which is what
`--check` enforces in CI. See AmbiqAI/heartkit-vitals-demo#37.
"""

import argparse
import filecmp
import hashlib
import json
import sys
import tempfile
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
GOLDEN_DIR = REPO_ROOT / "tools" / "aot" / "golden"
OUT_DIR = REPO_ROOT / "tools" / "aot" / "parity"

# model key -> (C identifier prefix, guard stem, human name)
MODELS = {
    "den": ("golden_den", "GOLDEN_DEN", "denoise"),
    "seg": ("golden_seg", "GOLDEN_SEG", "segmentation"),
    "arr": ("golden_arr", "GOLDEN_ARR", "arrhythmia"),
}

BANNER = """// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
// Generated by tools/aot/golden_to_c.py -- do not edit. See #37.
//
// Model: {name} ({model_path})
// model_sha256: {model_sha256}
// Cases ({ncases}), each npz listed with its sha256:
{case_lines}
"""


def sha256_file(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_model(key):
    """Return (sidecar, [(npz_path, input_array, output_array), ...])."""
    sidecar = json.loads((GOLDEN_DIR / f"golden-{key}.json").read_text())
    cases = []
    for case in sidecar["cases"]:
        path = GOLDEN_DIR / case["path"]
        with np.load(path) as npz:
            cases.append((path, npz["input_0"], npz["output_0"]))
    return sidecar, cases


def fmt_i8(values):
    return [", ".join(f"{int(v):4d}" for v in values[i : i + 16]) for i in range(0, len(values), 16)]


def c_float(value):
    # .9g round-trips every float32 exactly, so the device sees the fixture bit
    # pattern the reference interpreter produced. It also renders whole values
    # without a decimal point, where the `f` suffix would be an integer suffix.
    text = f"{float(value):.9g}"
    if not any(ch in text for ch in ".e"):
        text += ".0"
    return text + "f"


def fmt_f32(values):
    return [", ".join(c_float(v) for v in values[i : i + 8]) for i in range(0, len(values), 8)]


def emit(key, out_dir):
    prefix, guard, name = MODELS[key]
    sidecar, cases = load_model(key)
    dtype = cases[0][1].dtype
    is_i8 = dtype == np.int8
    ctype = "int8_t" if is_i8 else "float"
    fmt = fmt_i8 if is_i8 else fmt_f32
    in_len = int(cases[0][1].size)
    out_len = int(cases[0][2].size)

    for path, xin, xout in cases:
        if xin.size != in_len or xout.size != out_len or xin.dtype != dtype or xout.dtype != dtype:
            raise SystemExit(f"{path.name}: shape/dtype differs from case 0")

    banner = BANNER.format(
        name=name,
        model_path=sidecar["model_path"],
        model_sha256=sidecar["model_sha256"],
        ncases=len(cases),
        case_lines="\n".join(
            f"//   {i}: {p.name} {sha256_file(p)}" for i, (p, _, _) in enumerate(cases)
        ),
    )

    header = [
        banner,
        f"#ifndef __HKV_{guard}_CASES_H",
        f"#define __HKV_{guard}_CASES_H",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        f"#define {guard}_NUM_CASES {len(cases)}",
        f"#define {guard}_INPUT_LEN {in_len}",
        f"#define {guard}_OUTPUT_LEN {out_len}",
        "",
        f"extern const {ctype} {prefix}_inputs[{guard}_NUM_CASES][{guard}_INPUT_LEN];",
        f"extern const {ctype} {prefix}_outputs[{guard}_NUM_CASES][{guard}_OUTPUT_LEN];",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        f"#endif // __HKV_{guard}_CASES_H",
        "",
    ]

    source = [banner, f'#include "{prefix}_cases.h"', ""]
    for arrays, kind, length in ((1, "inputs", in_len), (2, "outputs", out_len)):
        source.append(f"const {ctype} {prefix}_{kind}[{guard}_NUM_CASES][{guard}_{kind[:-1].upper()}_LEN] = {{")
        for idx, case in enumerate(cases):
            source.append(f"    {{ // case {idx}")
            for chunk in fmt(np.asarray(case[arrays]).reshape(length)):
                source.append(f"        {chunk},")
            source.append("    },")
        source.append("};")
        source.append("")

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{prefix}_cases.h").write_text("\n".join(header))
    (out_dir / f"{prefix}_cases.c").write_text("\n".join(source))
    return [f"{prefix}_cases.h", f"{prefix}_cases.c"]


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="regenerate to a temp dir and diff")
    args = ap.parse_args()

    if not args.check:
        for key in MODELS:
            for fname in emit(key, OUT_DIR):
                print(f"wrote {OUT_DIR / fname}")
        return 0

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        drift = []
        for key in MODELS:
            for fname in emit(key, tmp_dir):
                committed = OUT_DIR / fname
                if not committed.exists() or not filecmp.cmp(
                    committed, tmp_dir / fname, shallow=False
                ):
                    drift.append(fname)
        if drift:
            print("golden C fixtures are stale: " + ", ".join(sorted(drift)), file=sys.stderr)
            print("run: python3 tools/aot/golden_to_c.py", file=sys.stderr)
            return 1
    print("golden C fixtures match the committed goldens")
    return 0


if __name__ == "__main__":
    sys.exit(main())
